### ISSUE TITLE
`Error: Plugin did not respond`,  `panic: interface conversion: interface {} is string, not float64`

### ISSUE THREAD

**Issue by whoisnobody** [Telmate/terraform-provider-proxmox#1059]
Hello,
I am unable to clone a new machine using `terraform init`. 

Error:
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.mongodb.proxmox_vm_qemu.vm[0]: Creating...
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the
│ output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering
│ from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.mongodb.proxmox_vm_qemu.vm[0],
│   on ../modules/debian-v3/main.tf line 40, in resource "proxmox_vm_qemu" "vm":
│   40: resource "proxmox_vm_qemu" "vm" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 32 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0005a4180, 0xc000492780?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.prepareDiskSize(0x0?, 0xc0004944e0?, 0x7?, 0xc000322000?)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1737 +0xeb
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0001aec80, {0xb66f60?, 0xc000268a50})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1059 +0x1cb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc000246150?}, 0xd?, {0xb66f60?, 0xc000268a50?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000f6ee0, {0xdd7840, 0xc000246150}, 0xc00033c340, 0xc0001aeb00, {0xb66f60, 0xc000268a50})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000403ef0, {0xdd7840?, 0xc000246030?}, 0xc0004502d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002983c0, {0xdd7840?, 0xc0000a4f00?}, 0xc0001b01c0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc0002983c0}, {0xdd7840, 0xc0000a4f00}, 0xc0001b0000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023e1e0, {0xddb420, 0xc0003129c0}, 0xc00032e000, 0xc0004117d0, 0x128f7a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00023e1e0, {0xddb420, 0xc0003129c0}, 0xc00032e000, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

Steps to reproduce:
`terraform apply --target=module.mongodb`

Last log:
```
2024/07/24 12:18:24 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK
Content-Length: 1013
Cache-Control: max-age=0
Connection: Keep-Alive
Content-Type: application/json;charset=UTF-8
Date: Wed, 24 Jul 2024 10:18:23 GMT
Expires: Wed, 24 Jul 2024 10:18:23 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0

{"data":{"sockets":1,"unused0":"raid-6G-600GB:9064/vm-9064-disk-0.qcow2","digest":"78336efcb484db75a489a4b5fd6af0db5394127f","ide0":"raid-6G-600GB:9064/vm-9064-cloudinit.qcow2,media=cdrom,size=4M","numa":0,"virtio0":"raid-6G-600GB:9064/vm-9064-disk-3.raw,cache=writethrough,discard=on,size=60G","onboot":1,"vmgenid":"6b9ccf8d-17e9-47e8-abc2-cf4d5b5c2502","smbios1":"uuid=2f264390-804b-4949-9e84-558a49d0d46f","ostype":"other","scsihw":"virtio-scsi-pci","agent":"1","tablet":1,"meta":"creation-qemu=8.1.5,ctime=1721811202","boot":"order=virtio0;ide2;net0","cpu":"host","unused2":"raid-6G-600GB:9064/vm-9064-disk-2.raw","ide2":"none,media=cdrom","memory":"6144","ipconfig0":"ip=192.168.90.64/16,gw=192.168.90.1","net0":"virtio=02:76:92:05:3F:F4,bridge=vmbr0,firewall=1","hotplug":"network,disk,usb","name":"mongodb","description":"Debian server bookworm image","kvm":1,"cicustom":"user=local:snippets/cloud_init_9064.yml","unused1":"raid-6G-600GB:9064/vm-9064-disk-1.raw","bios":"seabios","balloon":4096,"cores":2}}

```

**Comment by valynkoandrei** [comment]
the same error

**Comment by Tinyblargon** [comment]
@whoisnobody 2.x is currently broken, and fixing it requires breaking changes see release 3.0RC3
