### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by grioghar** [Telmate/terraform-provider-proxmox#1163]
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.k8s_master[1],
│   on main.tf line 40, in resource "proxmox_vm_qemu" "k8s_master":
│   40: resource "proxmox_vm_qemu" "k8s_master" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.2 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 55 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000111678, 0xc000385680, 0xc000386a20, 0x0, 0x0)
	github.com/Telmate/proxmox-api-go@v0.0.0-20211101191122-8bbe30eb7171/proxmox/config_qemu.go:556 +0x5a39
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc0000a2800, 0x17b0ce0, 0xc000385810, 0x0, 0x0)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1218 +0x3cf
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0xc0000a2800, 0x17b0ce0, 0xc000385810, 0x1e6c2d0, 0xc000680000)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1190 +0x3f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001a27e0, 0x19f0398, 0xc0001f0600, 0xc0000a2800, 0x17b0ce0, 0xc000385810, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001a27e0, 0x19f0398, 0xc0001f0600, 0xc00011cdd0, 0x17b0ce0, 0xc000385810, 0xc000286d38, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012b2d8, 0x19f0398, 0xc0001f0600, 0xc0001f0640, 0xc0001f0600, 0x100b665, 0x188a820)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x47d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0005106a0, 0x19f0440, 0xc0001f0600, 0xc000620540, 0xc0005106a0, 0xc00009e8a0, 0xc0004e5ba0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x18b8420, 0xc0005106a0, 0x19f0440, 0xc00009e8a0, 0xc0006204e0, 0x0, 0x19f0440, 0xc00009e8a0, 0xc0004f6000, 0x51b)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002768c0, 0x19f7d98, 0xc000683b00, 0xc0006cde60, 0xc000282750, 0x1e2fd90, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002768c0, 0x19f7d98, 0xc000683b00, 0xc0006cde60, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000120420, 0xc0002768c0, 0x19f7d98, 0xc000683b00, 0xc0006cde60)
	google.golang.org/grpc@v1.42.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.42.0/server.go:919 +0x1fd

Error: The terraform-provider-proxmox_v2.9.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by amirsalehag** [comment]
I get the same issue.

**Comment by Tinyblargon** [comment]
Currently 2.x is broken. The library used in 2.x has had lots of development, so back porting is reather difficult. For now, we recommend using 3.0.1rc5 as it also fixes lots of bugs that were lurking in 2.x.

**Comment by amirsalehag** [comment]
@Tinyblargon 
im using the last version
Error: The terraform-provider-proxmox_v3.0.1-rc5 plugin crashed!

**Comment by Tinyblargon** [comment]
@amirsalehag could you post the cpu settings you are using? I'll try to reproduce the crash.

**Comment by amirsalehag** [comment]
@Tinyblargon 
you mean my system's cpu?
13th Gen Intel(R) Core(TM) i7-13700H

**Comment by Tinyblargon** [comment]
@amirsalehag found the bug:
Never check if `config.Type` is `nil` before de-referencing it.

https://github.com/Telmate/terraform-provider-proxmox/blob/09269ddc3dff3f982bb96be7a002b951769f4958/proxmox/Internal/resource/guest/qemu/cpu/terraform.go#L18-L22

**Comment by Tinyblargon** [comment]
@amirsalehag #1179 is merged. Gonna release RC6. keeping this issue open as it started about a different crashing issue.

**Comment by amirsalehag** [comment]
@Tinyblargon 
tnx mate.

**Comment by 4ydan** [comment]
I get a similar crashing issue for having a PCI device attached to a VM I am trying to import via opentofu.
When I detach the PCI device, the error message is gone.


```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-proxmox_v3.0.2-rc01 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9cf3ed]

goroutine 87 [running]:
github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/qemu/pci.terraformSubroutinePCIs({0x0?, 0xc000a22f00?, 0x0?})
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/qemu/pci/terraform.go:175 +0x20d
github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/qemu/pci.terraformPCIs(0xc0019f2cc0)
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/qemu/pci/terraform.go:154 +0xe5
github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/qemu/pci.Terraform(0xc0019f2cc0, 0xc00177a900)
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/qemu/pci/terraform.go:17 +0xbf
github.com/Telmate/terraform-provider-proxmox/v2/proxmox.resourceVmQemuRead({0x1034bb8, 0xc0007445b0}, 0xc00177a900, {0xd287e0?, 0xc00055c5a0})
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_vm_qemu.go:1138 +0x1605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003b9700, {0x1034b10, 0xc000a2d080}, 0xc00177a900, {0xd287e0, 0xc00055c5a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:866 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003b9700, {0x1034b10, 0xc000a2d080}, 0xc000635520, {0xd287e0, 0xc00055c5a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:1162 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003a6000, {0x1034b10?, 0xc000a2cfc0?}, 0xc000db46e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/grpc_provider.go:908 +0xb6d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002960a0, {0x1034b10?, 0xc000a2c1e0?}, 0xc0003d0620)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/tf5server/server.go:859 +0x2f3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xeae720, 0xc0002960a0}, {0x1034b10, 0xc000a2c1e0}, 0xc00028e100, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:651 +0x1a9
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ea000, {0x1034b10, 0xc000a2c150}, 0xc00005c780, 0xc0000f7290, 0x16a2f18, 0x0)
        google.golang.org/grpc@v1.72.1/server.go:1405 +0x1036
google.golang.org/grpc.(*Server).handleStream(0xc0003ea000, {0x10354d0, 0xc00054a000}, 0xc00005c780)
        google.golang.org/grpc@v1.72.1/server.go:1815 +0xb88
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.72.1/server.go:1035 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 38
        google.golang.org/grpc@v1.72.1/server.go:1046 +0x11d

Error: The terraform-provider-proxmox_v3.0.2-rc01 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by alexandergmiles** [comment]
I'm getting a similar issue when trying to update qemu guest that has an ISO unmounted from the (scsi0) Cdrom. I have since moved to correctly using ide2 for boot ISO but hope this is still of some use.

```golang
Stack trace from the terraform-provider-proxmox_v3.0.2-rc05 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 115 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*ConfigQemu).mapToStruct(0x140001c21e0, 0x14000d3ab90?, 0x14000ce3920)
        github.com/Telmate/proxmox-api-go@v0.0.0-20251016192144-4a331a14ad5c/proxmox/config__qemu.go:398 +0x118c
github.com/Telmate/proxmox-api-go/proxmox.(*rawConfigQemu).get(0x14001c609b0, 0x14000d3ab90)
        github.com/Telmate/proxmox-api-go@v0.0.0-20251016192144-4a331a14ad5c/proxmox/config__qemu.go:1149 +0x3c4
github.com/Telmate/proxmox-api-go/proxmox.(*rawConfigQemu).Get(0x14000aab7a0?, 0x10117ace2?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20251016192144-4a331a14ad5c/proxmox/config__qemu.go:1123 +0x1c
github.com/Telmate/terraform-provider-proxmox/v2/proxmox.resourceVmQemuRead({0x1014f8ab8, 0x14000ac0f50}, 0x14000aab7a0, {0x101336460?, 0x14000819db0})
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_vm_qemu.go:997 +0x59c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000013800, {0x1014f8a10, 0x14001f7ce10}, 0x14000aab7a0, {0x101336460, 0x14000819db0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:866 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000013800, {0x1014f8a10, 0x14001f7ce10}, 0x140009825b0, {0x101336460, 0x14000819db0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:1162 +0x400
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000372030, {0x1014f8a10?, 0x14001f7cd50?}, 0x14000c60320)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/grpc_provider.go:908 +0x9bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400027e140, {0x1014f8a10?, 0x14001f7c1e0?}, 0x14000ac00e0)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/tf5server/server.go:859 +0x210
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1014c9960, 0x1400027e140}, {0x1014f8a10, 0x14001f7c1e0}, 0x14000194b80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:651 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400025a400, {0x1014f8a10, 0x14001f7c150}, 0x140007d4120, 0x14000746c90, 0x101b63258, 0x0)
        google.golang.org/grpc@v1.72.1/server.go:1405 +0xc9c
google.golang.org/grpc.(*Server).handleStream(0x1400025a400, {0x1014f9350, 0x140007b8000}, 0x140007d4120)
        google.golang.org/grpc@v1.72.1/server.go:1815 +0x900
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.72.1/server.go:1035 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 35
        google.golang.org/grpc@v1.72.1/server.go:1046 +0x138

```
