### ISSUE TITLE
Error: Plugin did not respond - The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

### ISSUE THREAD

**Issue by PSClearn01** [Telmate/terraform-provider-proxmox#1203]
Stack trace from the terraform-provider-proxmox_v2.9.11 plugin:

panic: assignment to entry in nil map

goroutine 49 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceLxcCreate(0x0?, {0xb2bec0?, 0xc00026f8b0?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:570 +0x1987
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd847f0?, {0xd847f0?, 0xc00018cff0?}, 0xd?, {0xb2bec0?, 0xc00026f8b0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000350b60, {0xd847f0, 0xc00018cff0}, 0xc00029a8f0, 0xc000293980, {0xb2bec0, 0xc00026f8b0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002991b8, {0xd847f0?, 0xc00018ced0?}, 0xc0004cc960)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002ec320, {0xd847f0?, 0xc00018c3c0?}, 0xc0000e0310)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc29f00?, 0xc0002ec320}, {0xd847f0, 0xc00018c3c0}, 0xc0000e02a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000370000, {0xd87268, 0xc000373d40}, 0xc00022b680, 0xc00036af90, 0x1212d00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc000370000, {0xd87268, 0xc000373d40}, 0xc00022b680, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-proxmox_v2.9.11 plugin crashed!

**Comment by Tinyblargon** [comment]
@PSClearn01 2.x is currently broken. Please use 3.0.1rc6. We can't backport due to breaking changes. During the development of 3.0.1, numerous more panics were discovered that required breaking changes. Hence, the rc6.
