### ISSUE TITLE
Proxmox Virtual Environment 8.3.2 provider 2.9.14 panic: interface conversion: interface {} is string, not float64

### ISSUE THREAD

**Issue by DiprMaor** [Telmate/terraform-provider-proxmox#1212]
Proxmox Virtual Environment 8.3.2 provider 2.9.14 panic: interface conversion: interface {} is string, not float64
When creating from a template

```bash

***

2024-12-23T14:55:13.053+0300 [DEBUG] plugin.terraform-provider-proxmox_v2.9.14: panic: interface conversion: interface {} is string, not float64

***

2024-12-23T14:55:13.053+0300 [DEBUG] plugin.terraform-provider-proxmox_v2.9.14: 
2024-12-23T14:55:13.053+0300 [DEBUG] plugin.terraform-provider-proxmox_v2.9.14: goroutine 92 [running]:
2024-12-23T14:55:13.053+0300 [DEBUG] plugin.terraform-provider-proxmox_v2.9.14: github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0004dc718, 0xc9d509?)
2024-12-23T14:55:13.053+0300 [DEBUG] plugin.terraform-provider-proxmox_v2.9.14:         github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
2024-12-23T14:55:13.053+0300 [DEBUG] plugin.terraform-provider-proxmox_v2.9.14: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000625280, {0xb66f60?, 0xc00050a000})

```
I tried to find the reason
file `resource_pool.go` function `pxapi.NewConfigQemuFromApi`

```go
// HERE
log.Printf("[INFO][resourceVmQemuCreate] vmr2 MY MESSAGE TEST %v", vmr)
config_post_clone, err := pxapi.NewConfigQemuFromApi(vmr, client)
if err != nil {
		return err
}
log.Print("[INFO][resourceVmQemuCreate] d.Get 2 MY MESSAGE TEST")
```

And a place inside it `pxapi.NewConfigQemuFromApi`. 
File `config_qemu.go`

```go
if _, isSet := vmConfig["memory"]; isSet {
  log.Print("[INFO][NewConfigQemuFromApi] 10 ---if--- MY MESSAGE TEST")
  // HERE
  //memory = vmConfig["memory"].(float64)
  memory = 8192
}
```
Tried different versions of terraforms.
Tried to recreate the template.

**Comment by Yfksw65** [comment]
Same problem for me, any fix please ?

**Comment by alexgleason** [comment]
I am also hitting this problem, or at least hitting the same error message. Full output:

```
➜  warpzone git:(main) ✗ tofu apply
var.pm_password
  Enter a value: 

proxmox_lxc.boss: Refreshing state... [id=jupiter/lxc/100]

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # proxmox_vm_qemu.boss2 will be created
  + resource "proxmox_vm_qemu" "boss2" {
      + additional_wait           = 5
      + automatic_reboot          = true
      + balloon                   = 0
      + bios                      = "seabios"
      + boot                      = (known after apply)
      + bootdisk                  = (known after apply)
      + clone_wait                = 10
      + cores                     = 2
      + cpu                       = "host"
      + default_ipv4_address      = (known after apply)
      + define_connection_info    = true
      + force_create              = false
      + full_clone                = true
      + guest_agent_ready_timeout = 100
      + hotplug                   = "network,disk,usb"
      + id                        = (known after apply)
      + iso                       = "local:iso/ubuntu-24.04.1-live-server-amd64.iso"
      + kvm                       = true
      + memory                    = 2048
      + name                      = "boss2"
      + nameserver                = (known after apply)
      + onboot                    = false
      + oncreate                  = true
      + preprovision              = true
      + reboot_required           = (known after apply)
      + scsihw                    = "lsi"
      + searchdomain              = (known after apply)
      + sockets                   = 1
      + ssh_host                  = (known after apply)
      + ssh_port                  = (known after apply)
      + tablet                    = true
      + target_node               = "jupiter"
      + unused_disk               = (known after apply)
      + vcpus                     = 0
      + vlan                      = -1
      + vmid                      = (known after apply)

      + disk {
          + backup             = true
          + cache              = "none"
          + file               = (known after apply)
          + format             = (known after apply)
          + iops               = 0
          + iops_max           = 0
          + iops_max_length    = 0
          + iops_rd            = 0
          + iops_rd_max        = 0
          + iops_rd_max_length = 0
          + iops_wr            = 0
          + iops_wr_max        = 0
          + iops_wr_max_length = 0
          + iothread           = 0
          + mbps               = 0
          + mbps_rd            = 0
          + mbps_rd_max        = 0
          + mbps_wr            = 0
          + mbps_wr_max        = 0
          + media              = (known after apply)
          + replicate          = 0
          + size               = "8G"
          + slot               = (known after apply)
          + ssd                = 0
          + storage            = "local-lvm"
          + storage_type       = (known after apply)
          + type               = "scsi"
          + volume             = (known after apply)
        }

      + network {
          + bridge    = "vmbr0"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_vm_qemu.boss2: Creating...
proxmox_vm_qemu.boss2: Still creating... [10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.boss2,
│   on main.tf line 42, in resource "proxmox_vm_qemu" "boss2":
│   42: resource "proxmox_vm_qemu" "boss2" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 27 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0004f1e00, 0xc0004f1e00?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc0002fca00, {0xb66f60?, 0xc0001b2ff0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(...)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0002fca00, {0xb66f60?, 0xc0001b2ff0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1104 +0x292f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc0003efcb0?}, 0xd?, {0xb66f60?, 0xc0001b2ff0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00034e7e0, {0xdd7840, 0xc0003efcb0}, 0xc0001c01a0, 0xc0002fc500, {0xb66f60, 0xc0001b2ff0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003d8ba0, {0xdd7840?, 0xc0003efb90?}, 0xc0004b02d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001303c0, {0xdd7840?, 0xc0003ef050?}, 0xc0001480e0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc0001303c0}, {0xdd7840, 0xc0003ef050}, 0xc000148070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f4000, {0xddb420, 0xc00050a1a0}, 0xc0004b4000, 0xc0003eee40, 0x128f7a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0003f4000, {0xddb420, 0xc00050a1a0}, 0xc0004b4000, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by ksparwald** [comment]
Hi there,

Unfortunately the 2.x provider version is broken.
Please try the 3.0.1-rc6 version.
Also check the documentation because the schema has changed!

**Comment by Yfksw65** [comment]
Everything is fine in 3.0.1-rc6 thank you 👍
