### ISSUE TITLE
cicustom Terraform crash

### ISSUE THREAD

**Issue by goffinf** [Telmate/terraform-provider-proxmox#186]
When I run terraform apply with the cicustom property set to a cloud-config snippet, Terraform crashes.

If I remove the cicustom property the VM provisions successfully (but obviously doesn't then run the custom colod-config):

`cicustom          = "user=local:snippets/user-data-template.yaml"`

I am relatively inexperienced with proxmox, so its possible that I am doing this incorrectly. I do though, have a good knowledge of Terraform and cloud user-data configuration.

Grateful for all help.

Regards

Fraser.

**Proxmox version:**
```
pveversion --verbose
proxmox-ve: 6.2-1 (running kernel: 5.4.44-1-pve)
pve-manager: 6.2-6 (running version: 6.2-6/ee1d7754)
pve-kernel-5.4: 6.2-3
pve-kernel-helper: 6.2-3
pve-kernel-5.4.44-1-pve: 5.4.44-1
pve-kernel-5.4.34-1-pve: 5.4.34-2
...
```
**Terraform version:**
```
terraform version
Terraform v0.12.28
+ provider.proxmox (unversioned)
```
**terrafrom-provider-proxmox version:**  Compiled from latest source per the instructions in this repo.

**What are you trying to do ?**
Launch a Proxmox VM with a simple cloud-init configuration

**Describe what you did**
Launched VMs using the proxmox terraform provider configured for cloud-init (os_type) but without any explicit additional configuration is **successful** (plan, validate, apply and destroy all work as expected with the provider).

However, I wanted to test using a custom configuration using a very simple snippet (just to check whether I could use write_files and runcmd). I uploaded the following snippet into the local volume for the node where I am creating VMs:

**user-data-template.yaml**
```
#cloud-config
output: {all: '| tee -a /var/log/cloud-init-output.log'}
write_files:
  - path: /usr/local/bin/hello-world.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      
      echo "Hello World" >> /usr/local/bin/greeting;
runcmd:
  - /usr/local/bin/hello-world.sh
```

I referenced the snippet in the main.tf using the cicustom property:

```
resource "proxmox_vm_qemu" "test_vm" {
...
  cicustom          = "user=local:snippets/user-data-template.yaml"
...
}
```
When I run terraform apply I get crash (full output below - I also have the full crash log - but not much more to go on):

`!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!`

These are the Terraform files I am using (also attached):

**main.tf:**
```
provider "proxmox" {
    pm_api_url = "https://${var.proxmox_server_ip}:${var.proxmox_server_port}/api2/json"
    pm_user = var.proxmox_server_user
    pm_password = var.proxmox_server_pwd
    pm_tls_insecure = var.proxmox_insecure_mode
}

resource "proxmox_vm_qemu" "test_vm" {
  count             = var.proxmox_node_count
  name              = "test-vm-${count.index}"
  target_node       = var.proxmox_target_node

#  agent             = 1
  clone             = var.proxmox_template
  full_clone        = var.full_clone

  os_type           = var.proxmox_os_type
  cores             = var.cores
  sockets           = var.sockets
  cpu               = "host"
  memory            = var.memory
  scsihw            = "virtio-scsi-pci"
  bootdisk          = "scsi0"
  cicustom          = "user=local:snippets/user-data-template.yaml"

  disk {
    id              = var.disk_info["id"]
    size            = var.disk_info["size"]
    type            = var.disk_info["type"]
    storage         = var.disk_info["storage"]
    storage_type    = var.disk_info["storage_type"]
    iothread        = var.disk_info["iothread"]
  }

  network {
    id              = 0
    model           = "virtio"
    bridge          = "vmbr0"
  }

  lifecycle {
    ignore_changes  = [
      network,
    ]
  }

  # Cloud Init Settings
#  ipconfig0         = "dhcp"
#  ipconfig0         = "ip=192.168.2.11${count.index + 1}/24,gw=192.168.2.1"
#
#  sshkeys = <<EOF
#  ${var.ssh_key}
#  EOF

#  provisioner "remote-exec" {
#    inline = [
#      "ip a"
#    ]
#  }
}
```
**user-data-template.yaml**
```
#cloud-config
output: {all: '| tee -a /var/log/cloud-init-output.log'}
write_files:
  - path: /usr/local/bin/hello-world.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      
      echo "Hello World" >> /usr/local/bin/greeting;
runcmd:
  - /usr/local/bin/hello-world.sh
```

**terraform.tfvars**
```
proxmox_server_ip = "proxmox-002"
proxmox_server_port = 8006
proxmox_server_user = "root@pam"
proxmox_server_pwd = "xxxxxxxxxxxxx"
proxmox_insecure_mode = true
proxmox_target_node = "home"
proxmox_node_count = 1
#proxmox_template = "ubuntu-2002-base-cloudinit-template"
proxmox_template = "cloud-init-test-drive-template"
proxmox_os_type = "cloud-init"
cores = 2
full_clone = false
sockets = 1
memory = 2048
disk_info = {
    id = "0"
    size = "16"
    type = ""
    storage = "local-lvm"
    storage_type = "lvmthin"
    iothread = "true"
}
```

**Full Terraform output:**

```
terraform apply

proxmox_vm_qemu.test_vm[0]: Modifying... [id=home/qemu/110]
proxmox_vm_qemu.test_vm[0]: Still modifying... [id=home/qemu/110, 10s elapsed]
proxmox_vm_qemu.test_vm[0]: Still modifying... [id=home/qemu/110, 20s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [1] with length 0
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: goroutine 22 [running]:
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.initConnInfo(0xc000162fc0, 0xc00009e960, 0xc00007b770, 0xc0000d93d0, 0xc0000d9418, 0x0, 0x0)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/proxmox/terraform/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1107 +0x1087
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuUpdate(0xc000162fc0, 0xf09ba0, 0xc00009e960, 0x24, 0x1c18820)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/proxmox/terraform/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:781 +0x139f
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00014cf00, 0xc000522140, 0xc0005485e0, 0xf09ba0, 0xc00009e960, 0xfaf801, 0xc000359f08, 0xc000659350)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/resource.go:311 +0x263
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00014d180, 0xc0000d98a8, 0xc000522140, 0xc0005485e0, 0xc000011e98, 0xc0000a2001, 0xfb1ba0)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/provider.go:289 +0x99
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000eaa8, 0x1392a20, 0xc0003c4000, 0xc00009c3c0, 0xc00000eaa8, 0x0, 0xc0003b8a20)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/plugin/grpc_provider.go:885 +0x892
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10d9b00, 0xc00000eaa8, 0x1392a20, 0xc0003c4000, 0xc000202000, 0x0, 0x1392a20, 0xc0003c4000, 0xc0003be000, 0xada)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001b00, 0x139e3a0, 0xc000082d80, 0xc00053c000, 0xc0001dbf50, 0x1bc79c0, 0x0, 0x0, 0x0)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).handleStream(0xc000001b00, 0x139e3a0, 0xc000082d80, 0xc00053c000, 0x0)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xd3d
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00038c190, 0xc000001b00, 0x139e3a0, 0xc000082d80, 0xc00053c000)
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0xa1
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-07-03T14:31:16.622+0100 [DEBUG] plugin.terraform-provider-proxmox:         /home/goffinf/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
2020-07-03T14:31:16.623+0100 [DEBUG] plugin: plugin process exited: path=/home/goffinf/.terraform.d/plugins/terraform-provider-proxmox pid=4931 error="exit status 2"
2020/07/03 14:31:16 [DEBUG] proxmox_vm_qemu.test_vm[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/07/03 14:31:16 [TRACE] EvalWriteState: recording 0 dependencies for proxmox_vm_qemu.test_vm[0]
2020/07/03 14:31:16 [TRACE] EvalWriteState: writing current state object for proxmox_vm_qemu.test_vm[0]
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/07/03 14:31:16 [TRACE] EvalApplyProvisioners: proxmox_vm_qemu.test_vm[0] is not freshly-created, so no provisioning is required
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/07/03 14:31:16 [TRACE] EvalWriteState: recording 0 dependencies for proxmox_vm_qemu.test_vm[0]
2020/07/03 14:31:16 [TRACE] EvalWriteState: writing current state object for proxmox_vm_qemu.test_vm[0]
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalIf
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalIf
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/07/03 14:31:16 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/07/03 14:31:16 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/07/03 14:31:16 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/07/03 14:31:16 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.test_vm[0]
2020/07/03 14:31:16 [TRACE] vertex "proxmox_vm_qemu.test_vm[0]": visit complete
2020/07/03 14:31:16 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/07/03 14:31:16 [TRACE] dag/walk: upstream of "provider.proxmox (close)" errored, so skipping
2020/07/03 14:31:16 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/07/03 14:31:16 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2020/07/03 14:31:16 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 4
2020/07/03 14:31:16 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/07/03 14:31:16 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/07/03 14:31:16 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-07-03T14:31:16.702+0100 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Attached Files:

[terraform.zip](https://github.com/Telmate/terraform-provider-proxmox/files/4870146/terraform.zip)

**Comment by goffinf** [comment]
I have since got cloud-init to work as expected without a Terraform crash, but it is still reproducible so I’m going to leave this ticket open for now since it either identifies a bug or a misconfiguration of the provider/resource which would likely be a good thing to document so that others don’t hit the same problem.

Happy to help with further testing of which combination of properties/values cause a crash and provide doc updates if you want ?

Regards

Fraser.

**Comment by aaronstuder** [comment]
I am having the same issue

**Comment by goffinf** [comment]
Hey @aaronstuder, per my comment above, I do have Terraform provisioning a Proxmox VM including running cloud-init without crashing. It does appear that there are some properties that can still cause this though which hopefully will get looked at at some point. If you want to post your .tf files here and your user-data template (snippet) I would be happy to take a look at them ?

**Comment by fabri2000779** [comment]
We are getting the same issue, i tho that was something in my terraform script but i see now it isnt

**Comment by soakes** [comment]
I found that this can be dupicated.  If you remove `ipconfig0 = "ip=${var.vm_ip}/24,gw=${var.vm_gw}"` line, as say custom cloud-init will do it instead, it will crash.

The error is quite intresting...

```
proxmox_vm_qemu.vgw01[0]: Modifying... [id=pve01/qemu/271254]
proxmox_vm_qemu.vgw01[0]: Still modifying... [id=pve01/qemu/271254, 10s elapsed]
proxmox_vm_qemu.vgw01[0]: Still modifying... [id=pve01/qemu/271254, 20s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing
```

If you make sure the line is added i.e set with `ipconfig0` then the crash and error doesn't happen.

Might be an idea to make the error a bit more `friendly`.

**Comment by dkoerner85** [comment]
I have experienced this error as well today, though it is hard to compare stack traces since there are no repository tags. I have attached the full stack trace at the bottom.

I am using a custom Cloud-Init snippet to configure the network. The .tf file contains a line like

```
cicustom = "user=snippets:snippets/user-hello-network.yml,network=snippets:snippets/network-hello-network.yml"
```

and the `network-hello-network.yml` looks like

```
version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        address: 10.10.1.130/24
        gateway: 10.10.1.1
        dns_nameservers:
          - 10.10.1.1
        dns_search:
          - example.com
```

Thus I do not need an `ipconfig0` line to specify network info. Indeed, `terraform validate` reports that the configuration is valid. However, the proxmox provider will try to extract the ip address in an unsafe manner from `ipconfig0` in line 1132 of `resource_vm_qemu.go`, which fails since this variable is empty.

A workaroung is to add the following line to the .tf file:

```
ipconfig0 = "ip=dhcp"
```

I would prefer that the proxmox provider would treat an empty `ipconfig0` in the same way as for dhcp (query the qemu guest agent for the ip address) since in fact my network configuration is not dynamic, but static.


Stack trace:

```
panic: runtime error: index out of range [1] with length 0
2020-08-26T16:24:27.183+0200 [DEBUG] plugin.terraform-provider-proxmox: 
2020-08-26T16:24:27.183+0200 [DEBUG] plugin.terraform-provider-proxmox: goroutine 40 [running]:
2020-08-26T16:24:27.183+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.initConnInfo(0xc000122630, 0xc0003f42a0, 0xc000382370, 0xc0003c5528, 0xc0003c5570, 0x2, 0x0)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1132 +0x1105
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000122630, 0x18af880, 0xc0003f42a0, 0x2, 0x2145d00)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:687 +0x1745
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00012a200, 0xc000286700, 0xc0003f1ce0, 0x18af880, 0xc0003f42a0, 0x1, 0x0, 0x0)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:308 +0x3b8
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00012a480, 0xc0003c5a00, 0xc000286700, 0xc0003f1ce0, 0xc0000b8540, 0x1b46f00, 0xc0000b8540)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:297 +0x99
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000010030, 0x1b46280, 0xc0001f69c0, 0xc000286540, 0xc000010030, 0xc0001f69c0, 0xc000071b78)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:923 +0x905
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x19f00c0, 0xc000010030, 0x1b46280, 0xc0001f69c0, 0xc0000ba840, 0x0, 0x1b46280, 0xc0001f69c0, 0xc0005edb00, 0x8a1)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3303 +0x214
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000582300, 0x1b4e280, 0xc000583080, 0xc000312300, 0xc0003026f0, 0x20efde0, 0x0, 0x0, 0x0)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:1024 +0x522
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000582300, 0x1b4e280, 0xc000583080, 0xc000312300, 0x0)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:1313 +0xd34
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000038250, 0xc000582300, 0x1b4e280, 0xc000583080, 0xc000312300)
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:722 +0xa5
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: created by github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-26T16:24:27.184+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/Users/dkoerner/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:720 +0xa5
2020-08-26T16:24:27.187+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-08-26T16:24:27.188+0200 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/terraform.hsd.heine.com/telmate/proxmox/0.1.0/darwin_amd64/terraform-provider-proxmox pid=78892 error="exit status 2"
2020/08/26 16:24:27 [DEBUG] proxmox_vm_qemu.hellonetwork: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalMaybeTainted
2020/08/26 16:24:27 [TRACE] EvalMaybeTainted: proxmox_vm_qemu.hellonetwork encountered an error during creation, so it is now marked as tainted
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalWriteState
2020/08/26 16:24:27 [TRACE] EvalWriteState: removing state object for proxmox_vm_qemu.hellonetwork
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/08/26 16:24:27 [TRACE] EvalApplyProvisioners: proxmox_vm_qemu.hellonetwork has no state, so skipping provisioners
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalMaybeTainted
2020/08/26 16:24:27 [TRACE] EvalMaybeTainted: proxmox_vm_qemu.hellonetwork encountered an error during creation, so it is now marked as tainted
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalWriteState
2020/08/26 16:24:27 [TRACE] EvalWriteState: removing state object for proxmox_vm_qemu.hellonetwork
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalIf
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalIf
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalWriteDiff
2020/08/26 16:24:27 [TRACE] eval: *terraform.EvalApplyPost
2020/08/26 16:24:27 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/08/26 16:24:27 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/26 16:24:27 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.hellonetwork
2020/08/26 16:24:27 [TRACE] vertex "proxmox_vm_qemu.hellonetwork": visit complete
2020/08/26 16:24:27 [TRACE] dag/walk: upstream of "provider[\"terraform.hsd.heine.com/telmate/proxmox\"] (close)" errored, so skipping
2020/08/26 16:24:27 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/08/26 16:24:27 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: reading latest snapshot from terraform.tfstate
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: read nil snapshot
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: no original state snapshot to back up
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 1
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/08/26 16:24:27 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-08-26T16:24:27.203+0200 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
