### ISSUE TITLE
Terraform Refresh causing Panic

### ISSUE THREAD

**Issue by eddingston** [Telmate/terraform-provider-proxmox#203]
Using `terraform plan` on a previously successful terraform script now gives `panic: interface conversion: interface {} is int, not string`. It seems to panic when refreshing the terraform state. 

All ideas and suggests are greatly appreciated. Thank you.

Here is the panic part of the crash log:
```
2020-08-04T06:23:54.556-0700 [DEBUG] plugin.terraform-provider-proxmox: {"data":{"cpu":"host","ostype":"l26","smbios1":"uuid=0a0a9f07-1000-4cdb-aec4-2723740319d7","sockets":1,"hotplug":"network,disk,usb","bios":"seabios","scsi0":"sprox1-ssd-raid:vm-104-disk-0,format=raw,iothread=1,media=disk,size=32","scsi2":"sprox1-ssd-raid:vm-104-disk-2,format=raw,iothread=1,media=disk,size=153604M","onboot":1,"vmgenid":"48794bf1-cc73-4f23-888e-3bcb1521ccd4","digest":"9c1aa1ded4cc6d33dc83276db33155cd1fb3b42d","ide3":"sprox1-ssd-raid:vm-104-cloudinit,media=cdrom,size=4M","boot":"cdn","cores":2,"agent":"0","numa":0,"scsi1":"sprox1-ssd-raid:vm-104-disk-1,format=raw,iothread=1,media=disk,size=51204M","memory":3815,"scsihw":"virtio-scsi-pci","ipconfig0":"ip=10.60.44.53/24,gw=10.60.44.1","net0":"virtio=2E:FC:AF:DB:37:2D,bridge=vmbr0","name":"net-1","bootdisk":"scsi0","ide2":"none,media=cdrom"}}
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: panic: interface conversion: interface {} is int, not string
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: goroutine 97 [running]:
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.SerializeValueForHash(0xc000609518, 0xf419c0, 0xc00073d2c8, 0xc00052ee00)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/serialize.go:28 +0x917
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.SerializeResourceForHash(0xc000609518, 0xfb1ba0, 0xc0004d74a0, 0xc000510180)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/serialize.go:110 +0x319
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.HashResource.func1(0xfb1ba0, 0xc0004d74a0, 0xc0005a3320)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:32 +0x68
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Set).hash(0xc0006681a0, 0xfb1ba0, 0xc0004d74a0, 0xa, 0xc0005a33b8)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:221 +0x3d
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc0006681a0, 0xfb1ba0, 0xc0004d74a0, 0x0, 0xc0001f0bc8, 0xa)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:198 +0x83
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Set).Add(...)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:75
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.UpdateDevicesSet(0xc0006681a0, 0xc00020c030, 0x4)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/Workstation/garage/terraform/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1015 +0xbb
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0xc00010e620, 0xf09ba0, 0xc000483170, 0xc00010e620, 0x0)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/Workstation/garage/terraform/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:848 +0xd12
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000510280, 0xc0004507d0, 0xf09ba0, 0xc000483170, 0xc000508ad8, 0x0, 0x0)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/resource.go:455 +0x119
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000508030, 0x1392a20, 0xc0008ca1b0, 0xc0008d00f0, 0xc000508030, 0x0, 0xc0001d9a20)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/plugin/grpc_provider.go:525 +0x3d8
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x10d9b00, 0xc000508030, 0x1392a20, 0xc0008ca1b0, 0xc0008d00a0, 0x0, 0x1392a20, 0xc0008ca1b0, 0xc0008e0480, 0x46b)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000702600, 0x139e3a0, 0xc000703080, 0xc0008d8000, 0xc0003875c0, 0x1bc7990, 0x0, 0x0, 0x0)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).handleStream(0xc000702600, 0x139e3a0, 0xc000703080, 0xc0008d8000, 0x0)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xd3d
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000343b0, 0xc000702600, 0x139e3a0, 0xc000703080, 0xc0008d8000)
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0xa1
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-04T06:23:54.560-0700 [DEBUG] plugin.terraform-provider-proxmox: 	/home/tree/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
2020-08-04T06:23:54.561-0700 [DEBUG] plugin: plugin process exited: path=/home/tree/.terraform.d/plugins/terraform-provider-proxmox pid=9582 error="exit status 2"
2020/08/04 06:23:54 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Canceled desc = context canceled
2020/08/04 06:23:54 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2020/08/04 06:23:54 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/04 06:23:54 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.SPROX1-VM-NET-1[0]
2020/08/04 06:23:54 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/04 06:23:54 [TRACE] vertex "proxmox_vm_qemu.SPROX1-VM-NET-1[0]": visit complete
```

**Comment by mgebundy** [comment]
I'm hitting this exact same issue. I have a very simple qemu vm resource that was applied successfully, but even without any changes to the config, any consecutive `plan` or `apply` throws that error.

Here's my resource:
```tf
resource "proxmox_vm_qemu" "rancheros" {
    name = "rancheros"
    target_node = "home"

    os_type = "ubuntu"
    iso = "local:iso/rancheros.iso"
    memory = "1024"

    disk {
        id = 0
        size = 10
        type = "scsi"
        storage = "local-lvm"
        storage_type = "lvm"
    }

    network {
        id = 0
        model = "virtio"
        bridge = "vmbr0"
        firewall = true
    }
}
```

Full crash log:
[crash.log](https://github.com/Telmate/terraform-provider-proxmox/files/5252745/crash.log)

Of interest:

```
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 2020/09/20 17:42:36 >>>>>>>>>> REQUEST:
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: GET /api2/json/nodes/home/qemu/100/config HTTP/1.1
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Host: 192.168.0.138:8006
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: User-Agent: Go-http-client/1.1
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Accept: application/json
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Cookie: PVEAuthCookie=PVE:terraform-prov@pve:5F67CCCE::0WN/fI7gxnZew/Bs0+N5SWh+52HdlHvFQ0KUvY9mZEQ8t/X5jXiZw4wpVJyPkpFeULkHEde7aQnow6zKh2xs84xA5vD+T0VH5mDdGut+DhSNeJhawGX1r46U0RD7mSBs+K3g16bsCWiuNSjvmHtF/ynPDQ//WZ5puoUfk9/FJjBUdnhZOnQsNOOPWzMnB9S8mj1xgvuWIqFgQE8wLB/u7i/5/qZx98Qo+jnStlvoxsbaIbzZj2EyEit2IqUBCxfjTDHVBtpt37Cx+Ld0n/hr6JqE8rKWmG2tKT8073eQHFu3h0kdwOyRP3+67luwzkcU6/0vC713WjpyF4BCURTlDA==
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Csrfpreventiontoken: 5F67CCCE:mUA9SDAVC2XL1FGLOiKL79FqNT75MSCabgBsYmNfgoM
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Accept-Encoding: gzip
2020-09-20T17:42:36.967-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 2020/09/20 17:42:36 <<<<<<<<<< RESULT:
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: HTTP/1.1 200 OK
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Content-Length: 533
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Cache-Control: max-age=0
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Connection: Keep-Alive
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Content-Type: application/json;charset=UTF-8
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Date: Sun, 20 Sep 2020 21:42:38 GMT
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Expires: Sun, 20 Sep 2020 21:42:38 GMT
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Pragma: no-cache
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: Server: pve-api-daemon/3.0
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 
2020-09-20T17:42:36.987-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: {"data":{"ostype":"l26","bios":"seabios","boot":"cdn","digest":"3233333b7f4d58fd98d7173c57339bfb4518a004","onboot":1,"sockets":1,"kvm":1,"name":"rancheros","ide2":"local:iso/rancheros.iso,media=cdrom","hotplug":"network,disk,usb","vmgenid":"cce88f7d-7da5-4cb9-87e7-a95c38f356f5","agent":"0","scsi0":"local-lvm:vm-100-disk-0,format=raw,media=disk,size=10","numa":0,"bootdisk":"scsi0","memory":1024,"cpu":"host","smbios1":"uuid=27ff7940-4d5d-4324-a56a-8df1fe0b103b","cores":1,"net0":"virtio=2A:89:87:7B:5E:86,bridge=vmbr0,firewall=1"}}
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: panic: interface conversion: interface {} is int, not string
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: goroutine 54 [running]:
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.SerializeValueForHash(0xc000337688, 0x122bcc0, 0x19312f0, 0xc000275300)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/serialize.go:28 +0x925
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.SerializeResourceForHash(0xc000337688, 0x126a820, 0xc0005031a0, 0xc000168c80)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/serialize.go:110 +0x326
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.HashResource.func1(0x126a820, 0xc0005031a0, 0xc000631320)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/set.go:32 +0x6f
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.(*Set).hash(0xc000304440, 0x126a820, 0xc0005031a0, 0xa, 0xc0006313a8)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/set.go:221 +0x44
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc000304440, 0x126a820, 0xc0005031a0, 0x0, 0xc000132f28, 0xa)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/set.go:198 +0x8b
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.(*Set).Add(...)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/set.go:75
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/Telmate/terraform-provider-proxmox/proxmox.UpdateDevicesSet(0xc000304440, 0xc000502e40, 0x4)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1051 +0xc5
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0xc00013aa20, 0x1201e20, 0xc0005b2240, 0xc00013aa20, 0x0)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:884 +0xd85
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000168d80, 0xc0002542a0, 0x1201e20, 0xc0005b2240, 0xc00006d510, 0x1485d20, 0xc00006d510)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:466 +0x15f
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000006b48, 0x1485120, 0xc000416480, 0xc000300300, 0xc000006b48, 0xc000416480, 0xc0002ffb78)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:543 +0x425
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x1335fc0, 0xc000006b48, 0x1485120, 0xc000416480, 0xc0003002a0, 0x0, 0x1485120, 0xc000416480, 0xc000151000, 0x397)
2020-09-20T17:42:36.990-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3267 +0x214
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000284300, 0x148d6e0, 0xc000314c00, 0xc00036a100, 0xc000588510, 0x1a09170, 0x0, 0x0, 0x0)
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:1024 +0x522
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000284300, 0x148d6e0, 0xc000314c00, 0xc00036a100, 0x0)
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:1313 +0xd54
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00023e3a0, 0xc000284300, 0x148d6e0, 0xc000314c00, 0xc00036a100)
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:722 +0xa8
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: created by github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-09-20T17:42:36.991-0400 [DEBUG] plugin.terraform-provider-proxmox.exe: 	C:/Users/mitch/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:720 +0xa8
```

**Comment by mgebundy** [comment]
I switched the "size" attribute of "disk" to a string, and it works now.

@eddingston try setting a size of "32G" rather than 32

**Comment by eddingston** [comment]
Thank you for your suggestion @mgebundy. Unfortunately that did not fix it for me.
