### ISSUE TITLE
Unable to create secondary disk

### ISSUE THREAD

**Issue by kevinsulatra** [Telmate/terraform-provider-proxmox#204]
The error occurs when creating a VM with more than 1 disk with the latest versions of plugins.
```
MSG:
Failed due to error(s) thrown while running terraform plan:
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
panic: interface conversion: interface {} is int, not string
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: 
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: goroutine 68 [running]:
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.SerializeValueForHash(0xc000563518, 0xf429e0, 0xc00081ca90, 0xc0004af100)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/serialize.go:28 +0x917
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.SerializeResourceForHash(0xc000563518, 0xfb2c20, 0xc00050eba0, 0xc00014ee00)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/serialize.go:110 +0x319
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.HashResource.func1(0xfb2c20, 0xc00050eba0, 0xc0003b5560)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:32 +0x68
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Set).hash(0xc0004cdf40, 0xfb2c20, 0xc00050eba0, 0x0, 0x90)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:221 +0x3d
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc0004cdf40, 0xfb2c20, 0xc00050eba0, 0x0, 0xc0000143d8, 0xa)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:198 +0x83
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Set).Add(...)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/set.go:75
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.UpdateDevicesSet(0xc0004cdf40, 0xc000097bf0, 0x4)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1040 +0xbb
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0xc0001647e0, 0xf0abc0, 0xc000097f50, 0xc0001647e0, 0x0)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:873 +0xd5f
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00014ef00, 0xc0005a65a0, 0xf0abc0, 0xc000097f50, 0xc00031eb78, 0x0, 0x0)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/schema/resource.go:455 +0x119
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000ea98, 0x1393d80, 0xc00041cf30, 0xc0005a64b0, 0xc00000ea98, 0xc00041cf30, 0xc000626a20)
2020-08-05T12:15:48.000+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/helper/plugin/grpc_provider.go:525 +0x3d8
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0x10dab80, 0xc00000ea98, 0x1393d80, 0xc00041cf30, 0xc0005a6000, 0x0, 0x1393d80, 0xc00041cf30, 0xc000946580, 0x51f)
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/github.com/hashicorp/terraform@v0.12.10/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001e00, 0x139f700, 0xc000082d80, 0xc00064ce00, 0xc0003dc0f0, 0x1bc8990, 0x0, 0x0, 0x0)
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).handleStream(0xc000001e00, 0x139f700, 0xc000082d80, 0xc00064ce00, 0x0)
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xd3d
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000364d0, 0xc000001e00, 0x139f700, 0xc000082d80, 0xc00064ce00)
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0xa1
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-05T12:15:48.001+0100 [DEBUG] plugin.terraform-provider-proxmox:     /home/kev/go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.longhorn-ubuntu[2]
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.longhorn-ubuntu[2]": visit complete
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.longhorn-ubuntu[1]
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.longhorn-ubuntu[1]": visit complete
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.longhorn-ubuntu[0]
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.longhorn-ubuntu[0]": visit complete
2020/08/05 12:15:48 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.longhorn-ubuntu": dynamic subgraph encountered errors
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.longhorn-ubuntu": visit complete
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.rancher-ubuntu[0]
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.rancher-ubuntu[0]": visit complete
2020/08/05 12:15:48 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.rancher-ubuntu[1]
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.rancher-ubuntu[1]": visit complete
2020/08/05 12:15:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/08/05 12:15:48 [TRACE] [walkRefresh] Exiting eval tree: proxmox_vm_qemu.rancher-ubuntu[2]
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.rancher-ubuntu[2]": visit complete
2020/08/05 12:15:48 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-08-05T12:15:48.003+0100 [DEBUG] plugin: plugin process exited: path=/home/kev/.terraform.d/plugins/terraform-provider-proxmox pid=31344 error="exit status 2"
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.rancher-ubuntu": dynamic subgraph encountered errors
2020/08/05 12:15:48 [TRACE] vertex "proxmox_vm_qemu.rancher-ubuntu": visit complete
2020/08/05 12:15:48 [TRACE] dag/walk: upstream of "provider.proxmox (close)" errored, so skipping
2020/08/05 12:15:48 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-08-05T12:15:48.185+0100 [DEBUG] plugin: plugin exited
```

Our terraform file to create the VMs:
```
resource "proxmox_vm_qemu" "longhorn-ubuntu" {
  depends_on = [
    null_resource.cloud_init_config_files_longhorn-ubuntu,
  ]

  count = 3

  agent = 1 # Enable the qemu guest agent

  name = "longhorn-ubuntu-${count.index}-dev-kevin"
  desc = "Longhorn cluster node on Ubuntu"
  target_node = "x10drl-1-proxmox"

  clone = "ubuntu-2004-cloudinit-template"

  scsihw            = "virtio-scsi-pci"
  bootdisk          = "scsi0"

  # The destination resource pool for the new VM
  pool = "longhorn-ubuntu-dev-kevin"

  disk {
    id = 0
    size = 20
    storage = "local-lvm"
    storage_type = "lvmthin"
    type = "scsi"
  }

  disk {
    id = 1
    size = 20
    storage = "local-lvm"
    storage_type = "lvmthin"
    type = "scsi"
  }


  cores   = 2
  sockets = 1
  memory  = 8192

  network {
    id = 0
    bridge = "vmbr0"
    model = "virtio"
  }

  onboot = false

  ssh_user = "ubuntu"

  os_type = "cloud-init"
  ipconfig0 = "ip=dhcp,ip6=dhcp"

  /*
    sshkeys and other User-Data parameters are specified with a custom config file.
    In this example each VM has its own config file, previously generated and uploaded to
    the snippets folder in the local storage in the Proxmox VE server.
  */
  cicustom = "user=local:snippets/user_data_longhorn-ubuntu-${count.index}-dev-kevin.yml"
  ciuser = "ubuntu"

  lifecycle {
    ignore_changes  = [
      network,
    ]
  }
}
```

**Comment by drewhemm** [comment]
If it's any help, the plugins I built when I cloned this repo on the 22nd of June work fine, so it is something that has gone in since then.

**Comment by drewhemm** [comment]
And this is the error visible in the Proxmox UI:

```
TASK ERROR: can't get size of '/dev/local-lvm/vm-104-disk-1':   Failed to find logical volume "local-lvm/vm-104-disk-1"
```

**Comment by shadowlord017** [comment]
I have similar problem. I'm trying to clone template with 1 disk and create second:
    disk {
        id              = 0
        size            = 8
        type            = "scsi"
        storage         = "zfs-hba"
        storage_type    = "zfspool"
        iothread        = true
    }
    disk {
        id              = 1
        size            = 120
        type            = "scsi"
        storage         = "zfs-hba"
        storage_type    = "zfspool"
        iothread        = true
    }
Sometimes it works well, but other time it fails in proxmox (but terraform thinks all done well):
TASK ERROR: timeout: no zvol device link for 'vm-103-disk-1' found after 300 sec found.

As I see in debug, when it works - terraform creates second disk sooner than the first.
Problem is in this (as I think):
[DEBUG] plugin.terraform-provider-proxmox: HTTP/1.1 500 zfs error: cannot create 'zfs-pool/vm-103-disk-0': dataset already exists
Terraform tries to create disk that is created by clone function and fails - and stops creating any other disks. But if I drop first disk in config - how can I choose storage for it or resize?
