### ISSUE TITLE
Crash after successful clone

### ISSUE THREAD

**Issue by mjdall** [Telmate/terraform-provider-proxmox#24]
When cloning an existing VM, terraform will crash with the following log: 

panic: assignment to entry in nil map
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: goroutine 72 [running]:
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/proxmox-api-go/proxmox.ConfigQemu.CreateQemuDisksParams(0xc420348ad0, 0xa, 0xc420348b14, 0x9, 0x0, 0x400, 0x0, 0x0, 0x1, 0x1, ...)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/Telmate/proxmox-api-go/proxmox/config_qemu.go:582 +0xcc8
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/proxmox-api-go/proxmox.ConfigQemu.UpdateConfig(0xc420348ad0, 0xa, 0xc420348b14, 0x9, 0x0, 0x400, 0x0, 0x0, 0x1, 0x1, ...)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/Telmate/proxmox-api-go/proxmox/config_qemu.go:147 +0x3bc
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/proxmox-api-go/proxmox.ConfigQemu.CloneVm(0xc420348ad0, 0xa, 0xc420348b14, 0x9, 0x0, 0x400, 0x0, 0x0, 0x1, 0x1, ...)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/Telmate/proxmox-api-go/proxmox/config_qemu.go:134 +0x487
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc420166ee0, 0xd75620, 0xc4204fe120, 0xc420166ee0, 0x0)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:269 +0x1d9e
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420384000, 0xc42050eaf0, 0xc4203476a0, 0xd75620, 0xc4204fe120, 0xc42032cc01, 0xc42006cb88, 0x4ba3bc)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:265 +0x36c
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4200c0070, 0xc42050eaa0, 0xc42050eaf0, 0xc4203476a0, 0x18, 0x18, 0xc4203476e0)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420148e80, 0xc420347240, 0xc420508250, 0x0, 0x0)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:530 +0x57
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: reflect.Value.call(0xc42032a900, 0xc42033c038, 0x13, 0xf56b4e, 0x4, 0xc42006cf18, 0x3, 0x3, 0xc420333040, 0xc420094f00, ...)
2018-11-09T11:16:50.529+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/.gvm/gos/go1.10.5/src/reflect/value.go:447 +0x969
2018-11-09T11:16:50.530+1300 [DEBUG] plugin.terraform-provider-proxmox: reflect.Value.Call(0xc42032a900, 0xc42033c038, 0x13, 0xc4203a6f18, 0x3, 0x3, 0x429f69, 0x8, 0xc42034acc0)
2018-11-09T11:16:50.530+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/.gvm/gos/go1.10.5/src/reflect/value.go:308 +0xa4
2018-11-09T11:16:50.530+1300 [DEBUG] plugin.terraform-provider-proxmox: net/rpc.(*service).call(0xc420086440, 0xc42050e190, 0xc4203480d0, 0xc420348100, 0xc42034c000, 0xc4203464e0, 0xd762e0, 0xc420347240, 0x16, 0xd76320, ...)
2018-11-09T11:16:50.530+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/.gvm/gos/go1.10.5/src/net/rpc/server.go:384 +0x14e
2018-11-09T11:16:50.530+1300 [DEBUG] plugin.terraform-provider-proxmox: created by net/rpc.(*Server).ServeCodec
2018-11-09T11:16:50.530+1300 [DEBUG] plugin.terraform-provider-proxmox: 	/home/morgan/.gvm/gos/go1.10.5/src/net/rpc/server.go:480 +0x43a
2018-11-09T11:16:50.532+1300 [DEBUG] plugin: plugin process exited: path=/home/morgan/.terraform.d/plugins/terraform-provider-proxmox
2018/11/09 11:16:50 [TRACE] root: eval: *terraform.EvalWriteState
2018/11/09 11:16:50 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/11/09 11:16:50 [TRACE] root: eval: *terraform.EvalIf
2018/11/09 11:16:50 [TRACE] root: eval: *terraform.EvalWriteState
2018/11/09 11:16:50 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/11/09 11:16:50 [TRACE] root: eval: *terraform.EvalApplyPost
2018/11/09 11:16:50 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* proxmox_vm_qemu.rand-test: unexpected EOF
2018/11/09 11:16:50 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* proxmox_vm_qemu.rand-test: unexpected EOF
2018/11/09 11:16:50 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.rand-test
2018/11/09 11:16:50 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/11/09 11:16:50 [TRACE] dag/walk: upstream errored, not walking "provider.proxmox (close)"
2018/11/09 11:16:50 [TRACE] dag/walk: upstream errored, not walking "root"
2018/11/09 11:16:50 [TRACE] Preserving existing state lineage "f7d41fc1-c750-705a-c75a-8db944004ba7"
2018/11/09 11:16:50 [TRACE] Preserving existing state lineage "f7d41fc1-c750-705a-c75a-8db944004ba7"
2018/11/09 11:16:50 [TRACE] Preserving existing state lineage "f7d41fc1-c750-705a-c75a-8db944004ba7"
2018/11/09 11:16:50 [TRACE] Preserving existing state lineage "f7d41fc1-c750-705a-c75a-8db944004ba7"
2018/11/09 11:16:50 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-11-09T11:16:50.552+1300 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

The clone will be successful, however once cloned this crash will occur right after.

**Comment by mjdall** [comment]
Changing storage from "local" to "local-lvm" seemed to fix this.
