### ISSUE TITLE
plugin just partially works for me

### ISSUE THREAD

**Issue by csecsi** [Telmate/terraform-provider-proxmox#33]
The plan seems to be okay but when I apply only some settings are working.
It clones the template set the disk size and onboot for instance but memory, CPU and cloud-init settings are just ignored.

I cannot see any relevant error message. The only thing which strange is the following at TF_LOG=DEBUG terraform plan -out test:
2019-01-03T11:09:59.996Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/01/03 11:09:59 [ERR] plugin: plugin server: accept unix /tmp/plugin261792049: use of closed network connection
2019-01-03T11:09:59.996Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/01/03 11:09:59 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-01-03T11:09:59.996Z [DEBUG] plugin.terraform-provider-proxmox: 2019/01/03 11:09:59 [ERR] plugin: plugin server: accept unix /tmp/plugin527826518: use of closed network connection

Did anyone meet such a problem before?

main.tf:

provider "proxmox" {
  pm_tls_insecure = true
  pm_api_url      = "https://proxmox:8006/api2/json"
  pm_user         = "root@pam"
  pm_password     = "password"
}

/* Uses cloud-init options from Proxmox 5.2 */
resource "proxmox_vm_qemu" "cloudinittest" {
  name        = "test"
  desc        = "first terra vm"
  target_node = "proxmoxnode"

   clone = "Ubuntu18.04Template"

  disk {
    id           = 0
    type         = "virtio"
    storage      = "images"
    storage_type = "raw"
    size         = "20G"
    backup       = "true"
  }

  network {
    id     = 0
    model  = "virtio"
    bridge = "vmbr0"
  }

onboot  = false
cores   = 4
sockets = 2
memory  = 8192

  ssh_user = "root"

  ssh_private_key = <<EOF
-----BEGIN RSA PRIVATE KEY-----
privkey
-----END RSA PRIVATE KEY-----
  EOF

  os_type    = "cloud-init"
  ipconfig0  = "ip=192.168.0.100/24,gw=192.168.0.1"
  cipassword = "password"
  ciuser = "ubuntu"

  sshkeys = <<EOF
ssh-rsa pubkey
  EOF
  provisioner "remote-exec" {
    inline = [
      "ip a",
    ]
  }
}

**Comment by ggongaware** [comment]
First thing to check, for cloud-init, unless there's something special about your template, make sure ssh_user should equal ciuser.

**Comment by csecsi** [comment]
I changed it but does not help. :(  Anyway this cannot explain of ignoring memory and cpu settings.
As I digged further I see that terraform seemingly hands over the info to proxmox:

2019-01-04T10:31:10.034Z [DEBUG] plugin.terraform-provider-proxmox: cipassword=password&ciuser=ubuntu&cores=4&description=first+terra+vm&ipconfig0=ip%3D192.168.0.100%2F24%2Cgw%3D192.168.0.1&memory=8192&net0=macaddr%3D27%3A77%3AE5%3A37%3A0B%3A14%2Cbridge%3Dvmbr0%2Cmodel%3Dvirtio&onboot=1&sockets=2&sshkeys=ssh-rsa%...&virtio0=media%3Ddisk%2Csize%3D20G%2Cfile%3Dimages%3A103%2Fvm-103-disk-1.raw%2Cformat%3Draw%2Cbackup%3D1)

**Comment by ggongaware** [comment]
Just checked in a bunch of fixes for remote-exec-provisioner

**Comment by csecsi** [comment]
THX for the fix. It is much better now. All the params are set but terraform crashes (comment: in the example config disk params should be in quotes else plan fails):

proxmox_vm_qemu.cloudinittest: Creating...
  cipassword:                   "" => "password"
  ciuser:                       "" => "ubuntu"
  clone:                        "" => "Ubuntu18.04Template"
  cores:                        "" => "4"
  desc:                         "" => "first terra vm"
  disk.#:                       "" => "1"
  disk.2737946891.backup:       "" => "true"
  disk.2737946891.cache:        "" => "none"
  disk.2737946891.format:       "" => "raw"
  disk.2737946891.id:           "" => "0"
  disk.2737946891.iothread:     "" => "false"
  disk.2737946891.replicate:    "" => "false"
  disk.2737946891.size:         "" => "20G"
  disk.2737946891.storage:      "" => "images"
  disk.2737946891.storage_type: "" => "raw"
  disk.2737946891.type:         "" => "virtio"
  force_create:                 "" => "false"
  ipconfig0:                    "" => "ip=192.168.0.100/24,gw=192.168.0.1"
  memory:                       "" => "8192"
  name:                         "" => "terra1"
  network.#:                    "" => "1"
  network.2049251291.bridge:    "" => "vmbr0"
  network.2049251291.firewall:  "" => "false"
  network.2049251291.id:        "" => "0"
  network.2049251291.link_down: "" => "false"
  network.2049251291.macaddr:   "" => "<computed>"
  network.2049251291.model:     "" => "virtio"
  network.2049251291.queues:    "" => "-1"
  network.2049251291.rate:      "" => "-1"
  network.2049251291.tag:       "" => "-1"
  onboot:                       "" => "true"
  os_type:                      "" => "cloud-init"
  preprovision:                 "" => "true"
  qemu_os:                      "" => "l26"
  sockets:                      "" => "2"
  ssh_user:                     "" => "ubuntu"
  sshkeys:                      "" => "ssh-rsa … root@proxmox\n  "
  target_node:                  "" => "proxmox"
  vlan:                         "" => "-1"
proxmox_vm_qemu.cloudinittest: Still creating... (10s elapsed)
proxmox_vm_qemu.cloudinittest: Still creating... (20s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* proxmox_vm_qemu.cloudinittest: 1 error(s) occurred:

* proxmox_vm_qemu.cloudinittest: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


**panic: interface conversion: interface {} is string, not float64**
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox:
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox: goroutine 24 [running]:
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.prepareDiskSize(0xc000344d00, 0xc000275840, 0xc0002d2e70, 0xe, 0x1)
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox:     /root/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:637 +0x5a9
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc00016e310, 0xdf2a40, 0xc000349800, 0xc00016e310, 0x0)
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox:     /root/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:411 +0x1365
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0003be300, 0xc00037c1e0, 0xc0000d9040, 0xdf2a40, 0xc000349800, 0x40d701, 0xc000082b80, 0x4bd30c)
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox:     /root/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x363
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0003ba770, 0xc00037c0a0, 0xc00037c1e0, 0xc0000d9040, 0xc0002d0e00, 0x18, 0x7f27aaa886c0)
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox:     /root/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0003ac4e0, 0xc0000d83a0, 0xc0000bd680, 0x0, 0x0)
2019-01-09T10:20:21.241Z [DEBUG] plugin.terraform-provider-proxmox:     /root/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:530 +0x57
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox: reflect.Value.call(0xc0003466c0, 0xc00034e048, 0x13, 0xfcec3b, 0x4, 0xc000082f18, 0x3, 0x3, 0xc0000d0080, 0x0, ...)
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox:     /usr/lib/go-1.11/src/reflect/value.go:447 +0x454
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox: reflect.Value.Call(0xc0003466c0, 0xc00034e048, 0x13, 0xc0004dd718, 0x3, 0x3, 0x0, 0x0, 0x0)
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox:     /usr/lib/go-1.11/src/reflect/value.go:308 +0xa4
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox: net/rpc.(*service).call(0xc000344200, 0xc00037c190, 0xc0003501b0, 0xc0003501c0, 0xc000364200, 0xc00034aa00, 0xdf38c0, 0xc0000d83a0, 0x16, 0xdf3900, ...)
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox:     /usr/lib/go-1.11/src/net/rpc/server.go:384 +0x14e
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox: created by net/rpc.(*Server).ServeCodec
2019-01-09T10:20:21.242Z [DEBUG] plugin.terraform-provider-proxmox:     /usr/lib/go-1.11/src/net/rpc/server.go:481 +0x47e
2019-01-09T10:20:21.245Z [DEBUG] plugin: plugin process exited: path=/home/ubuntu/.terraform.d/plugins/terraform-provider-proxmox
2019/01/09 10:20:21 [TRACE] root: eval: *terraform.EvalWriteState
2019/01/09 10:20:21 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/01/09 10:20:21 [TRACE] root: eval: *terraform.EvalIf
2019/01/09 10:20:21 [TRACE] root: eval: *terraform.EvalWriteState
2019/01/09 10:20:21 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/01/09 10:20:21 [TRACE] root: eval: *terraform.EvalApplyPost
2019/01/09 10:20:21 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* proxmox_vm_qemu.cloudinittest: unexpected EOF
2019/01/09 10:20:21 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* proxmox_vm_qemu.cloudinittest: unexpected EOF
2019/01/09 10:20:21 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.cloudinittest
2019/01/09 10:20:21 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/01/09 10:20:21 [TRACE] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
2019/01/09 10:20:21 [TRACE] dag/walk: upstream errored, not walking "provider.proxmox (close)"
2019/01/09 10:20:21 [TRACE] dag/walk: upstream errored, not walking "root"
2019/01/09 10:20:21 [TRACE] Preserving existing state lineage "bdba148c-e750-2ea8-4b4b-612fcd3e636c"
2019/01/09 10:20:21 [TRACE] Preserving existing state lineage "bdba148c-e750-2ea8-4b4b-612fcd3e636c"
2019/01/09 10:20:21 [TRACE] Preserving existing state lineage "bdba148c-e750-2ea8-4b4b-612fcd3e636c"
2019/01/09 10:20:21 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-01-09T10:20:21.257Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-01-09T10:20:21.259Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/01/09 10:20:21 [ERR] plugin: plugin server: accept unix /tmp/plugin228161509: use of closed network connection
2019-01-09T10:20:21.259Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/01/09 10:20:21 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-01-09T10:20:21.262Z [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform

**Comment by ggongaware** [comment]
Checked in a fix for that interface conversion panic: 414c2fc74912c52f8c2815d35cfab13d26b3622c

**Comment by csecsi** [comment]
it is perfect now. Thank you for the quick fix.
