### ISSUE TITLE
v2.6.8 plugin crash LXC Proxmox 6.3

### ISSUE THREAD

**Issue by Ramshield** [Telmate/terraform-provider-proxmox#333]
```
root@server-01:/home/jklapwijk/terraform# terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_lxc.create_container[0] will be created
  + resource "proxmox_lxc" "create_container" {
      + arch         = "amd64"
      + cmode        = "tty"
      + console      = true
      + cpulimit     = 0
      + cpuunits     = 1024
      + hostname     = "unifi"
      + id           = (known after apply)
      + memory       = 512
      + onboot       = false
      + ostemplate   = "local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz"
      + ostype       = (known after apply)
      + protection   = false
      + start        = false
      + swap         = 512
      + target_node  = "server-01"
      + tty          = 2
      + unprivileged = false
      + vmid         = 0
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_lxc.create_container[0]: Creating...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-proxmox_v2.6.8 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 15 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceLxcCreate(0xc000214e80, 0xb50780, 0xc000271ef0, 0x0, 0x0)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:441 +0x12cd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000318c60, 0xdbf320, 0xc00030e400, 0xc000214e80, 0xb50780, 0xc000271ef0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/helper/schema/resource.go:268 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000318c60, 0xdbf320, 0xc00030e400, 0xc0001922a0, 0xc000604a40, 0xb50780, 0xc000271ef0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/helper/schema/resource.go:386 +0x681
github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0003041c0, 0xdbf320, 0xc00030e400, 0xc000192000, 0xc0003041c0, 0xc0003041d0, 0xcc8738)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/internal/helper/plugin/grpc_provider.go:952 +0x8b2
github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler.func1(0xdbf320, 0xc00030e400, 0xc5a0a0, 0xc000192000, 0xc00030e400, 0xbdcf60, 0xc000094601, 0xc000604400)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/internal/tfplugin5/tfplugin5.pb.go:3312 +0x86
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0xdbf3e0, 0xc0003030b0, 0xc5a0a0, 0xc000192000, 0xc0006043e0, 0xc000604400, 0xc0002d3ba0, 0x5863c8, 0xc32360, 0xc0003030b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/plugin/serve.go:76 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc68320, 0xc0003041c0, 0xdbf3e0, 0xc0003030b0, 0xc000094600, 0xc0001f70a0, 0xdbf3e0, 0xc0003030b0, 0xc000134800, 0x3c1)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/internal/tfplugin5/tfplugin5.pb.go:3314 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00033c700, 0xdc7f00, 0xc000509680, 0xc000178300, 0xc000302f00, 0x12ec820, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc00033c700, 0xdc7f00, 0xc000509680, 0xc000178300, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030a1a0, 0xc00033c700, 0xdc7f00, 0xc000509680, 0xc000178300)
        google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.30.0/server.go:832 +0x204

Error: The terraform-provider-proxmox_v2.6.8 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Respective Terraform code:

```
#terraform {
#  required_providers {
#    lxd = {
#      source = "sl1pm4t/lxd"
#    }
#  }
#}

terraform {
  required_providers {
    proxmox = {
      source = "Telmate/proxmox"
      version = "2.6.8"
    }
  }
}

provider "proxmox" {
    pm_api_url = "https://server-01t:8006/api2/json"
    pm_user = "user@pam"
    pm_tls_insecure = true
}

locals {
  containers = [
    { hostname = "unifi", template = "local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz", grains = { roles = ["unifi", "haproxy", "mongodb"] } },

  ]
}

#resource "lxd_cached_image" "image" {
#  count         = length(local.images)
#  aliases       = lookup(local.images[count.index], "alias")
#  source_remote = lookup(local.images[count.index], "source_remote")
#  source_image  = lookup(local.images[count.index], "source_image")
#}

resource "proxmox_lxc" "create_container" {
  count = length(local.containers)

  hostname = lookup(local.containers[count.index], "hostname")
  ostemplate = lookup(local.containers[count.index], "template")
  target_node = "server-01"
  #ephemeral = false

  #config = {
    #"boot.autostart" = true
  #}

  provisioner "local-exec" {
    when    = destroy
    command = <<EOT
      sudo salt-key --force-color --yes -d ${self.hostname}
      EOT
  }

  provisioner "local-exec" {
    command = <<EOT
      cd /home/user/ansible
      sudo ansible-playbook common.yml --limit ${lookup(local.containers[count.index], "hostname")}
      sleep 4s
      sudo salt-key --force-color --yes -a  ${lookup(local.containers[count.index], "hostname")}
      sudo lxc exec ${lookup(local.containers[count.index], "hostname")} -- bash -c "echo '${yamlencode(lookup(local.containers[count.index], "grains"))}' > /etc/salt/grains"
      sudo lxc exec ${lookup(local.containers[count.index], "hostname")} -- "systemctl restart salt-minion"
      sleep 10s
      sudo salt --force-color '${lookup(local.containers[count.index], "hostname")}' state.highstate
      EOT
  }
}
```

This code worked when I was using plain LXD before.

Clean install, please advice. If I can provide any other information, please let me know!

**Comment by Ramshield** [comment]
Switching back to version Terraform v0.14.3 fixes the issue.
The problem seems to be in Terraform v0.15.0.

**Comment by tagur87** [comment]
You must specific `rootfs` for this to work properly. See https://github.com/Telmate/terraform-provider-proxmox#known-limitations for more information.

Something like this is all thats needed in your lxc resource.
```terraform
  rootfs {
    storage = "Synatto-NFS"
    size    = "16G"
  }
```

**Comment by JimKlapwijk** [comment]
> You must specify `rootfs` for this to work properly. See https://github.com/Telmate/terraform-provider-proxmox#known-limitations for more information.
> 
> Something like this is all thats needed in your lxc resource.
> 
> ```terraform
>   rootfs {
>     storage = "Synatto-NFS"
>     size    = "16G"
>   }
> ```
> 
> Tested successfully on v2.6.9 plugin with Terraform 15.1.

I indeed noticed when switching back to v0.14.3, that gave a clear error message.
I haven't tried this on Terraform v0.15.X, will try in a bit!
