### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by MayamaTakeshi** [Telmate/terraform-provider-proxmox#355]
I've been seeing this issue for some time with previous commits.
I tried again today with latest 0d6e7d75f4086f54575473d705cbc01853ee21a7 but it still happens:
```
(base) takeshi:lab225131$ go version
go version go1.16.4 linux/amd64

(base) takeshi:lab225131$ terraform version
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/telmate/proxmox v2.0.0

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html

(base) takeshi:lab225131$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_vm_qemu.basix-ban will be created
  + resource "proxmox_vm_qemu" "basix-ban" {
      + agent                  = 1
      + balloon                = 0
      + bios                   = "seabios"
      + boot                   = "cdn"
      + bootdisk               = (known after apply)
      + clone                  = "debian10-raw-template"
      + clone_wait             = 15
      + cores                  = 1
      + cpu                    = "host"
      + define_connection_info = true
      + desc                   = "basix-ban"
      + force_create           = false
      + full_clone             = true
      + hotplug                = "network,disk,usb"
      + id                     = (known after apply)
      + ipconfig0              = "ip=192.168.225.131/24,gw=192.168.225.254"
      + kvm                    = true
      + memory                 = 512
      + name                   = "lab225131"
      + nameserver             = (known after apply)
      + numa                   = false
      + onboot                 = true
      + os_type                = "cloud-init"
      + preprovision           = true
      + scsihw                 = "virtio-scsi-pci"
      + searchdomain           = (known after apply)
      + sockets                = 1
      + ssh_host               = (known after apply)
      + ssh_port               = (known after apply)
      + target_node            = "labprox04221"
      + unused_disk            = (known after apply)
      + vcpus                  = 0
      + vlan                   = -1
      + vmid                   = (known after apply)

      + disk {
          + backup       = false
          + cache        = "none"
          + file         = (known after apply)
          + format       = (known after apply)
          + iothread     = false
          + mbps         = 0
          + mbps_rd      = 0
          + mbps_rd_max  = 0
          + mbps_wr      = 0
          + mbps_wr_max  = 0
          + media        = (known after apply)
          + replicate    = false
          + size         = "32G"
          + slot         = (known after apply)
          + storage      = "lvpve001"
          + storage_type = (known after apply)
          + type         = "scsi"
          + volume       = (known after apply)
        }

      + network {
          + bridge    = "vmbr3"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
    }

  # proxmox_vm_qemu.basix-fe will be created
  + resource "proxmox_vm_qemu" "basix-fe" {
      + agent                  = 1
      + balloon                = 0
      + bios                   = "seabios"
      + boot                   = "cdn"
      + bootdisk               = (known after apply)
      + clone                  = "debian10-raw-template"
      + clone_wait             = 15
      + cores                  = 1
      + cpu                    = "host"
      + define_connection_info = true
      + desc                   = "basix-fe"
      + force_create           = false
      + full_clone             = true
      + hotplug                = "network,disk,usb"
      + id                     = (known after apply)
      + ipconfig0              = "ip=192.168.225.133/24,gw=192.168.225.254"
      + kvm                    = true
      + memory                 = 512
      + name                   = "lab225133-basix-fe"
      + nameserver             = (known after apply)
      + numa                   = false
      + onboot                 = true
      + os_type                = "cloud-init"
      + preprovision           = true
      + scsihw                 = "virtio-scsi-pci"
      + searchdomain           = (known after apply)
      + sockets                = 1
      + ssh_host               = (known after apply)
      + ssh_port               = (known after apply)
      + target_node            = "labprox04221"
      + unused_disk            = (known after apply)
      + vcpus                  = 0
      + vlan                   = -1
      + vmid                   = (known after apply)

      + disk {
          + backup       = false
          + cache        = "none"
          + file         = (known after apply)
          + format       = (known after apply)
          + iothread     = false
          + mbps         = 0
          + mbps_rd      = 0
          + mbps_rd_max  = 0
          + mbps_wr      = 0
          + mbps_wr_max  = 0
          + media        = (known after apply)
          + replicate    = false
          + size         = "32G"
          + slot         = (known after apply)
          + storage      = "lvpve001"
          + storage_type = (known after apply)
          + type         = "scsi"
          + volume       = (known after apply)
        }

      + network {
          + bridge    = "vmbr3"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
    }

  # proxmox_vm_qemu.basix-tester will be created
  + resource "proxmox_vm_qemu" "basix-tester" {
      + agent                  = 1
      + balloon                = 0
      + bios                   = "seabios"
      + boot                   = "cdn"
      + bootdisk               = (known after apply)
      + clone                  = "debian10-raw-template"
      + clone_wait             = 15
      + cores                  = 1
      + cpu                    = "host"
      + define_connection_info = true
      + desc                   = "basix-tester"
      + force_create           = false
      + full_clone             = true
      + hotplug                = "network,disk,usb"
      + id                     = (known after apply)
      + ipconfig0              = "ip=192.168.225.132/24,gw=192.168.225.254"
      + ipconfig1              = "ip=10.255.255.132/24,gw=10.255.255.254"
      + kvm                    = true
      + memory                 = 512
      + name                   = "lab225132-basix-tester"
      + nameserver             = (known after apply)
      + numa                   = false
      + onboot                 = true
      + os_type                = "cloud-init"
      + preprovision           = true
      + scsihw                 = "virtio-scsi-pci"
      + searchdomain           = (known after apply)
      + sockets                = 1
      + ssh_host               = (known after apply)
      + ssh_port               = (known after apply)
      + target_node            = "labprox04221"
      + unused_disk            = (known after apply)
      + vcpus                  = 0
      + vlan                   = -1
      + vmid                   = (known after apply)

      + disk {
          + backup       = false
          + cache        = "none"
          + file         = (known after apply)
          + format       = (known after apply)
          + iothread     = false
          + mbps         = 0
          + mbps_rd      = 0
          + mbps_rd_max  = 0
          + mbps_wr      = 0
          + mbps_wr_max  = 0
          + media        = (known after apply)
          + replicate    = false
          + size         = "32G"
          + slot         = (known after apply)
          + storage      = "lvpve001"
          + storage_type = (known after apply)
          + type         = "scsi"
          + volume       = (known after apply)
        }

      + network {
          + bridge    = "vmbr3"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
      + network {
          + bridge    = "vmbr4"
          + firewall  = false
          + link_down = false
          + macaddr   = (known after apply)
          + model     = "virtio"
          + queues    = (known after apply)
          + rate      = (known after apply)
          + tag       = -1
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_vm_qemu.basix-fe: Creating...
proxmox_vm_qemu.basix-ban: Creating...
proxmox_vm_qemu.basix-tester: Creating...
proxmox_vm_qemu.basix-ban: Still creating... [10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [10s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [20s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [20s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [30s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [40s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [40s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [40s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [50s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [50s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [1m0s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [1m0s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [1m0s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [1m10s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [1m10s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [1m10s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [1m20s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [1m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [1m20s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [1m30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [1m30s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [1m30s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [1m40s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [1m40s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [1m40s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [1m50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [1m50s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [1m50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [2m0s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [2m0s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [2m0s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [2m10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [2m10s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [2m10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [2m20s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [2m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [2m20s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [2m30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [2m30s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [2m30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [2m40s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [2m40s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [2m40s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [2m50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [2m50s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [2m50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [3m0s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [3m0s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [3m0s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [3m10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [3m10s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [3m10s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [3m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [3m20s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [3m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [3m30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [3m30s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [3m30s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [3m40s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [3m40s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [3m40s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [3m50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [3m50s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [3m50s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [4m0s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [4m0s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [4m0s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [4m10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [4m10s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [4m10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [4m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [4m20s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [4m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [4m30s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [4m30s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [4m30s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [4m40s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [4m40s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [4m40s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [4m50s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [4m50s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [4m50s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [5m0s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [5m0s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [5m0s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [5m10s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [5m10s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [5m10s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [5m20s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [5m20s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [5m20s elapsed]
proxmox_vm_qemu.basix-ban: Still creating... [5m30s elapsed]
proxmox_vm_qemu.basix-fe: Still creating... [5m30s elapsed]
proxmox_vm_qemu.basix-tester: Still creating... [5m30s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.basix-ban,
│   on lab225131.tf line 25, in resource "proxmox_vm_qemu" "basix-ban":
│   25: resource "proxmox_vm_qemu" "basix-ban" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.basix-tester,
│   on lab225131.tf line 58, in resource "proxmox_vm_qemu" "basix-tester":
│   58: resource "proxmox_vm_qemu" "basix-tester" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.basix-fe,
│   on lab225131.tf line 98, in resource "proxmox_vm_qemu" "basix-fe":
│   98: resource "proxmox_vm_qemu" "basix-fe" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x8f1610]

goroutine 27 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000664f00, 0xb794c0, 0xc00042a000, 0x0, 0x0)
	/home/takeshi/extra/src/git/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:802 +0x22f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003168f0, 0xd9e800, 0xc0001ae500, 0xc000664f00, 0xb794c0, 0xc00042a000, 0x0, 0x0, 0x0)
	/home/takeshi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/helper/schema/resource.go:268 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003168f0, 0xd9e800, 0xc0001ae500, 0xc0000da460, 0xc0004a3240, 0xb794c0, 0xc00042a000, 0x0, 0x0, 0x0, ...)
	/home/takeshi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/helper/schema/resource.go:386 +0x65b
github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0003041c0, 0xd9e800, 0xc0001ae500, 0xc0000da230, 0xc0003041c0, 0xc0003041d0, 0xce0a90)
	/home/takeshi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/internal/helper/plugin/grpc_provider.go:952 +0x8cf
github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler.func1(0xd9e800, 0xc0001ae500, 0xc73fe0, 0xc0000da230, 0xc0001ae500, 0xbfb560, 0x1, 0xc0004a2040)
	/home/takeshi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/internal/tfplugin5/tfplugin5.pb.go:3312 +0x89
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0xd9e8c0, 0xc0005ec000, 0xc73fe0, 0xc0000da230, 0xc0004a2020, 0xc0004a2040, 0xc000523ba0, 0x59da66, 0xc4c9a0, 0xc0005ec000)
	/home/takeshi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/plugin/serve.go:76 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc81fc0, 0xc0003041c0, 0xd9e8c0, 0xc0005ec000, 0xc000412060, 0xc000201660, 0xd9e8c0, 0xc0005ec000, 0xc0007cea80, 0x91d)
	/home/takeshi/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.1.0/internal/tfplugin5/tfplugin5.pb.go:3314 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00033a700, 0xda64e0, 0xc000503680, 0xc000702000, 0xc0002b0750, 0x11d0b20, 0x0, 0x0, 0x0)
	/home/takeshi/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00033a700, 0xda64e0, 0xc000503680, 0xc000702000, 0x0)
	/home/takeshi/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030a1d0, 0xc00033a700, 0xda64e0, 0xc000503680, 0xc000702000)
	/home/takeshi/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/takeshi/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd

Error: The terraform-provider-proxmox plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by pgporada** [comment]
You will want to enable the provider debug log. Checking the proxmox web hi
console might also give you the failure reason. I agree the provider
shouldn't explode all over the place like this and that the error returns
are subpar at best.

**Comment by pgporada** [comment]
The way you'll enable the provider debug log is as follows (probably in your main.tf)
```
provider "proxmox" {
  pm_tls_insecure = true
  pm_log_enable   = true
  pm_log_file     = "terraform-plugin-proxmox.log"
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}
```

Then you'll run terraform apply to attempt building your VM even though you experience the panic. After the panic, you'll be able to open the debug log with `less -R terraform-plugin-proxmox.log`. Somewhere in there you'll see the true failure as returned by the Proxmox API (not terraform, not the proxmox-golang-api).

**Comment by MayamaTakeshi** [comment]
I enabled debug log: [Uploading terraform-plugin-proxmox.log…]() 
But there is no error. I confirmed in the proxy WebGUI: the terraform file asks for creation of 3 VMs cloned from the same vm-template and all 3 cloning operations succeed.

I tried separating each VM in their own terraform files and executing 'terraform apply' for each of them separately was successful.
So I suppose the plugin has issues handling multiple VMs (or maybe some timeout is triggering a bug since it needs to wait for longer for the operations to complete (each VM  separately is taking about 4 minutes to be created).

I think this is not highly critical: I will change my automation procedure to create each VM one by one by adding them to the terraform file after the previous one is created.

**Comment by pgporada** [comment]
In my environment able to spin up multiple VMs in parallel. Can you post
your .tf file so I can test it?

**Comment by mleone87** [comment]
according to this line it crashes silently there 	/home/takeshi/extra/src/git/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:802 +0x22f0

https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L802


but from logs it goes ahead in creating the vm(getting a free vm id)

dont know whats happening there... is the server powerful enough? what kind of template are you using?

**Comment by MayamaTakeshi** [comment]
@pgporada 

Here is the .tf file (renamed with .txt suffix):
[main.txt](https://github.com/Telmate/terraform-provider-proxmox/files/6527911/main.txt)

It tries to create 3 VMs from a template with a disk of 30GB.

However, I tried creating a new template with a disk of 120GB. 
Then I tried to create a single VM with it and the same crash happened.
I compared the timing of the crashes:

Three VMs of 30GB: 5m44.014s

One VM of 120GB: 5m47.903s

So, this is not related to multiple VMs. 
Instead it seems the plugin cannot wait for very long for the cloning operation to complete.

**Comment by MayamaTakeshi** [comment]
@mleone87 
I suppose the server is OK. It is a 16-core machine:
```
# grep "model name" /proc/cpuinfo 
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
```
But as mentioned in my previous post I think the problem is that the plugin doesn't handle template cloning timeout properly.

**Comment by MayamaTakeshi** [comment]
> I think this is not highly critical: I will change my automation procedure to create each VM one by one by adding them to the terraform file after the previous one is created.

Checking the docs, I realized I just need to instruct terraform to create one VM at a time by doing:
```
terraform apply -parallelism=1
```
and I can use pm_timeout in the tf file to increase the proxmox API reply timeout (but with the caveat mentioned in #358).

(well all this would eventually fail if more than one person runs 'terraform apply -parallelism=1' at the same time causing more than on template cloning to happen simultaneously but it is not my case).
