### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by rkoosaar** [Telmate/terraform-provider-proxmox#366]
Do you guys know what might be the cause of this crash?

```Plan: 1 to add, 0 to change, 0 to destroy.
module.pve_vm_test.proxmox_vm_qemu.vm_qemu[0]: Creating...
module.pve_vm_test.proxmox_vm_qemu.vm_qemu[0]: Still creating... [10s elapsed]
module.pve_vm_test.proxmox_vm_qemu.vm_qemu[0]: Still creating... [20s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with module.pve_vm_test.proxmox_vm_qemu.vm_qemu[0],
│   on ../../../tf_modules/terraform-proxmox-vm/main.tf line 1, in resource "proxmox_vm_qemu" "vm_qemu":
│    1: resource "proxmox_vm_qemu" "vm_qemu" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.7.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 54 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).createVMDisks(0xc0004424b0, 0xc00070e560, 0x6, 0xc000454988, 0xb, 0x0, 0x0, 0xc00070e130, 0x4)
        github.com/Telmate/proxmox-api-go@v0.0.0-20210507143528-c60bbda13c0c/proxmox/client.go:821 +0x772
github.com/Telmate/proxmox-api-go/proxmox.ConfigQemu.UpdateConfig(0x0, 0xc00003e4c0, 0x19, 0xc00070e1c4, 0xb, 0x0, 0x0, 0xc00070e130, 0x4, 0x0, ...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20210507143528-c60bbda13c0c/proxmox/config_qemu.go:285 +0xac9
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc00004d300, 0xb75b40, 0xc0002980a0, 0x0, 0x0)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:853 +0x2b1b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000380460, 0xd9e098, 0xc0002ca040, 0xc00004d300, 0xb75b40, 0xc0002980a0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000380460, 0xd9e098, 0xc0002ca040, 0xc00033a3f0, 0xc0003fd040, 0xb75b40, 0xc0002980a0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000316090, 0xd9e098, 0xc0002ca040, 0xc00031a780, 0xc0002ca040, 0xc6f160, 0xc0002c4c00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000099ba0, 0xd9e140, 0xc0002ca040, 0xc00033a1c0, 0xc000099ba0, 0xc0002c4cc0, 0xc000798ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc6f160, 0xc000099ba0, 0xd9e140, 0xc0002c4cc0, 0xc0002a2420, 0x0, 0xd9e140, 0xc0002c4cc0, 0xc000019000, 0xb5a)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000330380, 0xda57f8, 0xc000502900, 0xc000126200, 0xc0002c4720, 0x11b0ce0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000330380, 0xda57f8, 0xc000502900, 0xc000126200, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000036500, 0xc000330380, 0xda57f8, 0xc000502900, 0xc000126200)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-proxmox_v2.7.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by rkoosaar** [comment]
I'll close this out, it seems it was triggered by my  tf code which I have slightly rewritten

**Comment by radosevic** [comment]
Hi,
I think I have similar problem like you did.
Please, take a look... 
https://github.com/Telmate/terraform-provider-proxmox/issues/388
What in your code triggered this? Would you mind sharing what was the problem?
Thanks
