### ISSUE TITLE
How can I tell if my userdata file is being copied over to the VM and executed?

### ISSUE THREAD

**Issue by dmoore44** [Telmate/terraform-provider-proxmox#403]
I have a VM that I am creating from a template. The template has cloudbase-init installed, and I have created the proper `unattend.xml` and `cloudbase-init-unattend.conf` files. I also pre-installed the qemu guest agent.

In my` main.tf` file, I define a local_file resource to grab the file from my local system, then use a null_resource to copy the file over to proxmox like this:

```
# Create a local copy of the file, to transfer to Proxmox
resource "local_file" "cloud_init_windows_vm-01" {
  content   = data.template_file.cloud_init_windows_vm-01.rendered
  filename  = "${path.module}/files/user_data_cloud_init_windows_vm-01.cfg"
}

# Transfer the file to the Proxmox Host
resource "null_resource" "cloud_init_win2k19_vm-01" {
  connection {
    type    = "ssh"
    user    = "root"
    private_key = file("~/.ssh/pve01")
    host    = "10.0.0.10"
  }

  provisioner "file" {
    source       = local_file.cloud_init_windows_vm-01.filename
    destination  = "/var/lib/vz/snippets/cloud_init_windows_vm-01.yml"
  }
}
```

If I go and check my local storage/snippets location in Proxmox, I can see that the yml file makes it to the proper location on the Proxmox host successfully.

As for the yml file itself... I'm using a multi-part userdata file that looks something like this:

```
Content-Type: multipart/mixed; boundary="==BOUNDARY=="
MIME-Version: 1.0

--==BOUNDARY==
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config"


write_files:
  - encoding: b64
    content: some b64 stuff that I want executed
    path: C:\\terraform
    permissions: '0644'
 

--==BOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="hi.ps1"

#ps1
Write-Host "Hi - I'm just seeing if this works"
```

By way of logs, I've checked in `cloudbase-init.log`... but I don't see anything useful

```
2021-09-16 12:07:50.891 2680 WARNING cloudbaseinit.utils.log [-] Serial port: COM1,115200,N,8 could not be opened: serial.serialutil.SerialException: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-09-16 12:07:50.907 2680 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.osutils.windows.WindowsUtils' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 12:07:52.797 2680 DEBUG cloudbaseinit.osutils.windows [-] Checking if service exists: cloudbase-init check_service_exists C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1092
2021-09-16 12:07:52.797 2680 DEBUG cloudbaseinit.osutils.windows [-] Getting service username: cloudbase-init get_service_username C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1225
2021-09-16 12:07:52.813 2680 DEBUG cloudbaseinit.osutils.windows [-] Resetting password for service user: .\cloudbase-init reset_service_password C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1248
2021-09-16 12:07:53.094 2680 DEBUG cloudbaseinit.osutils.windows [-] Setting service credentials: cloudbase-init set_service_credentials C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1208
2021-09-16 12:07:53.157 2680 INFO cloudbaseinit.init [-] Respawning current process with updated credentials.
2021-09-16 12:07:53.157 2680 DEBUG cloudbaseinit.osutils.windows [-] Creating logon session for user: .\cloudbase-init create_user_logon_session C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:649
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell [-] Cannot load user profile: 'The device is not ready.': cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot load user profile: 'The device is not ready.'
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell Traceback (most recent call last):
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\shell.py", line 33, in main
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell     init.InitManager().configure_host()
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\init.py", line 172, in configure_host
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell     self._reset_service_password_and_respawn(osutils)
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\init.py", line 162, in _reset_service_password_and_respawn
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell     logon_type=osutils.LOGON32_LOGON_BATCH)
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py", line 670, in create_user_logon_session
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell     "Cannot load user profile: %r")
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot load user profile: 'The device is not ready.'
2021-09-16 12:07:53.172 2680 ERROR cloudbaseinit.shell 
2021-09-16 12:07:53.344 2680 CRITICAL cloudbaseinit [-] Unhandled error: cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot load user profile: 'The device is not ready.'
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit Traceback (most recent call last):
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\runpy.py", line 193, in _run_module_as_main
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     "__main__", mod_spec)
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\runpy.py", line 85, in _run_code
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     exec(code, run_globals)
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\Scripts\cloudbase-init.exe\__main__.py", line 7, in <module>
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     sys.exit(main())
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\shell.py", line 33, in main
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     init.InitManager().configure_host()
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\init.py", line 172, in configure_host
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     self._reset_service_password_and_respawn(osutils)
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\init.py", line 162, in _reset_service_password_and_respawn
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     logon_type=osutils.LOGON32_LOGON_BATCH)
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py", line 670, in create_user_logon_session
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit     "Cannot load user profile: %r")
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot load user profile: 'The device is not ready.'
2021-09-16 12:07:53.344 2680 ERROR cloudbaseinit 
2021-09-16 10:09:39.381 3624 WARNING cloudbaseinit.utils.log [-] Serial port: COM1,115200,N,8 could not be opened: serial.serialutil.SerialException: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-09-16 10:09:39.398 3624 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.osutils.windows.WindowsUtils' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:42.616 3624 DEBUG cloudbaseinit.osutils.windows [-] Checking if service exists: cloudbase-init check_service_exists C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1092
2021-09-16 10:09:42.633 3624 DEBUG cloudbaseinit.osutils.windows [-] Getting service username: cloudbase-init get_service_username C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1225
2021-09-16 10:09:42.633 3624 DEBUG cloudbaseinit.osutils.windows [-] Resetting password for service user: .\cloudbase-init reset_service_password C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1248
2021-09-16 10:09:42.732 3624 DEBUG cloudbaseinit.osutils.windows [-] Setting service credentials: cloudbase-init set_service_credentials C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1208
2021-09-16 10:09:42.765 3624 INFO cloudbaseinit.init [-] Respawning current process with updated credentials.
2021-09-16 10:09:42.765 3624 DEBUG cloudbaseinit.osutils.windows [-] Creating logon session for user: .\cloudbase-init create_user_logon_session C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:649
2021-09-16 10:09:42.798 3624 DEBUG cloudbaseinit.osutils.windows [-] Executing process as user, command line: ['C:\\Program Files\\Cloudbase Solutions\\Cloudbase-Init\\Python\\Scripts\\cloudbase-init', '--config-file', 'C:\\Program Files\\Cloudbase Solutions\\Cloudbase-Init\\conf\\cloudbase-init.conf', '--noreset_service_password'] execute_process_as_user C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:703
2021-09-16 10:09:45.157 4456 WARNING cloudbaseinit.utils.log [-] Serial port: COM1,115200,N,8 could not be opened: serial.serialutil.SerialException: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2021-09-16 10:09:45.157 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.osutils.windows.WindowsUtils' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.370 4456 INFO cloudbaseinit.init [-] Cloudbase-Init version: 1.1.2
2021-09-16 10:09:45.370 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.networkconfig.NetworkConfigPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.403 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.setuserpassword.SetUserPasswordPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.502 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.userdata.UserDataPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.584 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.sethostname.SetHostNamePlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.600 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.mtu.MTUPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.650 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.windows.extendvolumes.ExtendVolumesPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 INFO cloudbaseinit.init [-] Executing plugins for stage 'PRE_NETWORKING':
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.networkconfig.NetworkConfigPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.setuserpassword.SetUserPasswordPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.userdata.UserDataPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.sethostname.SetHostNamePlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.common.mtu.MTUPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.plugins.windows.extendvolumes.ExtendVolumesPlugin' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.682 4456 INFO cloudbaseinit.init [-] Executing plugins for stage 'PRE_METADATA_DISCOVERY':
2021-09-16 10:09:45.682 4456 INFO cloudbaseinit.init [-] Executing plugin 'MTUPlugin'
2021-09-16 10:09:45.682 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.osutils.windows.WindowsUtils' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:45.715 4456 DEBUG urllib3.connectionpool [-] Starting new HTTPS connection (1): www.cloudbase.it:443 _new_conn C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connectionpool.py:941
2021-09-16 10:09:45.715 4456 DEBUG cloudbaseinit.osutils.windows [-] Setting MTU for interface "Ethernet Instance 0" with value "1500" set_network_adapter_mtu C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:843
2021-09-16 10:09:46.256 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.metadata.services.configdrive.ConfigDriveService' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:46.321 4456 WARNING oslo_config.cfg [-] Deprecated: Option "config_drive_raw_hhd" from group "DEFAULT" is deprecated. Use option "raw_hdd" from group "config_drive".
2021-09-16 10:09:46.321 4456 WARNING oslo_config.cfg [-] Deprecated: Option "raw_hdd" from group "config_drive" is deprecated for removal.  Its value may be silently ignored in the future.
2021-09-16 10:09:46.321 4456 WARNING oslo_config.cfg [-] Deprecated: Option "config_drive_cdrom" from group "DEFAULT" is deprecated. Use option "cdrom" from group "config_drive".
2021-09-16 10:09:46.321 4456 WARNING oslo_config.cfg [-] Deprecated: Option "cdrom" from group "config_drive" is deprecated for removal.  Its value may be silently ignored in the future.
2021-09-16 10:09:46.321 4456 WARNING oslo_config.cfg [-] Deprecated: Option "config_drive_vfat" from group "DEFAULT" is deprecated. Use option "vfat" from group "config_drive".
2021-09-16 10:09:46.321 4456 WARNING oslo_config.cfg [-] Deprecated: Option "vfat" from group "config_drive" is deprecated for removal.  Its value may be silently ignored in the future.
2021-09-16 10:09:46.321 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.metadata.services.osconfigdrive.windows.WindowsConfigDriveManager' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:46.354 4456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.osutils.windows.WindowsUtils' load_class C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2021-09-16 10:09:46.354 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for Config Drive vfat in partition with expected label config-2 get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:218
2021-09-16 10:09:46.354 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for a Config Drive with label 'config-2' on '\\?\Volume{90317d9c-0000-0000-0000-100000000000}\'. Found mismatching label 'System Reserved'. _check_for_config_drive C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:70
2021-09-16 10:09:46.354 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for a Config Drive with label 'config-2' on '\\?\Volume{90317d9c-0000-0000-0000-602200000000}\'. Found mismatching label ''. _check_for_config_drive C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:70
2021-09-16 10:09:46.354 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for Config Drive vfat in hdd with expected label config-2 get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:218
2021-09-16 10:09:46.518 4456 DEBUG cloudbaseinit.utils.windows.vfat [-] Could not retrieve label for VFAT drive path '\\\\.\\PHYSICALDRIVE0' is_vfat_drive C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\windows\vfat.py:46
2021-09-16 10:09:46.518 4456 DEBUG cloudbaseinit.utils.windows.vfat [-] mlabel failed with error b"init :: sector size (190) not a small power of two\r\nCannot initialize '::'\r\nC:\\Program Files\\Cloudbase Solutions\\Cloudbase-Init\\bin\\mlabel: Cannot initialize drive\r\n" is_vfat_drive C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\windows\vfat.py:47
2021-09-16 10:09:46.534 4456 DEBUG cloudbaseinit.utils.windows.vfat [-] Could not retrieve label for VFAT drive path '\\\\.\\PHYSICALDRIVE1' is_vfat_drive C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\windows\vfat.py:46
2021-09-16 10:09:46.534 4456 DEBUG cloudbaseinit.utils.windows.vfat [-] mlabel failed with error b"init :: sector size (190) not a small power of two\r\nCannot initialize '::'\r\nC:\\Program Files\\Cloudbase Solutions\\Cloudbase-Init\\bin\\mlabel: Cannot initialize drive\r\n" is_vfat_drive C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\windows\vfat.py:47
2021-09-16 10:09:46.534 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for Config Drive vfat in cdrom with expected label config-2 get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:218
2021-09-16 10:09:46.534 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Irrelevant type vfat in cdrom location; skip _get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:200
2021-09-16 10:09:46.551 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for Config Drive iso in partition with expected label config-2 get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:218
2021-09-16 10:09:46.583 4456 WARNING cloudbaseinit.metadata.services.osconfigdrive.windows [-] ISO extraction failed on <Partition: \\?\GLOBALROOT\Device\Harddisk0\Partition1> with WindowsCloudbaseInitException("Cannot open file: 'The process cannot access the file because it is being used by another process.'",): cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot open file: 'The process cannot access the file because it is being used by another process.'
2021-09-16 10:09:46.633 4456 DEBUG urllib3.connectionpool [-] https://www.cloudbase.it:443 "GET /checkupdates.php?p=Cloudbase-Init&v=1.1.2 HTTP/1.1" 200 None _make_request C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connectionpool.py:442
2021-09-16 10:09:49.971 4456 WARNING cloudbaseinit.metadata.services.osconfigdrive.windows [-] ISO extraction failed on <Partition: \\?\GLOBALROOT\Device\Harddisk0\Partition2> with WindowsCloudbaseInitException("Cannot open file: 'The process cannot access the file because it is being used by another process.'",): cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot open file: 'The process cannot access the file because it is being used by another process.'
2021-09-16 10:09:49.988 4456 WARNING cloudbaseinit.metadata.services.osconfigdrive.windows [-] ISO extraction failed on <Partition: \\?\GLOBALROOT\Device\Harddisk1\Partition1> with WindowsCloudbaseInitException("Cannot open file: 'The system cannot find the file specified.'",): cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot open file: 'The system cannot find the file specified.'
2021-09-16 10:09:49.988 4456 WARNING cloudbaseinit.metadata.services.osconfigdrive.windows [-] ISO extraction failed on <Partition: \\?\GLOBALROOT\Device\Harddisk1\Partition2> with WindowsCloudbaseInitException("Cannot open file: 'The system cannot find the file specified.'",): cloudbaseinit.exception.WindowsCloudbaseInitException: Cannot open file: 'The system cannot find the file specified.'
2021-09-16 10:09:49.988 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for Config Drive iso in hdd with expected label config-2 get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:218
2021-09-16 10:09:50.004 4456 DEBUG cloudbaseinit.metadata.services.osconfigdrive.windows [-] Looking for Config Drive iso in cdrom with expected label config-2 get_config_drive_files C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\metadata\services\osconfigdrive\windows.py:218
2021-09-16 10:09:50.004 4456 ERROR cloudbaseinit.init [-] No metadata service found: cloudbaseinit.exception.MetadataNotFoundException: No available service found
2021-09-16 10:09:50.004 4456 INFO cloudbaseinit.init [-] Plugins execution done
2021-09-16 10:09:50.004 4456 INFO cloudbaseinit.init [-] Stopping Cloudbase-Init service
2021-09-16 10:09:53.107 4456 DEBUG cloudbaseinit.osutils.windows [-] Stopping service cloudbase-init stop_service C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:1140
```

**Comment by dmoore44** [comment]
Found the issue; I didn't declare a cloud-init cd-rom device in the terraform code.
