### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ortiga88** [Telmate/terraform-provider-proxmox#447]
what worked yesterday does not work today and I have not touched anything

```

Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.vm[0],
│   on linux.tf line 33, in resource "proxmox_vm_qemu" "vm":
│   33: resource "proxmox_vm_qemu" "vm" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs
│ may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.1 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 67 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc00011eeb0, 0xc0003e8c00, 0x5, 0x1, 0x1, 0x0, 0x0, 0xc0001fac00)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211101191122-8bbe30eb7171/proxmox/client.go:191 +0x845
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211101191122-8bbe30eb7171/proxmox/client.go:181
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000544900, 0x17b0da0, 0xc00011ef00, 0x0, 0x0)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:738 +0x18c6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000320460, 0x19f0498, 0xc0003c99c0, 0xc000544900, 0x17b0da0, 0xc00011ef00, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000320460, 0x19f0498, 0xc0003c99c0, 0xc0004760d0, 0xc000545c80, 0x17b0da0, 0xc00011ef00, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000bc078, 0x19f0498, 0xc0003c99c0, 0xc0003f2c30, 0xc0003c99c0, 0x18b84e0, 0xc000437000)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00051f340, 0x19f0540, 0xc0003c99c0, 0xc0001e13b0, 0xc00051f340, 0xc0004370e0, 0xc0005a0ba0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x18b84e0, 0xc00051f340, 0x19f0540, 0xc0004370e0, 0xc00008dc80, 0x0, 0x19f0540, 0xc0004370e0, 0xc00033b500, 0x991)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000240540, 0x19f7ef8, 0xc00029b080, 0xc0004465a0, 0xc000282780, 0x1e2fdc0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000240540, 0x19f7ef8, 0xc00029b080, 0xc0004465a0, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000292030, 0xc000240540, 0x19f7ef8, 0xc00029b080, 0xc0004465a0)
        google.golang.org/grpc@v1.42.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x1fd

Error: The terraform-provider-proxmox_v2.9.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by iamniki01** [comment]
Hi Ortiga, I am curious, that you closed an issue here. But I am facing the same issue and it would be great if you can tell me how did you resolve this issue? Much appreciated if you can explain with your problem
