### ISSUE TITLE
[BUG] provider stoped working suddenly

### ISSUE THREAD

**Issue by baskraai** [Telmate/terraform-provider-proxmox#464]
Deployed machines the day before, and today cannot make changes, add or destroy vm's. Even a regular apply will not working.

# issue
When running a plan any changes or checks go fine. When running the apply the run will crash with the trace in the next section.

# Stack-trace
```
Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.proxmox_vms_****.proxmox_vm_qemu.vms["test-node-1"]: Creating...
module.proxmox_vms_****.proxmox_vm_qemu.vms["test-node-1"]: Still creating... [10s elapsed]

Stack trace from the terraform-provider-proxmox_v2.9.3 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 27 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc0000d31d0, 0xc0000ac8c0, 0x1e, 0x1, 0x1, 0x0, 0x0, 0xc0001a8000)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:190 +0x845
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0002abf00, 0x17c53c0, 0xc0000d3220, 0x8, 0xffffffffffffffff)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:738 +0x1886
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001767e0, 0x1a0b1b8, 0xc0002be200, 0xc0002abf00, 0x17c53c0, 0xc0000d3220, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:329 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001767e0, 0x1a0b1b8, 0xc0002be200, 0xc0001084e0, 0xc0002abd00, 0x17c53c0, 0xc0000d3220, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d2c0, 0x1a0b1b8, 0xc0002be200, 0xc00007dcc0, 0xc0002be200, 0x18d06a0, 0xc000196600)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0007dbae0, 0x1a0b260, 0xc0002be200, 0xc0001551f0, 0xc0007dbae0, 0xc000196660, 0xc0000bfba0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x18d06a0, 0xc0007dbae0, 0x1a0b260, 0xc000196660, 0xc0001a4cc0, 0x0, 0x1a0b260, 0xc000196660, 0xc000491500, 0xa32)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027aa80, 0x1a12c18, 0xc0002a1380, 0xc00011d680, 0xc0000946c0, 0x1e55f40, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00027aa80, 0x1a12c18, 0xc0002a1380, 0xc00011d680, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a0160, 0xc00027aa80, 0x1a12c18, 0xc0002a1380, 0xc00011d680)
        google.golang.org/grpc@v1.42.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x1fd

Error: The terraform-provider-proxmox_v2.9.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│
│   with module.proxmox_vms_*******.proxmox_vm_qemu.vms["test-node-1"],
│   on modules/proxmox/main.tf line 74, in resource "proxmox_vm_qemu" "vms":
│   74: resource "proxmox_vm_qemu" "vms" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```
the `***` are masking a location-name. They are not ment literally.

**Comment by Syntax3rror404** [comment]
Try the 2.8.0 version. All versions after 2.9.0 are crap

**Comment by baskraai** [comment]
@Syntax3rror404 after I got the error on 2.9.3 tried downgrading to 2.8.0 and got the same resold. Shoud have mentioned that. My apologies!

**Comment by Syntax3rror404** [comment]
Can you share your module code?
