### ISSUE TITLE
Stack trace during deploy 

### ISSUE THREAD

**Issue by arcsr** [Telmate/terraform-provider-proxmox#489]
Recived the following stack trace while attempting to spin up a couple of vms on a local proxmox:

terraform apply local.plan
```proxmox_vm_qemu.vms["ubuntu-test-1"]: Creating...
proxmox_vm_qemu.vms["ubuntu-test-2"]: Creating...
proxmox_vm_qemu.vms["ubuntu-test-1"]: Still creating... [10s elapsed]
proxmox_vm_qemu.vms["ubuntu-test-2"]: Still creating... [10s elapsed]
╷
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.vms["ubuntu-test-1"],
│   on proxmox_vms.tf line 2, in resource "proxmox_vm_qemu" "vms":
│    2: resource "proxmox_vm_qemu" "vms" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.vms["ubuntu-test-2"],
│   on proxmox_vms.tf line 2, in resource "proxmox_vm_qemu" "vms":
│    2: resource "proxmox_vm_qemu" "vms" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.4 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 34 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xbf6e45, {0xc000418460, 0xd})
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:190 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000045b00, {0xab4220, 0xc00031c8c0})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:763 +0x1334
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00042e960, {0xcd9d18, 0xc00020ef80}, 0x2, {0xab4220, 0xc00031c8c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000398460, {0xcd9d18, 0xc00020ef80}, 0xc0000ab5f0, 0xc000045980, {0xab4220, 0xc00031c8c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003040c0, {0xcd9d18, 0xc00020ef80}, 0xc000616460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000314780, {0xcd9dc0, 0xc0003d8fc0}, 0xc00061e3f0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xba8f20, 0xc000314780}, {0xcd9dc0, 0xc0003d8fc0}, 0xc00041a8a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032e700, {0xce7150, 0xc0003ee300}, 0xc0002a2120, 0xc0003d8db0, 0x11a4a20, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00032e700, {0xce7150, 0xc0003ee300}, 0xc0002a2120, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x294
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 83 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xbf6e45, {0xc00044c2f0, 0xd})
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:190 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0005cd600, {0xab4220, 0xc00031c8c0})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:763 +0x1334
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0005b6d20, {0xcd9d18, 0xc00011c340}, 0x2, {0xab4220, 0xc00031c8c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000398460, {0xcd9d18, 0xc00011c340}, 0xc0005b2410, 0xc0005cd100, {0xab4220, 0xc00031c8c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003040c0, {0xcd9d18, 0xc00011c340}, 0xc0004261e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000314780, {0xcd9dc0, 0xc0005002a0}, 0xc0002de000)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xba8f20, 0xc000314780}, {0xcd9dc0, 0xc0005002a0}, 0xc00050a2a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032e700, {0xce7150, 0xc0003ee300}, 0xc0003d6000, 0xc0003d8db0, 0x11a4a20, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00032e700, {0xce7150, 0xc0003ee300}, 0xc0003d6000, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x294

Error: The terraform-provider-proxmox_v2.9.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.```

Plan Output
```terraform plan -out local.plan -var-file local.tfvars

Terraform used the selected providers to generate the following execution plan. Resource actions
are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_vm_qemu.vms["ubuntu-test-1"] will be created
  + resource "proxmox_vm_qemu" "vms" {
      + additional_wait           = 0
      + agent                     = 0
      + automatic_reboot          = true
      + balloon                   = 0
      + bios                      = "seabios"
      + boot                      = "c"
      + bootdisk                  = (known after apply)
      + clone_wait                = 0
      + cores                     = 2
      + cpu                       = "host"
      + default_ipv4_address      = (known after apply)
      + define_connection_info    = true
      + force_create              = false
      + full_clone                = true
      + guest_agent_ready_timeout = 100
      + hotplug                   = "network,disk,usb"
      + id                        = (known after apply)
      + iso                       = "ubuntu-20.04.3-live-server-amd64.iso"
      + kvm                       = true
      + memory                    = 512
      + name                      = "ubuntu-test-1"
      + nameserver                = (known after apply)
      + numa                      = false
      + onboot                    = false
      + oncreate                  = true
      + os_type                   = "ubuntu"
      + preprovision              = true
      + qemu_os                   = "l26"
      + reboot_required           = (known after apply)
      + scsihw                    = (known after apply)
      + searchdomain              = (known after apply)
      + sockets                   = 1
      + ssh_host                  = (known after apply)
      + ssh_port                  = (known after apply)
      + tablet                    = true
      + target_node               = "proxtest1"
      + unused_disk               = (known after apply)
      + vcpus                     = 0
      + vlan                      = -1
      + vmid                      = (known after apply)
    }

  # proxmox_vm_qemu.vms["ubuntu-test-2"] will be created
  + resource "proxmox_vm_qemu" "vms" {
      + additional_wait           = 0
      + agent                     = 0
      + automatic_reboot          = true
      + balloon                   = 0
      + bios                      = "seabios"
      + boot                      = "c"
      + bootdisk                  = (known after apply)
      + clone_wait                = 0
      + cores                     = 2
      + cpu                       = "host"
      + default_ipv4_address      = (known after apply)
      + define_connection_info    = true
      + force_create              = false
      + full_clone                = true
      + guest_agent_ready_timeout = 100
      + hotplug                   = "network,disk,usb"
      + id                        = (known after apply)
      + iso                       = "ubuntu-20.04.3-live-server-amd64.iso"
      + kvm                       = true
      + memory                    = 512
      + name                      = "ubuntu-test-2"
      + nameserver                = (known after apply)
      + numa                      = false
      + onboot                    = false
      + oncreate                  = true
      + os_type                   = "ubuntu"
      + preprovision              = true
      + qemu_os                   = "l26"
      + reboot_required           = (known after apply)
      + scsihw                    = (known after apply)
      + searchdomain              = (known after apply)
      + sockets                   = 1
      + ssh_host                  = (known after apply)
      + ssh_port                  = (known after apply)
      + tablet                    = true
      + target_node               = "proxtest1"
      + unused_disk               = (known after apply)
      + vcpus                     = 0
      + vlan                      = -1
      + vmid                      = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

**Comment by alteredtech** [comment]
pm_tls_insecure     = true
  pm_log_enable = true
  pm_log_file   = "terraform-plugin-proxmox.log"
  pm_debug      = true
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }

add this to your providers resource. When I ran into this, I was not connecting to my proxmox server. I had to add an 's' to http. simple typo

**Comment by arcsr** [comment]
lol port was wrong should have checked the basics like connectivity 🤦  lol thanks!
