### ISSUE TITLE
advanced lxc rootfs support

### ISSUE THREAD

**Issue by h0tw1r3** [Telmate/terraform-provider-proxmox#523]
missing advanced option support, some of these are only available through the api.
* acl, quota, replicate, shared, and ro flags
* mountoptions

**Comment by h0tw1r3** [comment]
mountoptions is still needed

**Comment by h0tw1r3** [comment]
mountoptions is still needed

**Comment by h0tw1r3** [comment]
still needed

**Comment by PW999** [comment]
`mountoptions` would be very nice since it prevents me from properly importing existing containers which have mountoptions set.

After importing the container and manually fixing all the holes in the statefile, I'm now greeted with this error
`│ Error: proxmox provider error: proxmox API returned new parameter 'mountoptions' we cannot process`

**Comment by h0tw1r3** [comment]
@PW999  this is open for mountoptions, rootfs support was already merged

**Comment by h0tw1r3** [comment]
still needed

**Comment by h0tw1r3** [comment]
still needed

**Comment by h0tw1r3** [comment]
*still* needed

**Comment by s0nik42** [comment]
Hi @h0tw1r3 would be great if you could test it

**Comment by tonyallard** [comment]
Hi @s0nik42, thanks for the work on the mountoptions feature. I am in need of this. I have cloned your repo, built, and tried testing, but am new to terraform. I think I have set it up correctly with dev_overrides. However it is having trouble interpreting the mountoptions feature:
```
2025-05-31T10:53:12.481Z [INFO]  Terraform version: 1.12.1
2025-05-31T10:53:12.481Z [DEBUG] using github.com/hashicorp/go-tfe v1.74.1
2025-05-31T10:53:12.481Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.23.1-0.20250203194505-ba0759438da2
2025-05-31T10:53:12.481Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2025-05-31T10:53:12.481Z [DEBUG] using github.com/zclconf/go-cty v1.16.2
2025-05-31T10:53:12.481Z [INFO]  Go runtime version: go1.24.2
2025-05-31T10:53:12.481Z [INFO]  CLI args: []string{"terraform", "plan"}
2025-05-31T10:53:12.481Z [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2025-05-31T10:53:12.481Z [INFO]  Loading CLI configuration from /root/.terraformrc
2025-05-31T10:53:12.481Z [DEBUG] checking for credentials in "/root/.terraform.d/plugins"
2025-05-31T10:53:12.481Z [DEBUG] Explicit provider installation configuration is set
2025-05-31T10:53:12.482Z [INFO]  CLI command args: []string{"plan"}
2025-05-31T10:53:12.483Z [DEBUG] Provider registry.terraform.io/telmate/proxmox is overridden by dev_overrides
2025-05-31T10:53:12.483Z [DEBUG] Provider registry.terraform.io/telmate/proxmox is overridden to load from /root/.terraform.d/plugins/terraform-provider-proxmox
2025-05-31T10:53:12.483Z [DEBUG] checking for provisioner in "."
2025-05-31T10:53:12.487Z [DEBUG] checking for provisioner in "/usr/bin"
2025-05-31T10:53:12.487Z [DEBUG] checking for provisioner in "/root/.terraform.d/plugins"
2025-05-31T10:53:12.487Z [DEBUG] Provider registry.terraform.io/telmate/proxmox is overridden by dev_overrides
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - telmate/proxmox in /root/.terraform.d/plugins/terraform-provider-proxmox
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
2025-05-31T10:53:12.490Z [INFO]  backend/local: starting Plan operation
2025-05-31T10:53:12.491Z [DEBUG] Config.VerifyDependencySelections: skipping registry.terraform.io/telmate/proxmox because it's overridden by a special configuration setting
2025-05-31T10:53:12.491Z [DEBUG] created provider logger: level=debug
2025-05-31T10:53:12.491Z [INFO]  provider: configuring client automatic mTLS
2025-05-31T10:53:12.504Z [DEBUG] provider: starting plugin: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox args=["/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox"]
2025-05-31T10:53:12.504Z [DEBUG] provider: plugin started: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox pid=6663
2025-05-31T10:53:12.504Z [DEBUG] provider: waiting for RPC address: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox
2025-05-31T10:53:12.509Z [INFO]  provider.terraform-provider-proxmox: configuring server automatic mTLS: timestamp=2025-05-31T10:53:12.509Z
2025-05-31T10:53:12.524Z [DEBUG] provider.terraform-provider-proxmox: plugin address: address=/tmp/plugin968491320 network=unix timestamp=2025-05-31T10:53:12.524Z
2025-05-31T10:53:12.524Z [DEBUG] provider: using plugin: version=5
2025-05-31T10:53:12.558Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-05-31T10:53:12.560Z [INFO]  provider: plugin process exited: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox id=6663
2025-05-31T10:53:12.560Z [DEBUG] provider: plugin exited
2025-05-31T10:53:12.560Z [DEBUG] Building and walking validate graph
2025-05-31T10:53:12.560Z [DEBUG] ProviderTransformer: "proxmox_lxc.ubuntu_container" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/telmate/proxmox"]
2025-05-31T10:53:12.560Z [DEBUG] ReferenceTransformer: "proxmox_lxc.ubuntu_container" references: []
2025-05-31T10:53:12.560Z [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/telmate/proxmox\"]" references: []
2025-05-31T10:53:12.560Z [DEBUG] Starting graph walk: walkValidate
2025-05-31T10:53:12.561Z [DEBUG] created provider logger: level=debug
2025-05-31T10:53:12.561Z [INFO]  provider: configuring client automatic mTLS
2025-05-31T10:53:12.566Z [DEBUG] provider: starting plugin: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox args=["/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox"]
2025-05-31T10:53:12.566Z [DEBUG] provider: plugin started: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox pid=6668
2025-05-31T10:53:12.566Z [DEBUG] provider: waiting for RPC address: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox
2025-05-31T10:53:12.571Z [INFO]  provider.terraform-provider-proxmox: configuring server automatic mTLS: timestamp=2025-05-31T10:53:12.571Z
2025-05-31T10:53:12.586Z [DEBUG] provider: using plugin: version=5
2025-05-31T10:53:12.587Z [DEBUG] provider.terraform-provider-proxmox: plugin address: address=/tmp/plugin2650485063 network=unix timestamp=2025-05-31T10:53:12.586Z
2025-05-31T10:53:12.601Z [ERROR] vertex "proxmox_lxc.ubuntu_container" error: Unsupported argument
╷
│ Error: Unsupported argument
│ 
│   on ubuntu-server.tf line 44, in resource "proxmox_lxc" "ubuntu_container":
│   44:     mountoptions = {
│ 
│ An argument named "mountoptions" is not expected here.
╵
2025-05-31T10:53:12.603Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-05-31T10:53:12.604Z [INFO]  provider: plugin process exited: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox id=6668
2025-05-31T10:53:12.604Z [DEBUG] provider: plugin exited
```

**Comment by Optimised** [comment]
Hi @s0nik42, thanks for the work on the mountoptions feature. I am in need of this. I have cloned your repo, built, and tried testing, but am new to terraform. I think I have set it up correctly with dev_overrides. However it is having trouble interpreting the mountoptions feature:
```
2025-05-31T10:53:12.481Z [INFO]  Terraform version: 1.12.1
2025-05-31T10:53:12.481Z [DEBUG] using github.com/hashicorp/go-tfe v1.74.1
2025-05-31T10:53:12.481Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.23.1-0.20250203194505-ba0759438da2
2025-05-31T10:53:12.481Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2025-05-31T10:53:12.481Z [DEBUG] using github.com/zclconf/go-cty v1.16.2
2025-05-31T10:53:12.481Z [INFO]  Go runtime version: go1.24.2
2025-05-31T10:53:12.481Z [INFO]  CLI args: []string{"terraform", "plan"}
2025-05-31T10:53:12.481Z [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2025-05-31T10:53:12.481Z [INFO]  Loading CLI configuration from /root/.terraformrc
2025-05-31T10:53:12.481Z [DEBUG] checking for credentials in "/root/.terraform.d/plugins"
2025-05-31T10:53:12.481Z [DEBUG] Explicit provider installation configuration is set
2025-05-31T10:53:12.482Z [INFO]  CLI command args: []string{"plan"}
2025-05-31T10:53:12.483Z [DEBUG] Provider registry.terraform.io/telmate/proxmox is overridden by dev_overrides
2025-05-31T10:53:12.483Z [DEBUG] Provider registry.terraform.io/telmate/proxmox is overridden to load from /root/.terraform.d/plugins/terraform-provider-proxmox
2025-05-31T10:53:12.483Z [DEBUG] checking for provisioner in "."
2025-05-31T10:53:12.487Z [DEBUG] checking for provisioner in "/usr/bin"
2025-05-31T10:53:12.487Z [DEBUG] checking for provisioner in "/root/.terraform.d/plugins"
2025-05-31T10:53:12.487Z [DEBUG] Provider registry.terraform.io/telmate/proxmox is overridden by dev_overrides
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - telmate/proxmox in /root/.terraform.d/plugins/terraform-provider-proxmox
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
2025-05-31T10:53:12.490Z [INFO]  backend/local: starting Plan operation
2025-05-31T10:53:12.491Z [DEBUG] Config.VerifyDependencySelections: skipping registry.terraform.io/telmate/proxmox because it's overridden by a special configuration setting
2025-05-31T10:53:12.491Z [DEBUG] created provider logger: level=debug
2025-05-31T10:53:12.491Z [INFO]  provider: configuring client automatic mTLS
2025-05-31T10:53:12.504Z [DEBUG] provider: starting plugin: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox args=["/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox"]
2025-05-31T10:53:12.504Z [DEBUG] provider: plugin started: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox pid=6663
2025-05-31T10:53:12.504Z [DEBUG] provider: waiting for RPC address: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox
2025-05-31T10:53:12.509Z [INFO]  provider.terraform-provider-proxmox: configuring server automatic mTLS: timestamp=2025-05-31T10:53:12.509Z
2025-05-31T10:53:12.524Z [DEBUG] provider.terraform-provider-proxmox: plugin address: address=/tmp/plugin968491320 network=unix timestamp=2025-05-31T10:53:12.524Z
2025-05-31T10:53:12.524Z [DEBUG] provider: using plugin: version=5
2025-05-31T10:53:12.558Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-05-31T10:53:12.560Z [INFO]  provider: plugin process exited: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox id=6663
2025-05-31T10:53:12.560Z [DEBUG] provider: plugin exited
2025-05-31T10:53:12.560Z [DEBUG] Building and walking validate graph
2025-05-31T10:53:12.560Z [DEBUG] ProviderTransformer: "proxmox_lxc.ubuntu_container" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/telmate/proxmox"]
2025-05-31T10:53:12.560Z [DEBUG] ReferenceTransformer: "proxmox_lxc.ubuntu_container" references: []
2025-05-31T10:53:12.560Z [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/telmate/proxmox\"]" references: []
2025-05-31T10:53:12.560Z [DEBUG] Starting graph walk: walkValidate
2025-05-31T10:53:12.561Z [DEBUG] created provider logger: level=debug
2025-05-31T10:53:12.561Z [INFO]  provider: configuring client automatic mTLS
2025-05-31T10:53:12.566Z [DEBUG] provider: starting plugin: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox args=["/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox"]
2025-05-31T10:53:12.566Z [DEBUG] provider: plugin started: path=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox pid=6668
2025-05-31T10:53:12.566Z [DEBUG] provider: waiting for RPC address: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox
2025-05-31T10:53:12.571Z [INFO]  provider.terraform-provider-proxmox: configuring server automatic mTLS: timestamp=2025-05-31T10:53:12.571Z
2025-05-31T10:53:12.586Z [DEBUG] provider: using plugin: version=5
2025-05-31T10:53:12.587Z [DEBUG] provider.terraform-provider-proxmox: plugin address: address=/tmp/plugin2650485063 network=unix timestamp=2025-05-31T10:53:12.586Z
2025-05-31T10:53:12.601Z [ERROR] vertex "proxmox_lxc.ubuntu_container" error: Unsupported argument
╷
│ Error: Unsupported argument
│ 
│   on ubuntu-server.tf line 44, in resource "proxmox_lxc" "ubuntu_container":
│   44:     mountoptions = {
│ 
│ An argument named "mountoptions" is not expected here.
╵
2025-05-31T10:53:12.603Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-05-31T10:53:12.604Z [INFO]  provider: plugin process exited: plugin=/root/.terraform.d/plugins/terraform-provider-proxmox/terraform-provider-proxmox id=6668
2025-05-31T10:53:12.604Z [DEBUG] provider: plugin exited
```

**Comment by s0nik42** [comment]
Hi, this is how we use it :

```
resource "proxmox_lxc" "ct" {
  dynamic "mountpoint" {
    for_each = var.configuration.additionnal_disks
    content {
      [...]
      mountoptions  = mountpoint.value.mountoptions
    }
  }
```

```
variable "configuration" {
  type = object({
    [...]
    additionnal_disks   = optional(list(object({
      [...]
      mountoptions      = optional(map(bool))
    })), [])

  })
}
```

**Comment by philou511** [comment]
Hello,

Did someone managed to create a container with mountoptions ?

I cloned @s0nik42's repo (branch lxc-mountoptions), compiled the provider and used it in my "required_providers".

I added mountoptions in the "type = object" part and in the for_each part as indicated above but no success...

│ Error: Unsupported argument
│  136:       mountoptions = mountpoint.value.mountoptions
│ An argument named "mountoptions" is not expected here.

Thank you :)

**Comment by Tinyblargon** [comment]
@philou511 The new `proxmox_lxc_guest` does support mount points. Please keep in mind that this resource isn't fully finalized yet and could be subject to breaking changes in following RC releases.

https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs%2Fresources%2Flxc_guest.md

**Comment by philou511** [comment]
I don't understand how to use the mounts argument : I tried this but "terraform plan" complains about "data"
  mounts {
    data {
      guest_path="/var"
      storage = "my-storage"
      size = "1G"
    }
  }

**Comment by Tinyblargon** [comment]
@philou511 If i remember correctly `data` is nested in a `mpX` item where `X` is the number of the mountpoint:

```hcl
mounts {
mp0 {
data {
guest_path="/var"
storage = "my-storage"
size = "1G"
}
}
}
```

**Comment by philou511** [comment]
OK thank you, I'll try.

And for mount, this is crashing when I "terraform apply" :
  mount {
    slot = "0"
    guest_path = "/var"
    storage = "my-storage"
    size = "1G"
    option_no_device = true
    option_no_suid = true
    option_no_exec = true
  }

Here is the stack trace :

```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

Stack trace from the terraform-provider-proxmox_v3.0.2-rc07 plugin:

panic: runtime error: slice bounds out of range [2:1]

goroutine 71 [running]:
github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/lxc/mounts.sdkMount(0x0, {0xc0013c44f0, 0x1, 0x0?})
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/lxc/mounts/sdk_mount.go:18 +0x1f4f
github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/lxc/mounts.SDK(0x0, 0xc0002878c0)
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/Internal/resource/guest/lxc/mounts/sdk.go:12 +0xcc
github.com/Telmate/terraform-provider-proxmox/v2/proxmox.lxcSDK(0x0, _)
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_lxc_guest.go:334 +0x40c
github.com/Telmate/terraform-provider-proxmox/v2/proxmox.resourceLxcGuestCreate({0x1094218, 0xc000281030}, 0xc0002878c0, {0xd75220?, 0xc00092f0e0})
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_lxc_guest.go:100 +0x1a8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0007af600, {0x1094170, 0xc000a46ea0}, 0xc0002878c0, {0xd75220, 0xc00092f0e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:849 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007af600, {0x1094170, 0xc000a46ea0}, 0xc000a74c30, 0xc0002877a0, {0xd75220, 0xc00092f0e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:980 +0xb47
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000360408, {0x1094170?, 0xc000a46de0?}, 0xc000b6e410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/grpc_provider.go:1484 +0x1085
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001fe000, {0x1094170?, 0xc000a461e0?}, 0xc000258480)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/tf5server/server.go:941 +0x3b9
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xf05720, 0xc0001fe000}, {0x1094170, 0xc000a461e0}, 0xc000258200, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:687 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000264000, {0x1094170, 0xc000a42540}, 0xc0009b20c0, 0xc000557e00, 0x1737fc8, 0x0)
        google.golang.org/grpc@v1.72.1/server.go:1405 +0x1036
google.golang.org/grpc.(*Server).handleStream(0xc000264000, {0x1094b50, 0xc0007be1a0}, 0xc0009b20c0)
        google.golang.org/grpc@v1.72.1/server.go:1815 +0xb88
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.72.1/server.go:1035 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 28
        google.golang.org/grpc@v1.72.1/server.go:1046 +0x11d

Error: The terraform-provider-proxmox_v3.0.2-rc07 plugin crashed!
```

**Comment by Tinyblargon** [comment]
@philou511 could you prefix the `slot` number with `mp` I remember seeing a ticket for this panic.

**Comment by philou511** [comment]
@Tinyblargon great, thanks a lot ;both are ok (mount and mounts, separately as indicated in the doc)

**Comment by s0nik42** [comment]
Hey, 
moving to 3.0.2-rc07, the root_mount options can be set on proxmox, but doesn't seem to be supported by the provider :  

```
│   on ../../../terraform/modules/proxmox/proxmox_ct/main.tf line 74, in resource "proxmox_lxc_guest" "ct":
│   74:     option_no_atime   = var.configuration.option_no_atime
│
│ An argument named "option_no_atime" is not expected here.
```

```
  root_mount {
    storage           = disk3
    size              = "10G"
    replicate         = true
    option_lazy_time  = true
    option_no_atime   = true
  }
```
