### ISSUE TITLE
Plugin crashed after refresh

### ISSUE THREAD

**Issue by yarcod** [Telmate/terraform-provider-proxmox#539]
Just getting into Terraform and trying to use it on my homelab. I am trying to set up containers and VMs using modules, one module for each type. While doing the mistake of removing a terraform-spawned container manually, via the GUI, I tried getting the local terraform state up to date again with a `terraform plan --refresh-only`. Running this crashed the plugin, with the following error:

```
local_file.ansible_inventory: Refreshing state... [id=8d1f625241c6cc82f546ddb0c0d1674095bd7a3a]
module.media.proxmox_lxc.test_ct: Refreshing state... [id=proxmox/lxc/100]
╷
│ Error: Request cancelled
│
│   with module.media.proxmox_lxc.test_ct,
│   on modules/proxmox-container/main.tf line 10, in resource "proxmox_lxc" "test_ct":
│   10: resource "proxmox_lxc" "test_ct" {
│
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-proxmox_v2.9.6 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 52 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmInfo(0xc0002621d0, 0xc00010f758)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220129131641-6909b62b8cf0/proxmox/client.go:159 +0x435
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceLxcRead(0xc00030f180, {0xab5260, 0xc0005a4b40})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:672 +0x210
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceLxcRead(0x68, {0xab5260, 0xc0005a4b40})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:658 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xbd3c2a, {0xcdb0d8, 0xc000047cc0}, 0x24, {0xab5260, 0xc0005a4b40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003a89a0, {0xcdb0d8, 0xc000047cc0}, 0xc0004b7d40, {0xab5260, 0xc0005a4b40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000148078, {0xcdb0d8, 0xc000047cc0}, 0xc000047d40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000152680, {0xcdb180, 0xc0002502a0}, 0xc0004eee40)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xba9f80, 0xc000152680}, {0xcdb180, 0xc0002502a0}, 0xc0004eede0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013c700, {0xce8510, 0xc0004f8000}, 0xc00024a5a0, 0xc0003f6ab0, 0x11a69f0, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00013c700, {0xce8510, 0xc0004f8000}, 0xc00024a5a0, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x294

Error: The terraform-provider-proxmox_v2.9.6 plugin crashed!
```

**Comment by mizhka** [comment]
Release notes of 2.9.7 contains items about LXC. It may be worth to try latest version (2.9.8)

**Comment by mleone87** [comment]
could be a permission issue, please provide provider configuration and users on proxmox side

**Comment by yarcod** [comment]
Since I hadn't come very far in my Terraforming, I decided to remove the whole tf state and start over. As such, this issue should perhaps be closed of no one else can reproduce it.
