### ISSUE TITLE
v2.9.9 crash

### ISSUE THREAD

**Issue by ryanseipp** [Telmate/terraform-provider-proxmox#543]
Stack trace:
```
Stack trace from the terraform-provider-proxmox_v2.9.9 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 40 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc1cfbb, {0xc0004e8a60, 0x7})
	github.com/Telmate/proxmox-api-go@v0.0.0-20220419083039-768690daeef0/proxmox/client.go:190 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
	github.com/Telmate/proxmox-api-go@v0.0.0-20220419083039-768690daeef0/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000049480, {0xad5bc0, 0xc00028af00})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd055e0, {0xd055e0, 0xc00032b200}, 0xd, {0xad5bc0, 0xc00028af00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00038e700, {0xd055e0, 0xc00032b200}, 0xc0000e3ad0, 0xc000049300, {0xad5bc0, 0xc00028af00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d170, {0xd05538, 0xc0001a9dc0}, 0xc000809e50)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000380140, {0xd055e0, 0xc00032aa20}, 0xc000368770)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbcd9e0, 0xc000380140}, {0xd055e0, 0xc00032aa20}, 0xc0000ac900, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000122700, {0xd12aa0, 0xc00040a1a0}, 0xc00022c6c0, 0xc0003acc60, 0x11e8c60, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000122700, {0xd12aa0, 0xc00040a1a0}, 0xc00022c6c0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-proxmox_v2.9.9 plugin crashed!
```
Would be happy to provide more info upon request

**Comment by ryanseipp** [comment]
This ended up being user error. I set `pm_api_url` incorrectly. Perhaps an error message could be included if a connection could not be made to the proxmox host. But closing since the issue is resolved.
