### ISSUE TITLE
>2.9.9 Plugin Crashes on VM resource creation

### ISSUE THREAD

**Issue by FullofQuarks** [Telmate/terraform-provider-proxmox#547]
Recently upgraded to Proxmox version 7.1-12. Terraform (v1.1.9) gives me the following error on creating many resources of type "proxmox_vm_qemu":

```
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.nodes["k8sw4"],
│   on create-nodes.tf line 1, in resource "proxmox_vm_qemu" "nodes":
│    1: resource "proxmox_vm_qemu" "nodes" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

Stack trace from the terraform-provider-proxmox_v2.9.9 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 52 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc1cfbb, {0xc00025bb20, 0x5})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220419083039-768690daeef0/proxmox/client.go:190 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220419083039-768690daeef0/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000333700, {0xad5bc0, 0xc0003b1d10})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd055e0, {0xd055e0, 0xc0002dc420}, 0xd, {0xad5bc0, 0xc0003b1d10})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000e0e00, {0xd055e0, 0xc0002dc420}, 0xc00007cf70, 0xc000333580, {0xad5bc0, 0xc0003b1d10})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000262390, {0xd05538, 0xc00040cd00}, 0xc000078410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00016b9a0, {0xd055e0, 0xc0002678c0}, 0xc0000d6a80)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbcd9e0, 0xc00016b9a0}, {0xd055e0, 0xc0002678c0}, 0xc000297140, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fec40, {0xd12aa0, 0xc00026f860}, 0xc0003e7320, 0xc000266ea0, 0x11e8c60, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001fec40, {0xd12aa0, 0xc00026f860}, 0xc0003e7320, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-proxmox_v2.9.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by FullofQuarks** [comment]
This issue gives the same error result with version 2.9.10

**Comment by clbx** [comment]
Issue persists with 2.9.10
```
❯ terraform version
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/telmate/proxmox v2.9.10
```

```
> pveversion
pve-manager/7.1-7/df5740ad (running kernel: 5.13.19-2-pve)
```

**Comment by FullofQuarks** [comment]
`pm_api_url` is correct, but this still ended up being user error! I forgot to regenerate the API token 🙄.

The error message could be more descriptive. In this case, the provider could communicate with the API, but it wasn't authorized.

I'm still not able to create VMs, but at least the plugin isn't crashing at this point. I'll close this issue and open another if I need to.
