### ISSUE TITLE
terraform-provider-proxmox_v2.9.10 panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by pdavies91** [Telmate/terraform-provider-proxmox#574]
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.10 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 37 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000312780, {0xae93c0, 0xc00007a050})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1503 +0x21dd
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(...)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1305
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000312780, {0xae93c0, 0xc00007a050})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:987 +0x2312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd1df00, {0xd1df00, 0xc00035e9f0}, 0xd, {0xae93c0, 0xc00007a050})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003de700, {0xd1df00, 0xc00035e9f0}, 0xc00037edd0, 0xc000312d00, {0xae93c0, 0xc00007a050})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000c9128, {0xd1de58, 0xc00051e640}, 0xc0004ae780)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000f8320, {0xd1df00, 0xc00035e1e0}, 0xc000508000)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbe2c80, 0xc0000f8320}, {0xd1df00, 0xc00035e1e0}, 0xc00055c2a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000bc700, {0xd2b6c0, 0xc000083ba0}, 0xc000364000, 0xc0003fcc00, 0x120cfa0, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0000bc700, {0xd2b6c0, 0xc000083ba0}, 0xc000364000, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by pdavies91** [comment]
After adding debug logging and seeing this in the log; 
HTTP/1.1 403 Permission check failed (/, Sys.Audit)
removed some OLD groups and pools and it works fine ....
