### ISSUE TITLE
terraform crash when one of the vm has a disk passtrough

### ISSUE THREAD

**Issue by zaregata** [Telmate/terraform-provider-proxmox#581]
when doing any action (terraform plan, apply, destroy) when one of the vm managed by terraform has a disk passtrough (the exact command used : qm set VMID --scsi1 /dev/disk/by-id/XXX,iothread=1,backup=0,replicate=0), terraform crash

I'm using terraform 1.2.4 with the provider 2.9.10 on archlinux

here's the crash message:

```
 |
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on main.tf line 7, in terraform:
│    7:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: Plugin did not respond
│
│   with module.servers["fileserver"].proxmox_vm_qemu.moduleVM[0],
│   on modules/template_vm/main.tf line 10, in resource "proxmox_vm_qemu" "moduleVM":
│   10: resource "proxmox_vm_qemu" "moduleVM" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.servers["apphost"].proxmox_vm_qemu.moduleVM[0],
│   on modules/template_vm/main.tf line 10, in resource "proxmox_vm_qemu" "moduleVM":
│   10: resource "proxmox_vm_qemu" "moduleVM" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.servers["drawbridge"].proxmox_vm_qemu.moduleVM[0],
│   on modules/template_vm/main.tf line 10, in resource "proxmox_vm_qemu" "moduleVM":
│   10: resource "proxmox_vm_qemu" "moduleVM" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.10 plugin:

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 39 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetStorageStatus(0xb5e980, 0xc000777210, {0x0, 0x0})
	github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:271 +0x20a
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000777210, 0xc000777210)
	github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/config_qemu.go:772 +0x25ea
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc00019d100, {0xae93c0, 0xc00049ceb0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1333 +0x39e
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x68, {0xae93c0, 0xc00049ceb0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1305 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xd1df00, {0xd1df00, 0xc0007929f0}, 0xd, {0xae93c0, 0xc00049ceb0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003bc700, {0xd1df00, 0xc0007929f0}, 0xc000123930, {0xae93c0, 0xc00049ceb0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d158, {0xd1de58, 0xc0004be280}, 0xc0004be340)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:613 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000d6320, {0xd1df00, 0xc000792210}, 0xc00059c360)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xbe2c80, 0xc0000d6320}, {0xd1df00, 0xc000792210}, 0xc00059c300, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a2700, {0xd2b6c0, 0xc000378000}, 0xc0002ce000, 0xc0003d8ae0, 0x120cf70, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0000a2700, {0xd2b6c0, 0xc000378000}, 0xc0002ce000, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I'd be happy to give any other information

**Comment by minpet** [comment]
any update on this? I'm getting the exact same thing, and cannot move the infrastructure to terraform because of this

**Comment by brutesque** [comment]
https://github.com/Telmate/terraform-provider-proxmox/issues/483
