### ISSUE TITLE
v2.9.10 crash with proxmox v7.2-3

### ISSUE THREAD

**Issue by andrewg-xyz** [Telmate/terraform-provider-proxmox#584]
The plugin crashes after the VM is created and started (as verified by looking in proxmox UI). I'm using a simple config to create a single VM, using a cloud init template. It appears the cloud init config is applied, except the ipconfig0. Resulting in the stack trace.

I've confirmed this behavior with two instance of terraform configuration, I've been able to previously use.

```
╷
│ Error: Request cancelled
│
│   with proxmox_vm_qemu.virtualmachine,
│   on main.tf line 14, in resource "proxmox_vm_qemu" "virtualmachine":
│   14: resource "proxmox_vm_qemu" "virtualmachine" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-proxmox_v2.9.10 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 67 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.initConnInfo(0xc000332fa0, 0xc0005daa10, 0x180ea17, 0x5, 0xc00028ec98, 0x0)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1786 +0x1025
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000096780, {0x16e8c60, 0xc0003331d0})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:973 +0x2245
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x191e7a0, {0x191e7a0, 0xc0004e09f0}, 0xd, {0x16e8c60, 0xc0003331d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00018ae00, {0x191e7a0, 0xc0004e09f0}, 0xc0000ae340, 0xc000096580, {0x16e8c60, 0xc0003331d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003cc510, {0x191e6f8, 0xc00042d640}, 0xc000333bd0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001f5d60, {0x191e7a0, 0xc0004e0210}, 0xc00001cd90)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x17e3840, 0xc0001f5d60}, {0x191e7a0, 0xc0004e0210}, 0xc0003015c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002cc8c0, {0x192bf00, 0xc000001380}, 0xc000375680, 0xc0003d8ba0, 0x1e120c0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0002cc8c0, {0x192bf00, 0xc000001380}, 0xc000375680, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!
```
main.tf
```
terraform {
  required_version = ">= 0.14"
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
    }
  }
}

provider "proxmox" {
  pm_tls_insecure = true
  # setting PM_API_URL, PM_API_TOKEN_ID, PM_API_TOKEN_SECRET as environment variables
}

resource "proxmox_vm_qemu" "virtualmachine" {
  name        = var.name
  target_node = var.target_node
  ipconfig0   = "ip=${var.vm_ip}/24,gw=${var.vm_gw}"
  agent       = var.qemu_agent
  clone       = var.clone_template
  full_clone  = false
  memory      = var.memory
  cores       = var.cores
  os_type     = var.os_type
  sshkeys     = var.ssh_key_public
  ciuser      = var.ssh_user
  cipassword  = var.user_secret

  disk {
    type    = var.disk_type
    storage = var.storage_pool
    size    = var.disk_size
  }
}
```

**Comment by andrewsgreene** [comment]
I'm not yet convinced there isn't some underlying issue with the cloud init template. However, can the error reported from the `terraform apply` not provide more usable information?
