### ISSUE TITLE
Provider crashes on terraform plan if direct disk path configured

### ISSUE THREAD

**Issue by yoshikakbudto** [Telmate/terraform-provider-proxmox#609]
Tested with 2.9.10, 2.9.11 versions
After VM created i manually edit the VM config to add disk directly by its path, like this
```
# qm set 107 -scsi1 /dev/disk/by-id/ata-ST4000NM0035-1V4107_ZC151JBR

# grep scsi1 /etc/pve/qemu-server/107.conf

scsi1: ata-ST4000NM0035-1V4107_ZC151JBR,size=3907018584K
```

after that, i'v ran terraform plan and the plugin crashes with this stack:
```
Stack trace from the terraform-provider-proxmox_v2.9.11.exe plugin:

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 67 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetStorageStatus(0xf22660?, 0xc00033d130, {0x0, 0x0})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220818102740-0129fa923095/proxmox/client.go:286 +0x1fe
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc00033d130, 0xc00033d130?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220818102740-0129fa923095/proxmox/config_qemu.go:788 +0x26ca
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc0004d8300, {0xeaafa0?, 0xc000074050})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1388 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0xeaafa0?, 0xc000074050?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1359 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1106eb0?, {0x1106eb0?, 0xc0004c80c0?}, 0xd?, {0xeaafa0?, 0xc000074050?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000164e00, {0x1106eb0, 0xc0004c80c0}, 0xc000160000, {0xeaafa0, 0xc000074050})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002fe6c0, {0x1106eb0?, 0xc0004bff80?}, 0xc0001fa0c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001c7d60, {0x1106eb0?, 0xc0004bf770?}, 0xc00042a300)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xfa90a0?, 0xc0001c7d60}, {0x1106eb0, 0xc0004bf770}, 0xc000439e30, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0x1109928, 0xc0003b1040}, 0xc0002b5b00, 0xc00021d230, 0x1595af0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0x1109928, 0xc0003b1040}, 0xc0002b5b00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
```

**Comment by brutesque** [comment]
Same here.

**Comment by brutesque** [comment]
https://github.com/Telmate/terraform-provider-proxmox/issues/483
