### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by exotime** [Telmate/terraform-provider-proxmox#636]
Just pasting the output as requested by the error message. Anecdotally seems to work from local, but not from a gitlab-runner using Docker. Both report to be v2.9.6.

Hope this helps!

```
Terraform has been successfully initialized!
proxmox_vm_qemu.virtual_machines["win10x64"]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.virtual_machines["win10x64"],
│   on main.tf line 15, in resource "proxmox_vm_qemu" "virtual_machines":
│   15: resource "proxmox_vm_qemu" "virtual_machines" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-proxmox_v2.9.6 plugin:
panic: interface conversion: interface {} is nil, not []interface {}
goroutine 27 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xbf7f6e, {0xc000458378, 0x13})
	github.com/Telmate/proxmox-api-go@v0.0.0-20220129131641-6909b62b8cf0/proxmox/client.go:190 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
	github.com/Telmate/proxmox-api-go@v0.0.0-20220129131641-6909b62b8cf0/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000ae200, {0xab5260, 0xc00049cb90})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00056fe90, {0xcdb0d8, 0xc000561740}, 0x2, {0xab5260, 0xc00049cb90})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000396540, {0xcdb0d8, 0xc000561740}, 0xc000316340, 0xc0000ae480, {0xab5260, 0xc00049cb90})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000308090, {0xcdb0d8, 0xc000561740}, 0xc0000c9040)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000314700, {0xcdb180, 0xc0000114a0}, 0xc0004681c0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xba9f80, 0xc000314700}, {0xcdb180, 0xc0000114a0}, 0xc0000b10e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032a700, {0xce8510, 0xc0003ec300}, 0xc0000e2360, 0xc0003e4ab0, 0x11a6a20, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00032a700, {0xce8510, 0xc0003ec300}, 0xc0000e2360, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.42.0/server.go:919 +0x294
Error: The terraform-provider-proxmox_v2.9.6 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

```
resource "proxmox_vm_qemu" "virtual_machines" {
  for_each = var.virtual_machines
  name        = each.value.hostname
  target_node = each.value.target_node
  clone       = each.value.vm_template
  cores       = each.value.cpu_cores
  sockets     = each.value.cpu_sockets
  memory      = each.value.memory
  agent       = 1
  boot        = "order=virtio0"
  os_type     = "cloud-init"
  cpu         = "kvm64"
  scsihw      = "virtio-scsi-pci"
  bootdisk    = "virtio0"
  pool        = "terraform"
  full_clone  = "false"
  qemu_os     = "win10"
  desc        = "Windows 10 x64 Test"

  disk {
    slot     = 0
    size     = each.value.hdd_size
    storage  = each.value.storage
    type     = "virtio"
    iothread = 1
    backup   = 0
    discard  = "on"
    cache    = "unsafe"
  }

  timeouts {
    create = "10m"
  }

  network {
    model    = "virtio"
    bridge   = "vmbr0"
    tag      = each.value.vlan_tag
    firewall = "true"
  }

  lifecycle {
    ignore_changes = [
      network,
      balloon,
      vcpus,
      vga,
      desc,
      bootdisk,
      pool
    ]
  }
}
```

Snippet from vars.tf
```
  default = {
    "win10x64" = {
      hostname    = "win10x64"
      vlan_tag    = 2,
      target_node = "node001",
      storage     = "diskpool",
      cpu_cores   = 4,
      cpu_sockets = 1,
      memory      = "8192",
      hdd_size    = "64G",
      vm_template = "win10x64-template",
      vmid        = 0,
    }
  }
```

**Comment by exotime** [comment]
Apologies for the noise, I noticed I was a few minor releases behind. An upgrade to 2.9.11 shows a human-readable error:

```
Terraform has been successfully initialized!
proxmox_vm_qemu.virtual_machines["win10x64"]: Creating...
╷
│ Error: Get "https://node001:8006/api2/json/cluster/nextid": dial tcp node001:8006: connect: connection refused
│ 
│   with proxmox_vm_qemu.virtual_machines["win10x64"],
│   on main.tf line 15, in resource "proxmox_vm_qemu" "virtual_machines":
│   15: resource "proxmox_vm_qemu" "virtual_machines" {
│ 
╵
Cleaning up project directory and file based variables
```

Hopefully this at least helps someone else?
