### ISSUE TITLE
LXC cannot be created due to error in provider panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by guzmalito** [Telmate/terraform-provider-proxmox#644]
After trying to execute a terraform template, the provider (v2.9.11) seems to not work after 5 min. Also, until I defined the vmid of the LXC container I didn't manage to see this stack error:

│ Error: Plugin did not respond
│
│   with proxmox_lxc.nginx-reverse-proxy,
│   on main.tf line 21, in resource "proxmox_lxc" "nginx-reverse-proxy":
│   21: resource "proxmox_lxc" "nginx-reverse-proxy" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.11 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6fb6f1]

goroutine 55 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).CreateLxcContainer(0xc00033aeb0, {0xc000594780, 0x5}, 0x4?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20220818102740-0129fa923095/proxmox/client.go:596 +0x1b1
github.com/Telmate/proxmox-api-go/proxmox.ConfigLxc.CreateLxc({{0xc000038a80, 0x34}, {0xc000594568, 0x5}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0xc000594595, ...}, ...}, ...)
	github.com/Telmate/proxmox-api-go@v0.0.0-20220818102740-0129fa923095/proxmox/config_lxc.go:341 +0x15f
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceLxcCreate(0x0?, {0xb2bec0?, 0xc00033af00?})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:596 +0x14e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd847f0?, {0xd847f0?, 0xc0004ffcb0?}, 0xd?, {0xb2bec0?, 0xc00033af00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000450b60, {0xd847f0, 0xc0004ffcb0}, 0xc000519450, 0xc00004d980, {0xb2bec0, 0xc00033af00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000389188, {0xd847f0?, 0xc0004ffb90?}, 0xc00033b400)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003e4320, {0xd847f0?, 0xc0004ff1d0?}, 0xc0003422a0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc29f00?, 0xc0003e4320}, {0xd847f0, 0xc0004ff1d0}, 0xc000342230, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000470000, {0xd87268, 0xc000570000}, 0xc00035a000, 0xc000472a50, 0x1212d00, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc000470000, {0xd87268, 0xc000570000}, 0xc00035a000, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-proxmox_v2.9.11 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)

The detail of the terraform main.tf:
# lxc-example.tf nginx
provider "proxmox" {
  pm_tls_insecure = true
  # URL of proxmox API
  pm_api_url = var.proxmox_api_var
  # API token id
  pm_api_token_id = var.proxmox_api_token_var
  # This is the secret value of the api token
  pm_api_token_secret = var.proxmox_api_token_secret_var
  #set time out for more than 300s
  pm_timeout    = 1800
  # pm_log_enable = true
  # pm_log_file   = "terraform-plugin-proxmox.log"
  # pm_debug      = true
  # pm_log_levels = {
  #   _default    = "debug"
  #   _capturelog = ""
  # }
}

resource "proxmox_lxc" "nginx-reverse-proxy" {
  target_node  = "node"
  hostname     = "nginx-reverse-proxy"
  vmid         = 103
  cores        = 1
  memory       = 512
  ostemplate   = "local:vztmpl/debian-11-standard_11.3-1_amd64.tar.zst"
  password     = "pass"
  unprivileged = "true"
  onboot       = "true"
  start        = "true"

  // Terraform will crash without rootfs defined
  rootfs {
    storage = "local-lvm"
    size    = "8G"
  }

  network {
    name   = "eth0"
    bridge = "vmbr1"
    ip     = "dhcp"
    mtu    = "9000"
  }

  ssh_public_keys = <<-EOT
    ssh-ed25519 ssh key code
    ssh-ed25519 ssh key code
  EOT

}

**Comment by guzmalito** [comment]
Closing, issue seems to happen only when using Terraform cloud as remote state store.
