### ISSUE TITLE
LXC clone issue

### ISSUE THREAD

**Issue by wyxtpthll** [Telmate/terraform-provider-proxmox#647]
Error on cloning lxc container. 
Something on getting HA config. HA on server not enabled.

```
  terraform {
    required_providers {
      proxmox = {
        source  = "Telmate/proxmox"
        version = "2.9.11"
      }
    }
  }
  provider "proxmox" {
    pm_parallel         = 1
    pm_tls_insecure     = true
    pm_api_url          = var.pm_api_url
    pm_log_enable = true
    pm_log_file   = "terraform-plugin-proxmox.log"
    pm_debug      = true
    pm_log_levels = {
      _default    = "debug"
      _capturelog = ""
    }
  }


resource "proxmox_lxc" "basic" {
  target_node  = "pve2"
  hostname     = "TEST-lxc-basic"
  clone       = "999"
  full = true
}

```

```
proxmox_lxc.basic: Creating...
proxmox_lxc.basic: Still creating... [10s elapsed]
proxmox_lxc.basic: Still creating... [20s elapsed]
╷
│ Error: Request cancelled
│
│   with proxmox_lxc.basic,
│   on ressource_testvm.tf line 1, in resource "proxmox_lxc" "basic":
│    1: resource "proxmox_lxc" "basic" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-proxmox_v2.9.11 plugin:

panic: assignment to entry in nil map

goroutine 51 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceLxcCreate(0x0?, {0xb2bec0?, 0xc00007e050?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:570 +0x1987
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd847f0?, {0xd847f0?, 0xc0004ed800?}, 0xd?, {0xb2bec0?, 0xc00007e050?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003d6b60, {0xd847f0, 0xc0004ed800}, 0xc00018d6c0, 0xc00017ff00, {0xb2bec0, 0xc00007e050})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003091d0, {0xd847f0?, 0xc0004ed6e0?}, 0xc0004d9bd0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000376320, {0xd847f0?, 0xc0004ec3c0?}, 0xc0001a0e00)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc29f00?, 0xc000376320}, {0xd847f0, 0xc0004ec3c0}, 0xc0001a0d90, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f2000, {0xd87268, 0xc000418340}, 0xc0001f7200, 0xc0003eee70, 0x1212d00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0003f2000, {0xd87268, 0xc000418340}, 0xc0001f7200, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-proxmox_v2.9.11 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

Proxmox server version:
```
proxmox-ve: 7.3-1 (running kernel: 5.15.83-1-pve)
pve-manager: 7.3-4 (running version: 7.3-4/d69b70d4)
pve-kernel-5.15: 7.3-1
pve-kernel-helper: 7.3-1
pve-kernel-5.13: 7.1-9
pve-kernel-5.4: 6.4-4
pve-kernel-5.15.83-1-pve: 5.15.83-1
pve-kernel-5.15.74-1-pve: 5.15.74-1
pve-kernel-5.15.64-1-pve: 5.15.64-1
pve-kernel-5.13.19-6-pve: 5.13.19-15
pve-kernel-5.13.19-2-pve: 5.13.19-4
pve-kernel-5.4.124-1-pve: 5.4.124-1
pve-kernel-5.4.73-1-pve: 5.4.73-1
ceph-fuse: 14.2.21-1
corosync: 3.1.7-pve1
criu: 3.15-1+pve-1
glusterfs-client: 9.2-1
ifupdown: not correctly installed
ifupdown2: 3.1.0-1+pmx3
ksm-control-daemon: 1.4-1
libjs-extjs: 7.0.0-1
libknet1: 1.24-pve2
libproxmox-acme-perl: 1.4.3
libproxmox-backup-qemu0: 1.3.1-1
libpve-access-control: 7.3-1
libpve-apiclient-perl: 3.2-1
libpve-common-perl: 7.3-1
libpve-guest-common-perl: 4.2-3
libpve-http-server-perl: 4.1-5
libpve-storage-perl: 7.3-1
libqb0: 1.0.5-1
libspice-server1: 0.14.3-2.1
lvm2: 2.03.11-2.1
lxc-pve: 5.0.0-3
lxcfs: 4.0.12-pve1
novnc-pve: 1.3.0-3
proxmox-backup-client: 2.3.1-1
proxmox-backup-file-restore: 2.3.1-1
proxmox-mini-journalreader: 1.3-1
proxmox-offline-mirror-helper: 0.5.0-1
proxmox-widget-toolkit: 3.5.3
pve-cluster: 7.3-1
pve-container: 4.4-2
pve-docs: 7.3-1
pve-edk2-firmware: 3.20220526-1
pve-firewall: 4.2-7
pve-firmware: 3.6-2
pve-ha-manager: 3.5.1
pve-i18n: 2.8-1
pve-qemu-kvm: 7.1.0-4
pve-xtermjs: 4.16.0-1
qemu-server: 7.3-2
smartmontools: 7.2-pve3
spiceterm: 3.2-2
swtpm: 0.8.0~bpo11+2
vncterm: 1.7-1
zfsutils-linux: 2.1.7-pve1
```

LOG file:
```
2022/12/29 13:44:02 >>>>>>>>>> REQUEST:
GET /api2/json/nodes/pve2/tasks/UPID:pve2:003E968C:016E6414:63AD7D74:vzclone:999:root@pam:/status HTTP/1.1

2022/12/29 13:44:02 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK

{"data":{"node":"pve2","id":"999","pstart":24011796,"pid":4101772,"type":"vzclone","starttime":1672314228,"upid":"UPID:pve2:003E968C:016E6414:63AD7D74:vzclone:999:root@pam:","user":"root@pam","exitstatus":"OK","status":"stopped"}}
2022/12/29 13:44:02 [DEBUG][LxcCreate] Waiting for clone becoming ready
2022/12/29 13:44:02 >>>>>>>>>> REQUEST:
GET /api2/json/nodes/pve2/lxc/334/config HTTP/1.1

2022/12/29 13:44:02 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK

{"data":{"hostname":"TEST-lxc-basic","digest":"dde2150493d0d284c9280a8f58d1b4b0883be55e","swap":0,"features":"nesting=1","ostype":"ubuntu","net0":"name=eth0,bridge=vmbr10,firewall=1,hwaddr=00:11:50:EB:74:7D,ip=dhcp,type=veth","unprivileged":1,"cores":1,"arch":"amd64","rootfs":"local-ssd:subvol-334-disk-0,size=2G","memory":1024}}
2022/12/29 13:44:02 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/334 HTTP/1.1

2022/12/29 13:44:02 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:334'

{"data":null}
2022/12/29 13:44:02 [DEBUG][GetJsonRetryable] Sleeping for 1 seconds before asking url /cluster/ha/resources/334
2022/12/29 13:44:03 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/334 HTTP/1.1

2022/12/29 13:44:03 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:334'

{"data":null}
2022/12/29 13:44:03 [DEBUG][GetJsonRetryable] Sleeping for 2 seconds before asking url /cluster/ha/resources/334
2022/12/29 13:44:05 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/334 HTTP/1.1

2022/12/29 13:44:05 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:334'

{"data":null}
2022/12/29 13:44:05 [DEBUG][GetJsonRetryable] Sleeping for 3 seconds before asking url /cluster/ha/resources/334
2022/12/29 13:44:08 [DEBUG] Container 334(TEST-lxc-basic) has no HA config
2022/12/29 13:44:08 [DEBUG][LxcCreate] We must resize
2022/12/29 13:44:08 >>>>>>>>>> REQUEST:
GET /api2/json/nodes/pve2/lxc/334/config HTTP/1.1

2022/12/29 13:44:08 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK

{"data":{"arch":"amd64","rootfs":"local-ssd:subvol-334-disk-0,size=2G","memory":1024,"unprivileged":1,"cores":1,"swap":0,"hostname":"TEST-lxc-basic","digest":"dde2150493d0d284c9280a8f58d1b4b0883be55e","features":"nesting=1","ostype":"ubuntu","net0":"name=eth0,bridge=vmbr10,firewall=1,hwaddr=00:11:50:EB:74:7D,ip=dhcp,type=veth"}}
2022/12/29 13:44:08 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/334 HTTP/1.1

2022/12/29 13:44:08 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:334'

{"data":null}
2022/12/29 13:44:08 [DEBUG][GetJsonRetryable] Sleeping for 1 seconds before asking url /cluster/ha/resources/334
2022/12/29 13:44:09 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/334 HTTP/1.1

2022/12/29 13:44:09 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:334'

{"data":null}
2022/12/29 13:44:09 [DEBUG][GetJsonRetryable] Sleeping for 2 seconds before asking url /cluster/ha/resources/334
2022/12/29 13:44:11 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/334 HTTP/1.1

2022/12/29 13:44:11 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:334'

{"data":null}
2022/12/29 13:44:11 [DEBUG][GetJsonRetryable] Sleeping for 3 seconds before asking url /cluster/ha/resources/334
2022/12/29 13:44:14 [DEBUG] Container 334(TEST-lxc-basic) has no HA config
```

**Comment by andrekloster** [comment]
I had the same problem. Once you try to clone a LXC template, you have to specify `rootfs` in your resource.

e.g.
```
rootfs {
  size = "20G"
  storage = "local-lvm"
}
```

**Comment by wyxtpthll** [comment]
Thanks.
Everything is ok after adding rootfs.
