### ISSUE TITLE
Error on terrafoem apply

### ISSUE THREAD

**Issue by fmbrown** [Telmate/terraform-provider-proxmox#676]
I'm not sure what to do to fix this error.

Error: Plugin did not respond
│
│   with proxmox_vm_qemu.test_server[0],
│   on main.tf line 26, in resource "proxmox_vm_qemu" "test_server":
│   26: resource "proxmox_vm_qemu" "test_server" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs
│ may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.7.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x932eb0]

goroutine 39 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc00038a800, 0xb77d60, 0xc0003427d0, 0x0, 0x0)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:843 +0x27d0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00015c460, 0xda0938, 0xc0001efec0, 0xc00038a800, 0xb77d60, 0xc0003427d0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00015c460, 0xda0938, 0xc0001efec0, 0xc0003412d0, 0xc0000cb6c0, 0xb77d60, 0xc0003427d0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c078, 0xda0938, 0xc0001efec0, 0xc000342e10, 0xc0001efec0, 0xc714a0, 0xc00033f800)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0000cb080, 0xda09e0, 0xc0001efec0, 0xc0003410a0, 0xc0000cb080, 0xc00033f8f0, 0xc0001b2ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc714a0, 0xc0000cb080, 0xda09e0, 0xc00033f8f0, 0xc00032d3e0, 0x0, 0xda09e0, 0xc00033f8f0, 0xc00035ed80, 0xd69)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000272c40, 0xda8098, 0xc000318780, 0xc0001cc300, 0xc000302780, 0x11b3ce0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000272c40, 0xda8098, 0xc000318780, 0xc0001cc300, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000310080, 0xc000272c40, 0xda8098, 0xc000318780, 0xc0001cc300)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-proxmox_v2.7.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by mleone87** [comment]
No info + very old version: closing
