### ISSUE TITLE
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

### ISSUE THREAD

**Issue by amitpatole** [Telmate/terraform-provider-proxmox#711]
Tried with all the older versions but still getting same error. VM gets deployed from clone but errors out while reconfiguring the VM

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

**Comment by rterbush** [comment]
I'm getting this same error with version 2.9.11.  (v2.9.13 does not allow use of api key)

I'm trying to clone an lxc template into a full clone. Here is my resource entry:
```hcl
resource "proxmox_lxc" "server-clone" {
  count                  = 1
  hostname           = "server-${count.index + 1}"
  clone                   = 501
  full                       = true
  clone_storage    = "containers"
  password            = var.nautilus-server-password
  unprivileged        = true
  cores                   = 4
  memory               = 2048
  swap                    = 1024
  vmid                     = "20${count.index + 1}"
  start                      = true
  ssh_public_keys  = var.ssh_key
}
```

Backtrace:
```
│ Error: Plugin did not respond
│
│   with proxmox_lxc.server-clone[0],
│   on main.tf line 44, in resource "proxmox_lxc" "server-clone":
│   44: resource "proxmox_lxc" "server-clone" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.11 plugin:

panic: assignment to entry in nil map

goroutine 14 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceLxcCreate(0x0?, {0x1052c3f40?, 0x14000136f50?})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:570 +0x12c4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1053f8708?, {0x1053f8708?, 0x14000135f80?}, 0xd?, {0x1052c3f40?, 0x14000136f50?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:695 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140001f9260, {0x1053f8708, 0x14000135f80}, 0x140003acf70, 0x140003b6e80, {0x1052c3f40, 0x14000136f50})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0x874
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140002c05d0, {0x1053f8708?, 0x14000135e60?}, 0x14000614320)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000285c20, {0x1053f8708?, 0x14000135650?}, 0x140002172d0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1053c2dc0?, 0x14000285c20}, {0x1053f8708, 0x14000135650}, 0x14000217260, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002de1e0, {0x1053fb148, 0x140003989c0}, 0x140005066c0, 0x14000432c30, 0x10586eda0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0x9d8
google.golang.org/grpc.(*Server).handleStream(0x140002de1e0, {0x1053fb148, 0x140003989c0}, 0x140005066c0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x298

Error: The terraform-provider-proxmox_v2.9.11 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by rterbush** [comment]
This also does not appear to be a permission issue as I gave the API token PVEAdmin permissions and it still fails.

**Comment by rterbush** [comment]
So for me, the failure seems to start when the process starts asking for /api2/json/cluster/ha/resources/CID

There is no HA configured on this server and not sure what is prompting this dialog. Relevant section of the log below:

```
{"data":{"cores":4,"protection":0,"cpuunits":1024,"console":1,"memory":2048,"cmode":"tty","swap":1024,"unprivileged":1,"rootfs":"containers:subvol-201-disk-0,size=10G","hostname":"nt-trade-1","onboot":0,"net0":"name=eth0,bridge=vmbr0,hwaddr=8E:3C:EB:6F:A8:63,ip=dhcp,type=veth","arch":"amd64","cpulimit":"0","digest":"66c960a6a57f95618f040e00c80838e4ef6cccce","ostype":"centos","tty":2}}
2023/03/17 16:01:57 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/201 HTTP/1.1
Host: 10.10.9.1:8006
User-Agent: Go-http-client/1.1
Accept: application/json
Authorization: PVEAPIToken=xxx
Accept-Encoding: gzip

2023/03/17 16:01:57 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:201'
Connection: close
Content-Length: 13
Cache-Control: max-age=0
Content-Type: application/json;charset=UTF-8
Date: Fri, 17 Mar 2023 22:01:57 GMT
Expires: Fri, 17 Mar 2023 22:01:57 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0

{"data":null}
2023/03/17 16:01:57 [DEBUG][GetJsonRetryable] Sleeping for 1 seconds before asking url /cluster/ha/resources/201
2023/03/17 16:01:58 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/201 HTTP/1.1
Host: 10.10.9.1:8006
User-Agent: Go-http-client/1.1
Accept: application/json
Authorization: PVEAPIToken=xxx
Accept-Encoding: gzip

2023/03/17 16:01:59 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:201'
Connection: close
Content-Length: 13
Cache-Control: max-age=0
Content-Type: application/json;charset=UTF-8
Date: Fri, 17 Mar 2023 22:01:59 GMT
Expires: Fri, 17 Mar 2023 22:01:59 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0

{"data":null}
2023/03/17 16:01:59 [DEBUG][GetJsonRetryable] Sleeping for 2 seconds before asking url /cluster/ha/resources/201
2023/03/17 16:02:01 >>>>>>>>>> REQUEST:
GET /api2/json/cluster/ha/resources/201 HTTP/1.1
Host: 10.10.9.1:8006
User-Agent: Go-http-client/1.1
Accept: application/json
Authorization: PVEAPIToken=xxx
Accept-Encoding: gzip

2023/03/17 16:02:01 <<<<<<<<<< RESULT:
HTTP/1.1 500 no such resource 'ct:201'
Connection: close
Content-Length: 13
Cache-Control: max-age=0
Content-Type: application/json;charset=UTF-8
Date: Fri, 17 Mar 2023 22:02:01 GMT
Expires: Fri, 17 Mar 2023 22:02:01 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0

{"data":null}
2023/03/17 16:02:01 [DEBUG][GetJsonRetryable] Sleeping for 3 seconds before asking url /cluster/ha/resources/201
2023/03/17 16:02:04 [DEBUG] Container 201(nt-trade-1) has no HA config
```

**Comment by rterbush** [comment]
So by adding the line `hastate = "ignored"` to the resource config the apply process was able to start the container but the apply process still ends with an error: `Error: Plugin did not respond`

This can't really be considered a workaround since Terraform still thinks that the container did not get deployed. Changing the count to 0 to remove it indicates `"No changes.`

Would love to get some input from @ggongaware or other relevant Telmate contributor.
Thanks

**Comment by rterbush** [comment]
Confirming that the v2.9.14 release does not fix this issue.

**Comment by rterbush** [comment]
After a bit more testing with the v2.9.14 release I am happy to report that with proper resource config, this now works and does not require an `hastate` parameter. The one thing that was causing the failure was lack of `rootfs {}` parameters for the clone. I was mistakenly assuming this is implied by the size of the container you are cloning from but seems to be required even for clones.

The following now works:

```hcl
resource "proxmox_lxc" "nautilus-trader" {
  count         = 1
  hostname = "server-${count.index + 1}"
  target_node   = "cnode3"
  clone         = 501
  full          = true
  cores         = 4
  memory        = 2048
  swap          = 1024
  start         = true
  onboot        = true
  unprivileged  = true
  vmid          = count.index + 201

  rootfs {
    storage = "containers"
    size = "10G"
  }
}
```
