### ISSUE TITLE
[ Gitlab Runner ] Request cancelled when using docker image hashicorp/terraform:light

### ISSUE THREAD

**Issue by Djebre** [Telmate/terraform-provider-proxmox#715]
Hi, I try to run my terraform script in a GitLab CI/CD pipeline, with the docker image hashicorp/terraform:light
My runner has the docker executor.

Error log from gitlab CI/CD : 
 ```
│ Error: Request cancelled
│ 
│   with proxmox_vm_qemu.preprovision-test,
│   on main.tf line 56, in resource "proxmox_vm_qemu" "preprovision-test":
│   56: resource "proxmox_vm_qemu" "preprovision-test" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
Stack trace from the terraform-provider-proxmox_v2.7.4 plugin:
panic: interface conversion: interface {} is nil, not []interface {}
goroutine 75 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc0003aa280, 0xc00039ea40, 0x8, 0xb9c6a0, 0xd82630, 0x0, 0x0, 0xc0001da000)
	github.com/Telmate/proxmox-api-go@v0.0.0-20210713150936-9bfd169c655f/proxmox/client.go:180 +0x899
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
	github.com/Telmate/proxmox-api-go@v0.0.0-20210713150936-9bfd169c655f/proxmox/client.go:170
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000bac00, 0xb77d60, 0xc000264fa0, 0x0, 0x0)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:776 +0x1629
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00042a460, 0xda0938, 0xc0004f0c80, 0xc0000bac00, 0xb77d60, 0xc000264fa0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00042a460, 0xda0938, 0xc0004f0c80, 0xc0003cc9a0, 0xc00039daa0, 0xb77d60, 0xc000264fa0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000bc078, 0xda0938, 0xc0004f0c80, 0xc0003ab130, 0xc0004f0c80, 0xc714a0, 0xc000288d00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00039ccc0, 0xda09e0, 0xc0004f0c80, 0xc0003cc700, 0xc00039ccc0, 0xc000288d50, 0xc0001c9ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc714a0, 0xc00039ccc0, 0xda09e0, 0xc000288d50, 0xc0003b8600, 0x0, 0xda09e0, 0xc000288d50, 0xc000647000, 0xe18)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000da380, 0xda8098, 0xc000092f00, 0xc0003ba000, 0xc000382600, 0x11b3ce0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000da380, 0xda8098, 0xc000092f00, 0xc0003ba000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b81f0, 0xc0000da380, 0xda8098, 0xc000092f00, 0xc0003ba000)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
Error: The terraform-provider-proxmox_v2.7.4 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
 ```

My main.tf : 

```
terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "2.7.4"
    }
  }
}

provider "proxmox" {
  pm_api_url = var.proxmox_host_api
  # api token id is in the form of: <username>@pam!<tokenId>
  pm_user = var.proxmox_user
  pm_password = var.proxmox_password
  pm_log_enable = true
  pm_log_file   = "terraform-plugin-proxmox.log"
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}


resource "proxmox_vm_qemu" "preprovision-test" {
  depends_on = [
#    null_resource.cloud_init_debian
  ]
  name        = "devsec-${var.vm_name}"
  desc        = "Test deployment"
  target_node = "${var.vm_target_node}"
  pool        = "DevSecOps"
  clone = "template-devsecops"
  os_type = "cloud-init"
  cores   = 2
  sockets = 1
  memory  = 2048
  numa     = false
  agent = 1
  boot = "order=ide2;scsi0;net0"
  # It's possible to add this type of material and use it directly
  # Possible values are: network,disk,cpu,memory,usb
  hotplug  = "network,disk"
  # Default boot disk
  bootdisk = "scsi0"
  ipconfig0 = "ip=...."
  ciuser = "user"
  cipassword = "user"
  sshkeys = "ssh-rsa ...."

  #Display
  vga {
    type   = "std"
    #Between 4 and 512, ignored if type is defined to serial
    memory = 4
  }
  network {
    model  = "virtio"
    bridge = "vmbr1"
    tag = 57
    firewall = true
  }
  disk {
    type         = "scsi"
    storage      = "local-lvm"
    size         = "20G"
  }
  # Serial interface of type socket is used by xterm.js
  # You will need to configure your guest system before being able to use it
  serial {
    id   = 0
    type = "socket"
  }
  
  # Ignore changes to the network
  ## MAC address is generated on every apply, causing
  ## TF to think this needs to be rebuilt on every apply
  lifecycle {
     ignore_changes = [
       network
     ]
  }
}
```
This script works perfectly fine when using in local WSL on Windows.
I also checked #543 with similar error : 
```
interface conversion: interface {} is nil, not []interface {}
```

Edit : 

**I tested the docker image ```hashicorp/terraform:light``` locally and it works, the problem seems to come from the runner/gitlab.**

Edit 2 :

**It seems that the runner in the gitlab pipeline is not able to run terraform even while using shell environnement, I did run terraform while being the user "gitlab-runner" and it works fine. I tried to update the provider to version ```2.9.13``` and I got an other error :**

```
│ Error: user does not exist or has insufficient permissions on proxmox: terraform-prov@pve!terraform-token
│ 
│   with provider["registry.terraform.io/telmate/proxmox"],
│   on main.tf line 10, in provider "proxmox":
│   10: provider "proxmox" {
```
Even if credentials are valid and the user has enought permissions...

**Comment by Djebre** [comment]
# [ CLOSED ]
2 things I learn from that : 
* You have to use the last version of "telmate/proxmox" (2.9.13)
* Don't forget to verify your hidden CI/CD values in GitLab 🤡

My credentials were overrided by the CI/CD vars, I deleted them and it was all good !
