### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by jkocianICA** [Telmate/terraform-provider-proxmox#716]
### Plugin crashed
Trying to run a test to create an ubuntu focal 22.04 template in Proxmox and saw this error. Double checked my configs and couldn't find anything other than a plugin error to be the issue.

### Output from the error:

```
**Error**: Plugin did not respond
│
│   with proxmox_vm_qemu.ubuntu-focal-docker[0],
│   on ubuntu-server-templates.tf line 1, in resource "proxmox_vm_qemu" "ubuntu-focal-docker":
│    1: resource "proxmox_vm_qemu" "ubuntu-focal-docker" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.3 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 59 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc0002e41e0, 0xc000034240, 0x13, 0x1, 0x1, 0x0, 0x0, 0xc000130200)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:190 +0x845
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc00046dd80, 0xbc5cc0, 0xc0002e4230, 0xc, 0xffffffffffffffff)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:738 +0x1886
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002b4460, 0xe0a8b8, 0xc000175540, 0xc00046dd80, 0xbc5cc0, 0xc0002e4230, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:329 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002b4460, 0xe0a8b8, 0xc000175540, 0xc0005292b0, 0xc00046db80, 0xbc5cc0, 0xc0002e4230, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002240c0, 0xe0a8b8, 0xc000175540, 0xc0002e49b0, 0xc000175540, 0xcd0560, 0xc0002ce900)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000494360, 0xe0a960, 0xc000175540, 0xc000386a80, 0xc000494360, 0xc0002ce9f0, 0xc0001bbba0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xcd0560, 0xc000494360, 0xe0a960, 0xc0002ce9f0, 0xc00036e4e0, 0x0, 0xe0a960, 0xc0002ce9f0, 0xc000416a80, 0xa41)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fc540, 0xe12198, 0xc00050a900, 0xc0000b1e60, 0xc0006065a0, 0x1251e00, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001fc540, 0xe12198, 0xc00050a900, 0xc0000b1e60, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002283a0, 0xc0001fc540, 0xe12198, 0xc00050a900, 0xc0000b1e60)
        google.golang.org/grpc@v1.42.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x1fd

Error: The terraform-provider-proxmox_v2.9.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by Djebre** [comment]
What version of ```telmate/proxmox``` are you using ?

**Comment by jkocianICA** [comment]
Thanks for the reply, sorry I missed that info in the OP.

Terraform: v1.3.9
Telmate/Proxmox: v2.9.3

I've also tried v2.8.0 and 2.9.2-2.9.0 and I still get the same result.

**Comment by mleone87** [comment]
try latest version please
