### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by SilentSib** [Telmate/terraform-provider-proxmox#730]
Hi,

I'm using terraform 1.4.2 and the latest version of your provider (2.9.14) and when trying to import an existing VM I get the following crash:

```
  Prepared proxmox_vm_qemu for import
proxmox_vm_qemu.kubernetes-slave-one: Refreshing state... [id=proxmox/ubuntu/101]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to
│ respond to the
│ plugin.(*GRPCProvider).ReadResource call. The
│ plugin logs may contain more details.
╵


Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 13 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0x4000319038, 0x4000319038?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:789 +0x37cc
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0x4000158600, {0x6cdf40?, 0x400019c000})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x328
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0x6cdf40?, 0x400019c000?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x24
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x93efc0?, {0x93efc0?, 0x4000485710?}, 0xd?, {0x6cdf40?, 0x400019c000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x4000164fc0, {0x93efc0, 0x4000485710}, 0x4000563450, {0x6cdf40, 0x400019c000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x460
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x4000371ef0, {0x93efc0?, 0x40004855f0?}, 0x400049e600)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x3fcgithub.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x4000298320, {0x93efc0?, 0x40004844b0?}, 0x40004002a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x7d2980?, 0x4000298320}, {0x93efc0, 0x40004844b0}, 0x40004c6150, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x16c
google.golang.org/grpc.(*Server).processUnaryRPC(0x40002221e0, {0x942b80, 0x4000472000}, 0x400051c120, 0x400037dcb0, 0xdef670, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb68
google.golang.org/grpc.(*Server).handleStream(0x40002221e0, {0x942b80, 0x4000472000}, 0x400051c120, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x294

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Please note that I was able to import another very similar VM without issues just before that.

Can you please help?
Thanks,

SilentSib

**Comment by SilentSib** [comment]
Fixed by looking at the code and by then appending `size=2G` in the VM conf file for the hard disk parameter.
