### ISSUE TITLE
Plugin crashed when there are physical disks attached in the VM

### ISSUE THREAD

**Issue by ivangundampc** [Telmate/terraform-provider-proxmox#786]
Hi, I encountered a problem when trying to attach physical disk to a VM. Since the resource required to provide the field `stroage` in the disk block, but there is no storage pool to provide when passing through a physical disk. When I try to add the physical disk by modify the qemu configuration file directly, then run the planning again, the plugin crashed.

I think maybe because the provider is trying to map the `volume` and `file` fields my spiting the disk lines with the `:` character, but it crashes when there is no `:`? Thanks.
e.g. 
for virtual disk: `vmdisk:106/vm-106-disk-0.raw,format=raw,size=40G`
but for physical disk passthrough, it is: `/dev/disk/by-id/ata-redacted,size=14902G`, no `:`.

Thanks!

Below is the crashing message :
```
Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 86 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000528900, {0xb66f60?, 0xc0005b1220})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1586 +0x363d
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0xb66f60?, 0xc0005b1220?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xdd7840?, {0xdd7840?, 0xc000708ba0?}, 0xd?, {0xb66f60?, 0xc0005b1220?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000f8ee0, {0xdd7840, 0xc000708ba0}, 0xc0003a2dd0, {0xb66f60, 0xc0005b1220})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000301f20, {0xdd7840?, 0xc000708a80?}, 0xc0005ac740)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001b2460, {0xdd7840?, 0xc0007082a0?}, 0xc000522cc0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc6bc20?, 0xc0001b2460}, {0xdd7840, 0xc0007082a0}, 0xc0000ee000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ae1e0, {0xddb420, 0xc0003889c0}, 0xc00070c120, 0xc00030dce0, 0x128f770, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001ae1e0, {0xddb420, 0xc0003889c0}, 0xc00070c120, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

My "proxmox_vm_qemu" resource:
```
resource "proxmox_vm_qemu" "proxmox_vm_truenas_master" {
  name        = "vm-truenas-master"
  vmid        = var.truenas_master.vmid
  target_node = var.pm_node_name
  bios        = "ovmf"
  os_type     = "ubuntu"
  balloon     = var.truenas_master.mim_memory
  memory      = var.truenas_master.memory
  cores       = var.truenas_master.num_core
  iso         = var.truenas_iso
  boot        = "order=scsi0"
  agent       = 0
  define_connection_info = false
  automatic_reboot = false
  scsihw = "virtio-scsi-single"
  qemu_os = "l26"

  dynamic "disk" {
    for_each = var.truenas_master.disks
    content {
      type = disk.value.type
      storage = disk.value.storage
      size = disk.value.size
    }
  }

  dynamic "network" {
    for_each = var.truenas_master.networks
    content {
      model = network.value.model
      bridge = network.value.bridge
      firewall = network.value.firewall
    }
  }

  lifecycle {
    ignore_changes = [
      define_connection_info,
      ciuser,
      sshkeys,
      network,
      onboot,
      disk,
      iso
    ]
  }
}
```

The qemu configuration file of the corresponding VM (after adding physical disk manually):
```
agent: 0
balloon: 4096
bios: ovmf
boot: order=scsi0
cores: 2
cpu: host
hotplug: network,disk,usb
ide2: images:iso/TrueNAS-SCALE-22.12.2.iso,media=cdrom,size=1699538K
kvm: 1
machine: q35
memory: 8192
meta: creation-qemu=6.2.0,ctime=1682941905
name: vm-truenas-master
net0: virtio=redacted,bridge=vmbr0,firewall=1
net1: virtio=redacted,bridge=vmbr1
numa: 0
onboot: 0
ostype: l26
scsi0: vmdisk:106/vm-106-disk-0.raw,format=raw,size=40G
scsi1: vmdisk:106/vm-106-disk-1.raw,format=raw,size=5G
scsi2: /dev/disk/by-id/ata-redacted,size=14902G
scsi3: /dev/disk/by-id/ata-redacted,size=14902G
scsi4: /dev/disk/by-id/ata-redacted,size=14902G
scsi5: /dev/disk/by-id/ata-redacted,size=14902G
scsihw: virtio-scsi-single
smbios1: uuid=redacted
sockets: 1
tablet: 1
vmgenid: redacted
```

**Comment by jsaalfeld** [comment]
https://github.com/Telmate/terraform-provider-proxmox/issues/581 states this issue is closed - but it doesn't seem to be released (yet).

**Comment by ivangundampc** [comment]
Cloned the repo and override the plugin with the newest changes locally, the error disappeared.
I think #765 has fixed this problem, please release it if possible.
