### ISSUE TITLE
2.9.11 plugin crashed when destroying a vm with attached disks

### ISSUE THREAD

**Issue by viajandee** [Telmate/terraform-provider-proxmox#810]
Deployed a VM along with a remote-exec that runs on the Proxmox host to search and attach 4 disks. When the disks are attached and I try to `destroy` the plugin crashes with the output below. When I try to detach the disks first before `destroy` it works fine.
```
terraform destroy -var-file="secrets.tfvars" -auto-approve

proxmox_vm_qemu.vm: Refreshing state... [id=pve/qemu/1200]
╷
│ Error: Request cancelled
│ 
│   with proxmox_vm_qemu.vm,
│   on main.tf line 1, in resource "proxmox_vm_qemu" "vm":
│    1: resource "proxmox_vm_qemu" "vm" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-proxmox_v2.9.11 plugin:

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 65 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetStorageStatus(0x17a36e0?, 0xc000239130, {0x0, 0x0})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220818102740-0129fa923095/proxmox/client.go:286 +0x1fe
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000239130, 0xc000239130?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220818102740-0129fa923095/proxmox/config_qemu.go:788 +0x26ca
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc00030ca00, {0x172b900?, 0xc00058af00})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1388 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0x172b900?, 0xc00058af00?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1359 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1984c50?, {0x1984c50?, 0xc00029b260?}, 0xd?, {0x172b900?, 0xc00058af00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003be7e0, {0x1984c50, 0xc00029b260}, 0xc00052cb60, {0x172b900, 0xc00058af00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000b7170, {0x1984c50?, 0xc00029b140?}, 0xc000097900)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000f4320, {0x1984c50?, 0xc00029a960?}, 0xc00008cf60)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x182a9a0?, 0xc0000f4320}, {0x1984c50, 0xc00029a960}, 0xc0005945b0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ea000, {0x1987748, 0xc0002b89c0}, 0xc00029c360, 0xc0003ecb10, 0x1e16e30, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0003ea000, {0x1987748, 0xc0002b89c0}, 0xc00029c360, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-proxmox_v2.9.11 plugin crashed!
```

**Comment by ScionOfDesign** [comment]
This also happens in 2.9.14.

**Comment by theeternalrat** [comment]
I have encountered this error in `2.9.11`
