### ISSUE TITLE
Crash on terraform import

### ISSUE THREAD

**Issue by KlutzyBubbles** [Telmate/terraform-provider-proxmox#826]
I am positive the api url is able to connect as i can create, remove and edit resources with terraform apply just fine, only when i use import do i get this issue.

I have tried searching existing issues but i was unable to find a solution.

```
terraform import `     
>>  -var-file=C:\Users\KlutzyBubbles\Documents\GitHub\ubuntu-configurations\vars\proxmox\node1.tfvars `
>>  proxmox_vm_qemu.awx[0] `
>>  node1/qemu/101
proxmox_vm_qemu.awx[0]: Importing from ID "node1/qemu/101"...
proxmox_vm_qemu.awx[0]: Import prepared!
  Prepared proxmox_vm_qemu for import
proxmox_vm_qemu.awx[0]: Refreshing state... [id=node1/qemu/101]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The      
│ plugin logs may contain more details.
╵


Stack trace from the terraform-provider-proxmox_v2.9.14.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 54 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc00061f088, 0xc00061f088?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:789 +0x4310    
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000628880, {0xcb8680?, 0xc000528000}) 
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0xcb8680?, 0xc000528000?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xf3a800?, {0xf3a800?, 0xc00068c660?}, 
0xd?, {0xcb8680?, 0xc000528000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003547e0, {0xf3a800, 0xc00068c660}, 0xc00025f5f0, {0xcb8680, 0xc000528000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003dac18, {0xf3a800?, 0xc00068c540?}, 0xc000611540)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002ac3c0, {0xf3a800?, 0xc000249800?}, 0xc0004b8360)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xdbf460?, 0xc0002ac3c0}, {0xf3a800, 0xc000249800}, 0xc000232070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f4000, {0xf3e3e0, 0xc0003f91e0}, 0xc00070cd80, 0xc0003f6c60, 0x1400850, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0003f4000, {0xf3e3e0, 0xc0003f91e0}, 0xc00070cd80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

please let me know if i have left out any required information.

**Comment by KlutzyBubbles** [comment]
Still open, and still on same version

**Comment by r-trigo** [comment]
I got it working on Windows and OpenTofu by bumping the provider to V3.0.1-rc1. Let me know if this helps.
