### ISSUE TITLE
Trying to plan or apply with existing resources fails

### ISSUE THREAD

**Issue by KlutzyBubbles** [Telmate/terraform-provider-proxmox#827]
Trying to create tf files for some existing resources, with some changable settings slightly different, but name and vmid the same. The plan and apply does not recognize the existing resources and tried to create new ones, which then causes the generic error seen below.

Although it didnt recognise the existing resource, when actually applying it did stop and edit the existing resource (replace its disk, change ram cpu etc) but then it errored before it could finish.

```
terraform apply -var-file=C:\Users\KlutzyBubbles\Documents\GitHub\ubuntu-configurations\vars\proxmox\node1.tfvars
proxmox_lxc.influxdb[0]: Refreshing state... [id=node1/lxc/118]
proxmox_lxc.grafana[0]: Refreshing state... [id=node1/lxc/119]
proxmox_vm_qemu.pterodactyl-panel[0]: Refreshing state... [id=node1/qemu/117]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated     
with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_vm_qemu.hms[0] will be created
  + resource "proxmox_vm_qemu" "hms" {
      + name                      = "hms.klutzybubbles.me"
      + vmid                      = 103
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_vm_qemu.hms[0]: Creating...
╷
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.hms[0],
│   on hms.tf line 1, in resource "proxmox_vm_qemu" "hms":
│    1: resource "proxmox_vm_qemu" "hms" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call.   
│ The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.14.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 116 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000498240, 0x0?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:789 +0x4310    
github.com/Telmate/terraform-provider-proxmox/proxmox.prepareDiskSize(0x0?, 0xc0002969a8?, 0x14?, 0x0?)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1737 +0xeb
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000159880, {0xcb8680?, 0xc00048e050})        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1059 +0x1cb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf3a800?, {0xf3a800?, 0xc0004a4270?}, 0xd?, {0xcb8680?, 0xc00048e050?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000f8ee0, {0xf3a800, 0xc0004a4270}, 0xc00064ba00, 0xc000159700, {0xcb8680, 0xc00048e050})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000420018, 
{0xf3a800?, 0xc0004a4060?}, 0xc0001397c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002143c0, {0xf3a800?, 0xc000015650?}, 0xc00018eaf0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdbf460?, 0xc0002143c0}, {0xf3a800, 0xc000015650}, 0xc00018e9a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b61e0, {0xf3e3e0, 0xc0001c5a00}, 0xc0002bcc60, 0xc0004117a0, 0x1400880, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001b61e0, {0xf3e3e0, 0xc0001c5a00}, 0xc0002bcc60, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

The way i am working around this for now is deleting existing vms and redeploying with terraform (although i cant do this with all of them) so any help to solve this issue would be great.

**Comment by KlutzyBubbles** [comment]
Hoping this comment will remove the stale tag as its the same provider version

**Comment by KlutzyBubbles** [comment]
Hey look the bot marked a current issue as stale again
