### ISSUE TITLE
Crash (panic: runtime error: index out of range)

### ISSUE THREAD

**Issue by czepesch** [Telmate/terraform-provider-proxmox#84]
Hi,
Terraform version: 0.12.7
Go runtime version: go1.12.9
Debian 9.9 (Stretch)
Virtual Environment 5.4-13

New VM at Proxmox VE is up and running after terraform apply, but it is crashes in process.

----
<details>
<summary>terraform init</summary>

`czepe@tftpd:~$ terraform init
Initializing the backend...
Initializing provider plugins...
Terraform has been successfully initialized!`
</details>

---
<details>
  <summary>terraform plan</summary>

`Refreshing Terraform state in-memory prior to plan... The refreshed state will be used to calculate this plan, but will not be persisted to local or remote state storage. ------------------------------------------------------------------------ An execution plan has been generated and is shown below. Resource actions are indicated with the following symbols: + create
Terraform will perform the following actions:

proxmox_vm_qemu.TFdebian will be created
resource "proxmox_vm_qemu" "TFdebian" {

agent = 1
boot = "cdn"
clone = "debian10"
cores = 2
cpu = "host"
desc = "tf description"
force_create = false
hotplug = "network,disk,usb"
id = (known after apply)
memory = 2048
name = "TFdebian"
numa = false
onboot = true
os_type = "cloud-init"
preprovision = true
scsihw = "lsi"
sockets = 1
ssh_private_key = (sensitive value)
ssh_user = "debian"
sshkeys = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEmKUW4Ir8ATgr3jWj96Zfez+D8HGX2A/V6eNyTSrr3stjR4ejXmaO76HLWikwMoND3av93xT9avZzM7Fm54eyhouhXkLWY8n45nPmJtnJsimvJzbEWv5T88o/oBonqOgB00Uhgr2iPnWwsISSgKa8heOTjwS9Ce5oaFzF4FV5WFBnkpEpCy7ATN3dDXp0UkCcizUv4OCXLXfEcEGC+LwVpua9oR1SjovuS7ay6vvX8W5ikP352GeiaKFH+fIJ0IRHakXANb43KWxUM0SbY8DhkKieMi3kweTPCbbADPMLlkfVArtYf9FcOLEd1GrK0KGG43BvHu7n1BOAfe98ZHkd czepe@tftpd\r\n"
+ target_node = "pve2"
+ vlan = -1

+ disk {
    + backup       = false
    + cache        = "none"
    + format       = "raw"
    + id           = 0
    + iothread     = true
    + replicate    = false
    + size         = "5"
    + storage      = "local"
    + storage_type = "rbd"
    + type         = "virtio"
  }

+ network {
    + bridge    = "vmbr0"
    + firewall  = false
    + id        = 0
    + link_down = false
    + model     = "virtio"
    + queues    = -1
    + rate      = -1
    + tag       = -1
  }
}

Plan: 1 to add, 0 to change, 0 to destroy.` 
</details>

---
<details>
<summary>.tf file</summary>

`provider "proxmox" {
  pm_tls_insecure = true
  pm_api_url      = "https://10.0.3.2:8006/api2/json"
  pm_password     = "password"
  pm_user         = "myusername@mydomain"
}

resource "proxmox_vm_qemu" "TFdebian" {
  name = "TFdebian"
  desc = "tf description"
  target_node = "pve2"
  clone = "debian10"
  agent = 1
  os_type = "cloud-init"
  cores = 2
  sockets = 1
  cpu = "host"
  memory = 2048
  scsihw = "lsi"
  
disk {
	id = 0
	size = 5
	type = "virtio"
	storage = "local"
	storage_type = "rbd"
	iothread = true
}

network {
	id = 0
	model = "virtio"
	bridge = "vmbr0"
}

  ssh_user = "debian"
  ssh_private_key = <<EOF
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKC.........................UFj3xxketL
-----END RSA PRIVATE KEY-----
EOF

  sshkeys = <<EOF
ssh-rsa AAAAB3Nza..........1BOAfe98ZHkd czepe@tftpd
EOF

  provisioner "remote-exec" {
    inline = [
      "ip a"
    ]
  }
}`
</details>

---

from crash.log:
`[DEBUG] plugin.terraform-provider-proxmox: panic: runtime error: index out of range`
and
`[DEBUG] proxmox_vm_qemu.TFdebian: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Canceled desc = context canceled`

link (google drive) to full crash.log here: https://drive.google.com/open?id=1NHzJUZoXsIlIM09we9EW5B0NhA3NEAfo

Thank You in advance.

**Comment by propellerhead001** [comment]
I've run into this issue too when trying to use the cloud-init fields _cipassword_ and _sshkeys_ 
As you say, the VMs get created perfectly in Proxmox but something about these fields causes Terraform to crash.

**Comment by propellerhead001** [comment]
Edit to my above comment I had missed the _os_type = "cloud-init"_ flag needed to allow the use of the cloud init features and it seems to provision absolutely fine now.
@czepesch you might want to check in your .tf file if there are parameters which feature in the non cloud-init examples.
Here is my resource entry from my tf file:
```
resource "proxmox_vm_qemu" "test" {
  name = "test"
  desc = "tf description"
  target_node = "rigel"
  clone = "ubuntu16"
  memory = 512
  cores = 1
  sockets = 1
  disk {
    id = 0
    type = "virtio"
    storage = "local-lvm"
    storage_type = "lvm"
    size = "10G"
    backup = false
  }
  serial {
    id = 0
    type = "socket"
  }
  network {
    id = 0
    model = "virtio"
    bridge = "vmbr0"
    tag = 1023
  }


  os_type = "cloud-init"

  cipassword = "Inn0vation"
  sshkeys = <<EOF
ssh-rsa 
EOF

  ipconfig0 = "gw=192.168.122.129,ip=192.168.122.162/25"
}
```

**Comment by ata-sql** [comment]
I got the same error when trying to adopt terraform with proxmox.
proxmox-ve: **6.0-2** (running kernel: 5.0.15-1-pve)
Terraform **v0.12.17**
go version **go1.12.13 linux/amd64**
When adding "sshkeys" element, it crashes with:
`
Error: rpc error: code = Unavailable desc = transport is closing
panic: runtime error: index out of range
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: goroutine 83 [running]:
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.initConnInfo(0xc0000d20e0, 0xc000498c30, 0xc000452640, 0xc000545558, 0xc0005455a0, 0x2, 0x0)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:969 +0xae5
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000d20e0, 0xf75620, 0xc000498c30, 0x2, 0x1e84c60)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:589 +0x148a
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0000fd000, 0xc00040c640, 0xc000599120, 0xf75620, 0xc000498c30, 0xc00053a801, 0xc00020db48, 0x100dc20)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:305 +0x3b4
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0000fd280, 0xc000545a30, 0xc00040c640, 0xc000599120, 0xc0005321a8, 0xc0002b6050, 0x1010140)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0x18f
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000010a90, 0x14825a0, 0xc0004d83c0, 0xc0004f4180, 0xc000010a90, 0xc0004d83c0, 0xc0001bcba8)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:885 +0x894
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1154ec0, 0xc000010a90, 0x14825a0, 0xc0004d83c0, 0xc00040c370, 0x0, 0x14825a0, 0xc0004d83c0, 0xc0001b3900, 0xc0d)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3189 +0x23e
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044fb00, 0x148e580, 0xc000548900, 0xc0004f6100, 0xc000108d50, 0x1e42880, 0x0, 0x0, 0x0)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:998 +0x470
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00044fb00, 0x148e580, 0xc000548900, 0xc0004f6100, 0x0)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:1278 +0xda6
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003a8260, 0xc00044fb00, 0x148e580, 0xc000548900, 0xc0004f6100)
2019-12-10T07:35:41.194+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:717 +0x9f
2019-12-10T07:35:41.195+0100 [DEBUG] plugin.terraform-provider-proxmox: created by github.com/hashicorp/terraform/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-12-10T07:35:41.195+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/atalarek/go/src/github.com/hashicorp/terraform/vendor/google.golang.org/grpc/server.go:715 +0xa1
`
Although instance is created and proper ssh key is set.
When commenting out "sshkeys" element, it finishes with success:
`
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
`

My config:
`
resource "proxmox_vm_qemu" "cloudinit-test" {
  name = "centos-cloudinit-terraform"
  target_node = "pve-3"
  pool = "tests"
  clone = "centos-cloudinit-template"

  os_type = "cloud-init"
  cores = 2
  sockets = 2
  memory = 4096

  disk {
    id = 0
    size = 8
    type = "virtio"
    storage = "local-lvm"
  }

  network {
    id = 0
    model = "virtio"
    bridge = "vmbr0"
    tag = 53
  }
}
`

**Comment by starcraft66** [comment]
I'm experiencing the same issue as @ata-sql when using sshkeys with cloud-init.

**Comment by starcraft66** [comment]
This appears to happen when there are no ipconfig statements in the cloud-init config.

**Comment by f0rkz** [comment]
I second this. It seems to only be happening when ipconfig0 is not populated.

**Comment by goffinf** [comment]
Unless you specifically want to set a static ip, set ipconfig0 = ip=dhcp

**Comment by solidgoldbomb** [comment]
I just ran into this today and can also confirm a crash.  I can also confirm that adding `ipconfig0 = "ip=dhcp"` avoided the crash.

Looking over the code, I believe this is the sequence that triggers/causes the crash:

In [InitConnInfo()](https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1078)
* config.HasCloudInit() is True
  * Happens when any of `ciuser`, `cipasswd`, `cicustom`, `searchdomain`, `nameserver`, `ssh-keys`, `ipconfig0`, `ipconfig1` are in the config
  * This is consistent with @ata-sql seeing the crash only when adding `ssh-keys` to their config
  * See: [HasCloudInit()](https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/config_qemu.go#L156)
* ssh_forward_ip is not provided
* ipconfig0 is not provided
* The code in the else clause [here](https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1132) assumes that it can match a substring out of (an empty/unprovided ipconfig0) and index into the result to grab the 2nd item.  **This results in a crash.**
