### ISSUE TITLE
Duplicate disks created

### ISSUE THREAD

**Issue by vilhelmprytz** [Telmate/terraform-provider-proxmox#887]
I've had the same issues with Proxmox 8 as a lot of people (like #882 and #863), but when I build this project locally from `master` and use that, then both these problems are solved. However, a new problem arises. The provider is supposed to increase the size of the 2G base image disk that I have, but instead, it seems like it just detaches that disk and creates a new empty one (with the correct size). This new disk is of course not bootable, and the `terraform apply` command stalls.

![image](https://github.com/Telmate/terraform-provider-proxmox/assets/15460993/65d48c4f-8648-4ffe-b4f4-10a1068d0977)

Any idea if this is a known problem? It didn't seem to me like a duplicate of any other open issues right now.

Proxmox: 8.1.3
Provider: local build of latest commit, https://github.com/Telmate/terraform-provider-proxmox/commit/a8675d3967710bab4ac08fad9dbc05eed3ae2c58

**Comment by everythings-gonna-be-alright** [comment]
Cause `pxapi.NewConfigQemuFromApi` function now returns disks in  `Disks *QemuStorages` part of `ConfigQemu` struct. However, the code expects them in `QemuDisks`
`Disks` structure differs in format from `QemuDisks QemuDevices`

https://github.com/Telmate/terraform-provider-proxmox/blob/a8675d3967710bab4ac08fad9dbc05eed3ae2c58/proxmox/resource_vm_qemu.go#L1148C2-L1148C2

**Comment by vilhelmprytz** [comment]
So have you found a solution to this problem? I'm guessing it's something that needs to be fixed with the provider, and not the `.tf` configuration I've used.

**Comment by everythings-gonna-be-alright** [comment]
Unfortunately, it isn't very easy for me. ( insufficient knowledge of GoLang )
As I can see, it is necessary to rewrite a significant part of disk logic.

**Comment by djonko** [comment]
same problem from proxmox  8.1.3 thanks in advance

**Comment by vilhelmprytz** [comment]
@mleone87 Anything new regarding this?

**Comment by ihatethecloud** [comment]
Having the same problem but with TheGameProfi/proxmox.
It seems defining file and volume fixes it but you need to know the id beforehand....

```hcl
  disk {
    size    = "16G"
    type    = "scsi"
    storage = "vg_nvme"
    ssd     = 1
    file    = "vm-108-disk-0"
    volume  = "vg_nvme:vm-108-disk-0"
  }
```

Not sure how to go around this.

**Comment by andrei-matei** [comment]
Having the same issue myself. For now, the provider seems to be unusable.

**Comment by hestiahacker** [comment]
I was able to duplicate this issue in Proxmox 7.4-17 as well. This issue doesn't seem to be related to the version of Proxmox.

I don't think the issues is where [https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1868043544] pointed to because that line hasn't changed in 3 years.

I tried to find the exact commit where this stopped working so we could get a better idea of where the problem was introduced. Unfortunately, there are a lot of commits where the code doesn't compile, which made it difficult to see where the issue was introduced.  Here's the best I could do:

- e51e787c3a792176a6401c2db1b15cb2a30449e0 has this problem
- 704db887ccbe636e2d97bafbc969eee56f99c13a did not have this problem

I spot checked the 24 commits in between and none of them compiled except a8675d3967710bab4ac08fad9dbc05eed3ae2c58, but that one failed because my VM name was `var.fqdn` and dots were not allowed in this version (which was fixed in the e51e787c3a792176a6401c2db1b15cb2a30449e0 commit, which is where I was able to reproduce this issue).

My two guesses for where the problem was introduced are:

I. commit [4a602733bbb5b767eeb79e1b27cf98665c904bb4](https://github.com/Telmate/terraform-provider-proxmox/commit/4a602733bbb5b767eeb79e1b27cf98665c904bb4), specifically the block starting on line [1066](https://github.com/Telmate/terraform-provider-proxmox/blame/master/proxmox/resource_vm_qemu.go#L1064) which adds an additional disk. That change was merged into the default branch with https://github.com/Telmate/terraform-provider-proxmox/pull/732, or
II. commit [d02bb5dba45bdb8e65ed58fccaa885fd6432e6fa](https://github.com/Telmate/terraform-provider-proxmox/commit/d02bb5dba45bdb8e65ed58fccaa885fd6432e6fa), specifically the code block starting line [2202](https://github.com/Telmate/terraform-provider-proxmox/commit/d02bb5dba45bdb8e65ed58fccaa885fd6432e6fa#diff-104365919f693375882979581d9f36f5266991eef361948e56c220931fe886ddR2202) which transforms a list of qemu devices (which includes disk drives).  This was merged into the default branch in https://github.com/Telmate/terraform-provider-proxmox/pull/866

Those guesses are listed in the order of where my gut tells me the issue lies. It's also possible that there was some change in some library that the provider uses, of which there are a ton of them and a lot of them were updated between when I could confirm this issue was not present and when I could reproduce this issue.

I was actually trying to investigate a issue https://github.com/Telmate/terraform-provider-proxmox/issues/704 when I came across this one, so I'm going to go back to trying to identifying the root cause of that issue. Hopefully my notes here will be helpful in someone getting to the bottom of this one before another release is cut.

**Comment by riverar** [comment]
Noticed my recent EFI changes were referenced here (#732). Happy to help debug as well.

**Comment by riverar** [comment]
Can someone provide steps to reproduce and/or proxmox_vm_qemu resource block? I cannot reproduce on Proxmox 8.0.4 / telmate master.

```tf
// before
disk {
  type    = "sata"
  size    = "60G"
  storage = "local-lvm"
  cache   = "writethrough"
  discard = "on"
}

// after
disk {
  type    = "sata"
  size    = "62G"
  storage = "local-lvm"
  cache   = "writethrough"
  discard = "on"
}
```

```
// plan
  # proxmox_vm_qemu.vm1011 will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm1011" {
      ...
      ~ disk {
          ~ size               = "60G" -> "62G"
            # (27 unchanged attributes hidden)
        }
```

Target machine via Proxmox UI:
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/475132/9ff41e45-1502-4f9f-8e04-eec63007c712)

**Comment by hestiahacker** [comment]
I am able to reproduce the issue with the small example below using a provider compiled from commit e51e787c3a792176a6401c2db1b15cb2a30449e0 (the latest as of right now):

```
# Define the usual provider things
terraform {
  required_providers {
    proxmox = {
      source = "registry.example.com/telmate/proxmox"
      version = ">=1.0.0"
      #source = "Telmate/proxmox"
      #version = "=2.9.11"
    }
  }
  required_version = ">= 0.14"
}

resource "proxmox_vm_qemu" "server" {
  name              = "test.example.com"
  target_node       = "ra"
  clone             = "debian-12"
  full_clone        = true
  os_type           = "cloud-init"
  cores             = 1
  sockets           = "1"
  cpu               = "host"
  memory            = 512
  scsihw            = "virtio-scsi-pci"
  bootdisk          = "virtio0"
  disk {
    size            = "20G"
    type            = "virtio"
    cache           = "writeback"
    storage         = "local-zfs"
  }
  network {
    model           = "virtio"
    bridge          = "vmbr0"
  }

  # Cloud Init Settings
  # Reference: https://pve.proxmox.com/wiki/Cloud-Init_Support
  ipconfig0 = "ip=192.168.22.222/22,gw=192.168.22.1"
  nameserver = "192.168.23.100 192.168.22.100"
  sshkeys = file("${path.root}/test.pub")
}
```

I am testing against Proxmox 7.4-17. That created `test.example.com` with two disks: disk-0 (unused), and disk-1 (virtio0). It attempts to boot but just boot loops because it can't find any bootable media.

![issue887](https://github.com/Telmate/terraform-provider-proxmox/assets/116128976/d3bdb1d2-36a0-4d90-be22-0f2a1378476b)

**Comment by riverar** [comment]
Hm, it's not clear if master remains compatible with Proxmox 7.x. Does this repro with the latest release? https://github.com/Telmate/terraform-provider-proxmox/tree/v2.9.14

**Comment by riverar** [comment]
Thanks! Can reproduce here now.

**Comment by riverar** [comment]
Looks like this has broken due to an upstream qemu disks overhaul (https://github.com/Telmate/proxmox-api-go/pull/255) as @everythings-gonna-be-alright suggested (tagging @Tinyblargon), which changed ConfigQemu.QemuDisks behavior. (I suspect the "deprecated" label is in error and it's really just gone/obsolete now.)

This may be expected churn for the master branch, so not _faulting_ anyone here. We just need to do the work to bring the terraform provider back in alignment.

**Comment by Tinyblargon** [comment]
@riverar #794 was supposed to change this behavior when the functionality was changed in the upstream library. Due to some setbacks, this kept getting delayed.

**Comment by riverar** [comment]
@Tinyblargon Oh nice, I missed that PR. Thanks!

**Comment by pescobar** [comment]
We are also hitting this problem with proxmox 8.1.3 and provider `TheGameProfi/proxmox` version `2.9.15`

**Comment by pescobar** [comment]
while debugging this issue I have realized that once I create a new qemu VM and I try `terraform state show` there is no `disk` section for the VM state and that's why the provider tries to add it again.

Weird that during the initial creation of the VM the disk is properly created in the right storage pool and with the right size defined in the terraform code but it's just not added to the terraform state

**Comment by hestiahacker** [comment]
I can confirm that the code that @Tinyblargon wrote does fix this problem. I tested using the same [small example](https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1873548314) that I posted earlier this week.

I've [submitted a merge request](https://github.com/Telmate/terraform-provider-proxmox/pull/889) with Tinyblargon's changes that can be applied cleanly to the HEAD of the default branch here in this repo. I'm pretty sure I've resolved all the merge conflicts correctly, and I have tested it to make sure it fixes this issue, but if anyone else would be willing and able to give it a review, I'd appreciate having a second pair of eyes on this.

And if anyone wants to just check out the code, compile it and verify that it fixes the issue, the code can be found here: https://github.com/hestiahacker/terraform-provider-proxmox/tree/overhaul-qemu-disks Having someone else reproduce my results would be good for avoiding that "works on my box" problem. :slightly_smiling_face:

**Comment by hestiahacker** [comment]
I've also tested an updated terraform file which uses the new syntax for configuring multiple disks. This avoids a deprecation warning from being printed, which makes me happy. My updated terraform file is below.

```
# Define the usual provider things
terraform {
  required_providers {
    proxmox = {
      source = "registry.example.com/telmate/proxmox"
      version = ">=1.0.0"
      #source = "Telmate/proxmox"
      #version = "=2.9.11"
    }
  }
  required_version = ">= 0.14"
}

resource "proxmox_vm_qemu" "server" {
  name              = "test.example.com"
  target_node       = "ra"
  clone             = "debian-12"
  full_clone        = true
  os_type           = "cloud-init"
  cores             = 1
  sockets           = "1"
  cpu               = "host"
  memory            = 512
  scsihw            = "virtio-scsi-pci"
  bootdisk          = "virtio0"
  disks {
    virtio {
      virtio0 {
        disk {
          size            = 20
          cache           = "writeback"
          storage         = "local-zfs"
        }
      }
    }
  }
  network {
    model           = "virtio"
    bridge          = "vmbr0"
  }

  # Cloud Init Settings
  # Reference: https://pve.proxmox.com/wiki/Cloud-Init_Support
  ipconfig0 = "ip=192.168.22.222/22,gw=192.168.22.1"
  nameserver = "192.168.23.100 192.168.22.100"
  sshkeys = file("${path.root}/test.pub")
}
```

**Comment by victormongi** [comment]
@hestiahacker what should we do? are we have to wait until new version release?

**Comment by hestiahacker** [comment]
I compiled the latest code and have been using that and it seems to have fixed this issue and #704. If you need a solution now, I'd suggest you take this route.

There are [instructions for compiling from source](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/guides/installation.md#compile-the-executables-with-go) but if you are compiling it on a Debian based machine, it'd look something like this:

```sh
git clone https://github.com/hestiahacker/terraform-provider-proxmox
cd terraform-provider-proxmox
git checkout overhaul-qemu-disks
sudo apt install -y ansible make
ansible-galaxy install gantsign.ansible-role-golang
ansible-playbook go.yml
. /etc/profile.d/golang.sh
make
```

At that point the new provider should be in the `./bin` directory. If you aren't compiling it on your deployment machine, copy the executable over to the deployer. You'll need to copy the executable into a particular directory on the deployer. Here are the commands from the aforementioned installation guide:

```sh
PLUGIN_ARCH=linux_amd64
mkdir -p ~/.terraform.d/plugins/registry.example.com/telmate/proxmox/1.0.0/${PLUGIN_ARCH}
cp bin/terraform-provider-proxmox ~/.terraform.d/plugins/registry.example.com/telmate/proxmox/1.0.0/${PLUGIN_ARCH}/
```

That source path of the `cp` command will change if you are compiling on a different machine, but that should be easy enough. The last step is to tell Terraform to use this new module. That means updating your terraform to look like this:

```
terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = ">=1.0.0"
    }
  }
  required_version = ">= 0.14"
}
```

That should work, but if you ever need to recompile it, terraform will complain about the checksum having changed. To deal with that you can either manually remove the offending checksum from the `.terraform.lock.hcl` file with a text editor, or what I personally do is just delete that lock file and regenerate it like so:

```sh
rm .terraform.lock.hcl && terraform get -update && terraform init -upgrade && terraform version
```

Also, do realize that this is the latest code that hasn't even been merged into this repo yet, and a fair amount has changed. So there's some risk of bugs causing you problems. I'd suggest you test the code in your environment and with your configuration even more than you would a new, official release. I've tested it in my environment, but if you're using different features than me, you could hit some code path that has a bug that I didn't run into.

If you are in an environment that has a low risk tolerance and you can't test this out, I have two suggestions:
1. Get a test environment! :scream: 
2. Wait for the official release :grin:

**Comment by kw149** [comment]
@hestiahacker thanks for much for the instructions, I was able to follow them (which is saying something).
I'm not a developer and have only started using proxmox / terraform in the last few weeks.
I'm just "testing" this all out in my lab so I have nothing to loose if this all goes wrong.

previously, terraform would create a duplicate scsi disk as well as the virtio, further more each time you "apply" changes it would create another duplicate.
For example making a network device change etc, would result in another additional disk.

Anyway moving on.
I've followed your instructions, tested out, but I have a new error, which I've not seen before:

```
panic: interface conversion: interface {} is string, not float64

goroutine 52 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0003e8718, 0xc9d509?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0003be300, {0xb66f60?, 0xc0003d2e60})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:972 +0x2c4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc0002f6570?}, 0xd?, {0xb66f60?, 0xc0003d2e60?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000e2ee0, {0xdd7840, 0xc0002f6570}, 0xc00037cc30, 0xc0003bf080, {0xb66f60, 0xc0003d2e60})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002e1ef0, {0xdd7840?, 0xc0002f6450?}, 0xc0001ef810)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001a0500, {0xdd7840?, 0xc000525b60?}, 0xc00043fdc0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc0001a0500}, {0xdd7840, 0xc000525b60}, 0xc00043fd50, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00019a1e0, {0xddb420, 0xc0003144e0}, 0xc000515680, 0xc0002edce0, 0x128f7a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00019a1e0, {0xddb420, 0xc0003144e0}, 0xc000515680, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I've not changed any of the .tf files so either I have a miss-configuration or as you mentioned somewhere, there is potential for errors.
thanks again for your efforts.

**Comment by kw149** [comment]
Okay Ignore the above, I made a couple of mistakes, I'll post here incase others do the same thing.

I forgot to update my providers file

```
 proxmox = {
      source = "registry.example.com/telmate/proxmox"
      version = ">=1.0.0"
    }
```

- then follow instructions to clean the lock file

I also needed to update my terraform file, so I changed

```
#  disk {
#    storage = "toaster-vm"
#    type = "scsi"
#    size = "12G"
#  }

disks {
    virtio{
      virtio0 {
        disk {
        size = 12
        storage = "toaster-vm"
        }
      }
    }
  }


```
I can confirm working now. I have a LCX container, Rocky8 and 9 and Ubuntu VM's all working within the same plan


For completeness I did the following 

I had to run the compile as root, I kept getting ansible/golang errors (built using a LCX container so might have something to do with it)
I copied the complied plug-in from /tmp/{compile directory} to my terraform directory (not my home dir)

Change the provider file and then follow instructions to fix the lock
then modify the .tf file(s) for the disk declaration.



However when I changed the plan (made a modification to the description)
It made some modifications 

```
~ disks {
          - ide {
            }
          ~ virtio {
              ~ virtio0 {
                  ~ disk {
                        id                   = 0
                      - replicate            = true -> null
                        # (18 unchanged attributes hidden)
                    }
                }
            }
        }
```


The disk is not duplicated but has a replication flag ?


![Screenshot 2024-01-06 at 11 01 48 am](https://github.com/Telmate/terraform-provider-proxmox/assets/143056162/cf8e77e7-63c2-4a32-add7-5debe385643a)

**Comment by Tchoupinax** [comment]
Hey!
I followed the issue as I'm also impacted since I upgraded Proxmox to v8.1.3.
Following instructions to build the latest version of the provider, I can now start a VM without error. However, I can see the configuration is not the same as previously and expected. It seems the "cloud init" disk is not mounted.

Before:
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/9136206/f09c7d8e-e6d4-4a5c-b762-9eebb4a146cf)

After:
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/9136206/913e8e65-f40c-4937-8145-8c5b4c38ed4c)

What is wrong here:
- Disk size is 10G, which is the size of the template. It should have been overridden (it worked before)
- There is no cloud init drive
- Hard disk has additional parameters which did not have before

**Comment by Tinyblargon** [comment]
@Tchoupinax I've ran a few tests on my end could you try the version in #892 as this has the latest patches.

**Comment by Tchoupinax** [comment]
Hey @Tinyblargon,
I tested your branch and it fixes my previous three issues. I wrote a comment [here](https://github.com/Telmate/terraform-provider-proxmox/pull/892#issuecomment-1880146720).

Thank you a lot for your work!

**Comment by pescobar** [comment]
@TheGameProfi do you plan to publish a new version in your repository including this fix?

**Comment by pescobar** [comment]
thanks @TheGameProfi for publishing a release to terraform registry including this fix. Much appreciated!

**Comment by opentokix** [comment]
> thanks @TheGameProfi for publishing a release to terraform registry including this fix. Much appreciated!

But there is no new version on the hashicorp registry? Or is it published under some other name than Telmate?

**Comment by TheGameProfi** [comment]
> > thanks @TheGameProfi for publishing a release to terraform registry including this fix. Much appreciated!
> 
> But there is no new version on the hashicorp registry? Or is it published under some other name than Telmate? 

It is published as a fork under my own name, thegameprofi/proxmox
There are multiple version with unreleased changes from this repo.
But also, at least the newest version, has problems mounting a cloud-init drive
#901

**Comment by den-patrakeev** [comment]
Hi!
Check work RC v3.0.1-rc1 on Terraform 1.6.6 / 1.7.1 with ProxMox 8.0.4 / 8.1.3.
The error is gone. Everything works well.
Thanks to all!

**Comment by hestiahacker** [comment]
I've also verified that [v3.0.1-rc1](https://github.com/Telmate/terraform-provider-proxmox/discussions/910) is able to deploy the [small example](https://github.com/Telmate/terraform-provider-proxmox/issues/887#issuecomment-1876176138) without any problems.

Thank you all for the testing, fixing, and releasing. :slightly_smiling_face:

**Comment by devZer0** [comment]
i still have this problem with 3.0.1-rc1 and pve 8.1.3, on clone from a template i still get 2 disks and the vm won't boot

what can i do to avoid that 2 disks being created ?

**Comment by devZer0** [comment]
thank you. i have tried further and by chance i found, that when setting the disk size in terraform file to exactly match the size of the disk in vm template, then it won't happen and the disk isn't getting duplicated.

weird.

**Comment by kerem-ak1** [comment]
> Having the same problem but with TheGameProfi/proxmox. It seems defining file and volume fixes it but you need to know the id beforehand....
> 
> ```terraform
>   disk {
>     size    = "16G"
>     type    = "scsi"
>     storage = "vg_nvme"
>     ssd     = 1
>     file    = "vm-108-disk-0"
>     volume  = "vg_nvme:vm-108-disk-0"
>   }
> ```
> 
> Not sure how to go around this.

@ihatethecloud   I wanted to  try this workound but its failing at parameter verification. I'm using zfs though, not sure is it related or not.

latest version of TheGameProfi/proxmox
proxmox version 8.1.4

file    = "vm-137-disk-0"
volume  = "local-zfs:vm-137-disk-0

am i doing something wrong ?

**Comment by ihatethecloud** [comment]
> > Having the same problem but with TheGameProfi/proxmox. It seems defining file and volume fixes it but you need to know the id beforehand....
> > ```terraform
> >   disk {
> >     size    = "16G"
> >     type    = "scsi"
> >     storage = "vg_nvme"
> >     ssd     = 1
> >     file    = "vm-108-disk-0"
> >     volume  = "vg_nvme:vm-108-disk-0"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure how to go around this.
> 
> @ihatethecloud I wanted to try this workound but its failing at parameter verification. I'm using zfs though, not sure is it related or not.
> 
> latest version of TheGameProfi/proxmox proxmox version 8.1.4
> 
> file = "vm-137-disk-0" volume = "local-zfs:vm-137-disk-0
> 
> am i doing something wrong ?

Don’t use TheGameProfi/proxmox. Build this repo if it has not been pushed to the registry yet.

**Comment by kerem-ak1** [comment]
> > > Having the same problem but with TheGameProfi/proxmox. It seems defining file and volume fixes it but you need to know the id beforehand....
> > > ```terraform
> > >   disk {
> > >     size    = "16G"
> > >     type    = "scsi"
> > >     storage = "vg_nvme"
> > >     ssd     = 1
> > >     file    = "vm-108-disk-0"
> > >     volume  = "vg_nvme:vm-108-disk-0"
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Not sure how to go around this.
> > 
> > 
> > @ihatethecloud I wanted to try this workound but its failing at parameter verification. I'm using zfs though, not sure is it related or not.
> > latest version of TheGameProfi/proxmox proxmox version 8.1.4
> > file = "vm-137-disk-0" volume = "local-zfs:vm-137-disk-0
> > am i doing something wrong ?
> 
> Don’t use TheGameProfi/proxmox. Build this repo if it has not been pushed to the registry yet.

If you mean :
source = "Telmate/proxmox"
      version = "3.0.1-rc1"
With this version its still creting empty disks and causing unbootable vm's with or without previous workaround.  Am i using wrong branch ? If so which branch/version i should create  ?  Again thank you for your help.

**Comment by JGHLab** [comment]
> > > > Having the same problem but with TheGameProfi/proxmox. It seems defining file and volume fixes it but you need to know the id beforehand....
> > > > ```terraform
> > > >   disk {
> > > >     size    = "16G"
> > > >     type    = "scsi"
> > > >     storage = "vg_nvme"
> > > >     ssd     = 1
> > > >     file    = "vm-108-disk-0"
> > > >     volume  = "vg_nvme:vm-108-disk-0"
> > > >   }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Not sure how to go around this.
> > > 
> > > 
> > > @ihatethecloud I wanted to try this workound but its failing at parameter verification. I'm using zfs though, not sure is it related or not.
> > > latest version of TheGameProfi/proxmox proxmox version 8.1.4
> > > file = "vm-137-disk-0" volume = "local-zfs:vm-137-disk-0
> > > am i doing something wrong ?
> > 
> > 
> > Don’t use TheGameProfi/proxmox. Build this repo if it has not been pushed to the registry yet.
> 
> version = "3.0.1-rc1" is out from telmate provider.
> 
> new version comes with different disk schema, I had to update my disk schema in tf file, now it works. its still has some glitches regarding disk type/controller though. anway thx to everyone !
> 
> ps:if someone needs a running example with clone_ _from_template+cloudinit+lvm/zfs can ping me.

Could you give me working example? I can't get mine to work as I get an unbootable disk error and the hardware settings are incorrect.

**Comment by kerem-ak1** [comment]
> > > > > Having the same problem but with TheGameProfi/proxmox. It seems defining file and volume fixes it but you need to know the id beforehand....
> > > > > ```terraform
> > > > >   disk {
> > > > >     size    = "16G"
> > > > >     type    = "scsi"
> > > > >     storage = "vg_nvme"
> > > > >     ssd     = 1
> > > > >     file    = "vm-108-disk-0"
> > > > >     volume  = "vg_nvme:vm-108-disk-0"
> > > > >   }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Not sure how to go around this.
> > > > 
> > > > 
> > > > @ihatethecloud I wanted to try this workound but its failing at parameter verification. I'm using zfs though, not sure is it related or not.
> > > > latest version of TheGameProfi/proxmox proxmox version 8.1.4
> > > > file = "vm-137-disk-0" volume = "local-zfs:vm-137-disk-0
> > > > am i doing something wrong ?
> > > 
> > > 
> > > Don’t use TheGameProfi/proxmox. Build this repo if it has not been pushed to the registry yet.
> > 
> > 
> > version = "3.0.1-rc1" is out from telmate provider.
> > new version comes with different disk schema, I had to update my disk schema in tf file, now it works. its still has some glitches regarding disk type/controller though. anway thx to everyone !
> > ps:if someone needs a running example with clone_ _from_template+cloudinit+lvm/zfs can ping me.
> 
> Could you give me working example? I can't get mine to work as I get an unbootable disk error and the hardware settings are incorrect.

`# Source the Cloud Init Config file
data "template_file" "cloud_init_jammy_test-converter01" {
  template  = "${file("${path.module}/files/cloud_init_jammy-lite.cloud_config")}"

  vars = {
    ssh_key = file("files/terraform-pve.pub")
    hostname = "test-converter01"
    domain = "test-domain.fqdn"
  }
}
##########################################################################################################################################################################################################
# Create a local copy of the file, to transfer to Proxmox
resource "local_file" "cloud_init_jammy_test-converter01" {
  content   = data.template_file.cloud_init_jammy_test-converter01.rendered
  filename  = "${path.module}/files/user_data_cloud_init_jammy_test-converter01.cfg"
}
##########################################################################################################################################################################################################
# Transfer the file to the Proxmox Host
resource "null_resource" "cloud_init_jammy_test-converter01" {
  connection {
    type    = "ssh"
    user    = "root"
    private_key = file("files/terraform-pve")
    host    = "pve01"
  }
##########################################################################################################################################################################################################
  provisioner "file" {
    source       = local_file.cloud_init_jammy_test-converter01.filename
    destination  = "/var/lib/vz/snippets/cloud_init_jammy_test-converter01.yml"
  }
}
##########################################################################################################################################################################################################
#Define virtual machine's specs as variables
  variable "test-converter01" {
    type = map(string)
    description = "Vm variables must be declared here"
    default = {
    "proxmox_node" = "pve01"
    "vm_id" = "151"
    "name" = "test-converter01"
    "domain" = "dev fqdn"
    "desc" = "test-converter "
    "clone_name" = "jammy-cloudinit"
    "os_type" = "cloud-init"
    "onboot_status" = "true"
    "cpu_type" = "host"
    "sockets" = "2"
    "cores" = "2"
    "mem" = "2048"
    "network0_model" = "virtio"
    "network0_bridge" = "vmbr2"
    "network0_mac" = ""
    "network0_IP" = "ip=192.168.X.X/16,gw=192.168.X.X" # this sets for nat ip from proxmox
    "network1_model" = "virtio"
    "network1_mac" = "mac of your vm"
    "network1_IP" = "ip=dhcp"
    "network1_bridge" = "vmbr1"
    "storage_class" = "local-zfs"
    "storage_interface" = "virtio"
    "disk0_size" = 30
    #"disk1_size" = "50G"
    }
  } 
##########################################################################################################################################################################################################  
resource "proxmox_vm_qemu" "test-converter01" { 

    depends_on = [
    null_resource.cloud_init_jammy_test-converter01
  ]

    target_node = var.test-converter01.proxmox_node
    vmid = var.test-converter01.vm_id
    name = var.test-converter01.name
    desc = var.test-converter01.desc
    vcpus = 2 # it will calculated by proxmox socket*core
    os_type = var.test-converter01.os_type
    onboot = var.test-converter01.onboot_status
    clone = var.test-converter01.clone_name
    agent = 1
    qemu_os = "l26"
    scsihw = "virtio-scsi-single"
    cloudinit_cdrom_storage = "local-zfs"
    cores = var.test-converter01.cores
    sockets = var.test-converter01.sockets
    cpu = var.test-converter01.cpu_type
    memory = var.test-converter01.mem
     network {

         model  = var.test-converter01.network0_model
         bridge = var.test-converter01.network0_bridge
        

     }
    network {

        bridge = var.test-converter01.network1_bridge
        model  = var.test-converter01.network1_model
        macaddr = var.test-converter01.network1_mac
    }
    lifecycle {
      ignore_changes = [
        network
      ]
   }
   disks {
       virtio {
           virtio0 {
               disk {
                 storage = var.test-converter01.storage_class
                 size = var.test-converter01.disk0_size
                    }
                }
           }
        }
    


    cicustom = "user=local:snippets/cloud_init_jammy_test-converter01.yml"
    ipconfig0 = var.test-converter01.network0_IP
    ipconfig1 = var.test-converter01.network1_IP
    }`

**Comment by devZer0** [comment]
not stale

**Comment by sruocco-i2r** [comment]
> ps:if someone needs a running example with clone_ _from_template+cloudinit+lvm/zfs can ping me.

I and probably others would appreciate that. Could you please post it here (for everyone's benefit)? Thanks.

**Comment by Alcatraz077** [comment]
I'm having the same issue

**Comment by SujithThirumalaisamy** [comment]
+1

**Comment by williampayne23** [comment]
+1

**Comment by kw149** [comment]
Working for me

Provider.tf

```
   proxmox = {
      source = "Telmate/proxmox"
      version = "=3.0.2-rc01"
  }
```

VM Template
```

resource "proxmox_vm_qemu" "someserver" {
    
  # VM General Settings
  target_node = "pve1"
  vmid = 500
  name = "test1"
  desc = "Terraform Environment : ${var.environment}"
  tags = var.template_tags
  qemu_os = "l26"
  os_type = "cloud-init"
  onboot = var.OnBoot 
  # Source
  clone = "packer-ubuntu-template"
  # VM OS Settings
  agent = var.template_qemu_agent

  cpu {
    cores = var.vm_med_cores
    sockets = var.vm_med_sockets
    type = var.template_host_cpu
  }
  
  memory = var.vm_large_memory 
  boot = "order=virtio0;net0"
  # VM Network Settings
  network {
    id = 0
    bridge = var.env_netBridge
    model  = "virtio"
    mtu = "1"
  }
  scsihw = "virtio-scsi-pci"
  disks {
      virtio{
        virtio0 {
          disk {
          size = 30
          storage = var.env_storage
          # format = "qcow2" # Removed for RC4+
          }
        }
      }
      ide{
        ide3 {
          cloudinit {
            storage = var.env_storage
          }
        }
      }
  }
  # (Optional) IP Address and Gateway

  ipconfig0 = "ip=192.168.1.30/24,gw=192.168.1.1"
  nameserver = "192.168.50.1"
  skip_ipv6 = true
}

```

**Comment by Scholdan** [comment]
+1
