### ISSUE TITLE
LXC Mountpoint - index out of range at proxmox.DiskSizeGB

### ISSUE THREAD

**Issue by DavidFair** [Telmate/terraform-provider-proxmox#975]
Using the latest RC, I expected that #806 would allow me to create a bind mount without specifying the size. 

However, attempting to create a bind mount without size results in a panic as I think the underlying API expects a 1:1 mapping of mounts to disk sizes when iterating through an array

main.tf:

```
required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "3.0.1-rc1"
    }
  }
}

resource "proxmox_lxc" "test" {
  target_node  = "pve"
  hostname     = "test"
  ostemplate   = "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
  unprivileged = false
  start        = true
  onboot       = true

  rootfs {
    storage = "local-zfs"
    size    = "10G"
  }

  mountpoint {
    key     = "0"
    slot    = 0
    storage = "/media-pool"
    mp      = "/media"
    # size    = "10G"
  }
```

Results in the following stack trace:
```
Stack trace from the terraform-provider-proxmox_v3.0.1-rc1 plugin:

panic: runtime error: index out of range [1] with length 0

goroutine 52 [running]:
github.com/Telmate/proxmox-api-go/proxmox.DiskSizeGB({0xc0a600?, 0xe5a770?})
        github.com/Telmate/proxmox-api-go@v0.0.0-20240123211857-586199ea9da2/proxmox/util.go:127 +0x18a
github.com/Telmate/proxmox-api-go/proxmox.FormatDiskParam(0xd3108a?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20240123211857-586199ea9da2/proxmox/config_qemu.go:1461 +0x2be
github.com/Telmate/proxmox-api-go/proxmox.ConfigLxc.mapToApiValues({{0xc00014a7c0, 0x38}, {0xc0001ae4b4, 0x5}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0xc0001ae4ca, ...}, ...})
        github.com/Telmate/proxmox-api-go@v0.0.0-20240123211857-586199ea9da2/proxmox/config_lxc.go:477 +0x2cc
github.com/Telmate/proxmox-api-go/proxmox.ConfigLxc.CreateLxc({{0xc00014a7c0, 0x38}, {0xc0001ae4b4, 0x5}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0xc0001ae4ca, ...}, ...}, ...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20240123211857-586199ea9da2/proxmox/config_lxc.go:336 +0x9e
github.com/Telmate/terraform-provider-proxmox/v2/proxmox.resourceLxcCreate(0x0?, {0xbe49a0?, 0xc000181bd0?})
        github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_lxc.go:599 +0x14e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xe63b60?, {0xe63b60?, 0xc0001a7080?}, 0xd?, {0xbe49a0?, 0xc000181bd0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000193180, {0xe63b60, 0xc0001a7080}, 0xc00012b6c0, 0xc000808900, {0xbe49a0, 0xc000181bd0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001d4000, {0xe63b60?, 0xc0001a6f60?}, 0xc00080a0a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001da000, {0xe63b60?, 0xc0001a6540?}, 0xc000246770)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd09ee0?, 0xc0001da000}, {0xe63b60, 0xc0001a6540}, 0xc0001d6080, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000209800, {0xe63b60, 0xc0001a64b0}, {0xe677f8, 0xc000007a00}, 0xc000802000, 0xc000198660, 0x137c578, 0x0)
        google.golang.org/grpc@v1.61.0/server.go:1385 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000209800, {0xe677f8, 0xc000007a00}, 0xc000802000)
        google.golang.org/grpc@v1.61.0/server.go:1796 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.0/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.61.0/server.go:1040 +0x145
```

Uncommenting the disk size resolves this error.

On an unrelated note: It's not currently obvious that size is optional in the latest RC, so I spent a significant amount of time wondering how to correctly do bind mounts where it apply
I'm happy to throw up an example / update the docs for bind mounts once this is working, as they got missed in the original PR

**Comment by bmeyer71** [comment]
One other thing to note is that bind mounts can only be created using the root@pam and the related password. Not even using an API token will work. That is at lease according to [this post](https://forum.proxmox.com/threads/is-it-possible-to-deploy-lxc-container-through-the-api-with-bind-mounts.124543/).

**Comment by Tinyblargon** [comment]
Upstream, there is a reimplemtation of LXC going on.
