### ISSUE TITLE
Interface Conversion Panic on VM Creation using terraform-provider-proxmox_v2.9.14

### ISSUE THREAD

**Issue by muks198** [Telmate/terraform-provider-proxmox#998]
Hi,

I upgraded Proxmox to 8.2.2 and now I am receiving the following error when cloning from an existing template:

```
proxmox_vm_qemu.test[0]: Creating...
╷
│ Error: Request cancelled
│ 
│   with proxmox_vm_qemu.test[0],
│   on main.tf line 1, in resource "proxmox_vm_qemu" "test":
│    1: resource "proxmox_vm_qemu" "test" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 12 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0005920c0, 0xc00041f4e8?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.prepareDiskSize(0x0?, 0xc00003891c?, 0x4?, 0x0?)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1737 +0xeb
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000554780, {0xb66f60?, 0xc000348a50})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1059 +0x1cb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc000016db0?}, 0xd?, {0xb66f60?, 0xc000348a50?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000196ee0, {0xdd7840, 0xc000016db0}, 0xc0001eef70, 0xc000554900, {0xb66f60, 0xc000348a50})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00041fed8, {0xdd7840?, 0xc000016c90?}, 0xc000150320)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002b83c0, {0xdd7840?, 0xc000016270?}, 0xc0001c2230)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc0002b83c0}, {0xdd7840, 0xc000016270}, 0xc0001c2070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00025c1e0, {0xddb420, 0xc00048a1a0}, 0xc0001c0000, 0xc00042d800, 0x128f7a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00025c1e0, {0xddb420, 0xc00048a1a0}, 0xc0001c0000, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Here is what is being applied using ```terraform apply```

```
resource "proxmox_vm_qemu" "test" {
  count = 1
  name = "core"
  target_node = "pve01"
  vmid = 110

  os_type = "cloud-init"
  clone = "template-ubuntu-22-04"
  full_clone = true
}
```

I experience no issues cloning using the Proxmox GUI.

Any thoughts on how this can be resolved?

**Comment by rpersee** [comment]
Hi, same issue for me:
```
proxmox_vm_qemu.instance: Creating...
proxmox_vm_qemu.instance: Still creating... [10s elapsed]
proxmox_vm_qemu.instance: Still creating... [20s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.instance,
│   on main.tf line 13, in resource "proxmox_vm_qemu" "instance":
│   13: resource "proxmox_vm_qemu" "instance" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 55 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000268718, 0xc9d509?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000127000, {0xb66f60?, 0xc0004c4230})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:972 +0x2c4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc000281410?}, 0xd?, {0xb66f60?, 0xc0004c4230?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003407e0, {0xdd7840, 0xc000281410}, 0xc0004a0f70, 0xc000126d80, {0xb66f60, 0xc0004c4230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003cab70, {0xdd7840?, 0xc000281230?}, 0xc0004c4910)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00029a3c0, {0xdd7840?, 0xc0002807b0?}, 0xc0004bc310)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc00029a3c0}, {0xdd7840, 0xc0002807b0}, 0xc0004bc0e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003e4000, {0xddb420, 0xc0003e91e0}, 0xc000176000, 0xc0003e6bd0, 0x128f7a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0003e4000, {0xddb420, 0xc0003e91e0}, 0xc000176000, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
With `main.tf`:
```terraform
terraform {
  required_providers {
    proxmox = {
      source = "Telmate/proxmox"
    }
  }
}

provider "proxmox" {}

resource "proxmox_vm_qemu" "instance" {
  name        = "tf-instance"
  desc        = "Terraform instance"
  target_node = "localhost"

  clone = "VM 9001"

  provisioner "remote-exec" {
    inline = [
      "ip a"
    ]
  }
}
```

**Comment by rpersee** [comment]
Switching to provider version "3.0.1-rc1" solves the issue.

**Comment by Aleksei-2021** [comment]
> Switching to provider version "3.0.1-rc1" solves the issue.
Hi! I have the same error 400. How did you update the plugin to 3.0.1-rc1?
